{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.2.aar",
          "url": "shared_preferences_android_release-10.2.aar",
          "size": 89515,
          "sha512": "e11ce0dfd08bbde09d99683a7ae78b350cf367bc59f7eb288e5567bae59479656fb10599bf030c720693e2562b9f460b02d00e883b2aa05d3990b810eb8a72c6",
          "sha256": "78dd26c83afc0cac4fb98fe39cff259a592ea7ffb5dda0bfc7cabdf7688fd7d9",
          "sha1": "226fa4d44fa8b10d7a6dcb60da0815349e4bdcb1",
          "md5": "303c4f4df62d65e4deeff6c30efb91d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.2.aar",
          "url": "shared_preferences_android_release-10.2.aar",
          "size": 89515,
          "sha512": "e11ce0dfd08bbde09d99683a7ae78b350cf367bc59f7eb288e5567bae59479656fb10599bf030c720693e2562b9f460b02d00e883b2aa05d3990b810eb8a72c6",
          "sha256": "78dd26c83afc0cac4fb98fe39cff259a592ea7ffb5dda0bfc7cabdf7688fd7d9",
          "sha1": "226fa4d44fa8b10d7a6dcb60da0815349e4bdcb1",
          "md5": "303c4f4df62d65e4deeff6c30efb91d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.2-sources.jar",
          "url": "shared_preferences_android_release-10.2-sources.jar",
          "size": 10391,
          "sha512": "c868c1a7019fbb013fc8f7393122f858679c552ee0b0521b78fd01d85a7e22b805f61c1c78db0c81d3d68ca28cb891a1450cbc3be4566fb39ffbc055a7bc22a1",
          "sha256": "4b7a533aea864be65713bbe35408e2eeaaf886febc2e0ff80f6d86c800f0eae9",
          "sha1": "e8a73be85d3672522581e4d702ba7289cd7a69ef",
          "md5": "e196aac4401e72d313a388902984ab00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.2-javadoc.jar",
          "url": "shared_preferences_android_release-10.2-javadoc.jar",
          "size": 326414,
          "sha512": "24d108a87951416353ff7bef6d837788a29ec6ac705eb0396ec5d7b5280e220da4f7bdaf6295ca762d8bfc7e8cc5cbfcfd3a2d94fa5935b9082bda6e39db6933",
          "sha256": "83d0c61295ac21dfbe17cf499de9d57493a35e56ab6f30a4c828b6ed4f725813",
          "sha1": "84ac0cd5168ad582921a1b1af570a93ff986ffa6",
          "md5": "a4d7bf45c74c1b14cb705b07def59059"
        }
      ]
    }
  ]
}
