{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-6.8.aar",
          "url": "azure_speech_release-6.8.aar",
          "size": 10903,
          "sha512": "9a82058abb98d900cbd31b7dd6e0734f88caa20944d48f4c02cc5d3294e85969a3334c3f49f5857a528b281c324466f987a2e93292c4ec1767d641c1092113c8",
          "sha256": "996fa9e661ca8f365e3d1045cfcb93c19da93e2706fea516bb4c68b1a0477d16",
          "sha1": "f1973707ee6e3d5abd529722039e980a77bfd36a",
          "md5": "fef5ad0e6a08bc0c319d16dc375da2c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-6.8.aar",
          "url": "azure_speech_release-6.8.aar",
          "size": 10903,
          "sha512": "9a82058abb98d900cbd31b7dd6e0734f88caa20944d48f4c02cc5d3294e85969a3334c3f49f5857a528b281c324466f987a2e93292c4ec1767d641c1092113c8",
          "sha256": "996fa9e661ca8f365e3d1045cfcb93c19da93e2706fea516bb4c68b1a0477d16",
          "sha1": "f1973707ee6e3d5abd529722039e980a77bfd36a",
          "md5": "fef5ad0e6a08bc0c319d16dc375da2c7"
        }
      ]
    }
  ]
}
