{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.22.aar",
          "url": "sqflite_android_release-0.0.22.aar",
          "size": 43114,
          "sha512": "d503f9bfda65979de31a2fae5f8f09ba4c0dffc2e4b103bafed743ad856f6fe846942769cfdfd1a6b7b002a547ad66254c23079af4e8761a3644c8c1db9ae130",
          "sha256": "9853dd219a077ace534dd5baca1a95ba8c4472db8a138054784c5625cd97dfe0",
          "sha1": "dc898fa37aef3652ebae2d18055ae54079786cdc",
          "md5": "abc510276235f235e95d5194735e8ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.22.aar",
          "url": "sqflite_android_release-0.0.22.aar",
          "size": 43114,
          "sha512": "d503f9bfda65979de31a2fae5f8f09ba4c0dffc2e4b103bafed743ad856f6fe846942769cfdfd1a6b7b002a547ad66254c23079af4e8761a3644c8c1db9ae130",
          "sha256": "9853dd219a077ace534dd5baca1a95ba8c4472db8a138054784c5625cd97dfe0",
          "sha1": "dc898fa37aef3652ebae2d18055ae54079786cdc",
          "md5": "abc510276235f235e95d5194735e8ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.22-sources.jar",
          "url": "sqflite_android_release-0.0.22-sources.jar",
          "size": 23748,
          "sha512": "79a18e8544303c175a5518d48dc0d23a617f6da7f5ddf699a7e94e154c1a221a1182d6b22363d34103e63d7e17decb835bdc2e3e92bfe0d08b1be7349ecc3847",
          "sha256": "7c4ef41dcd75693d0abddc88b3ba5c2fd30c31ee71155462d81055d982095868",
          "sha1": "8b554a039e5de13b3998bf9f2a1ef11cda40c2f1",
          "md5": "54e2ffa57d01fe69ac670dda7fb4b5f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.22-javadoc.jar",
          "url": "sqflite_android_release-0.0.22-javadoc.jar",
          "size": 339894,
          "sha512": "813a5bb117e0a07008b37b130ed48841c8d037de5407e56905b98e05e27b9fa66cd9ae348e4012fd26f36f033e1a3766f4c619afa5f0df7817bd288420cf9cd7",
          "sha256": "2c6729bc7a6a59fb957cfc9a214b133852ce66961dc9838b94204b58d8fe51ec",
          "sha1": "2f31f7fb35ea670196a97e11274cdc9cf66664e0",
          "md5": "0dd9cb0786486d2b56d13d9ee80a035c"
        }
      ]
    }
  ]
}
