{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "0.0.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.55.aar",
          "url": "shared_preferences_android_release-0.0.55.aar",
          "size": 112329,
          "sha512": "f73774b1ac92421b8df7fb4d99b1188f4dc86ca8d17794d5ba731f7009bf7336ddb589f5a02cba7f500eb1db1ffdb1c3083e0185cb20a381ea697e61d5764eb8",
          "sha256": "47ff00186aa60d5eb8b5b384f4846c4c444417a4c7749af7d1d8d6a56364945d",
          "sha1": "e469923958f02def716d95323a2033bcb0517104",
          "md5": "f26895e03540929d7503ea9814cee662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.55.aar",
          "url": "shared_preferences_android_release-0.0.55.aar",
          "size": 112329,
          "sha512": "f73774b1ac92421b8df7fb4d99b1188f4dc86ca8d17794d5ba731f7009bf7336ddb589f5a02cba7f500eb1db1ffdb1c3083e0185cb20a381ea697e61d5764eb8",
          "sha256": "47ff00186aa60d5eb8b5b384f4846c4c444417a4c7749af7d1d8d6a56364945d",
          "sha1": "e469923958f02def716d95323a2033bcb0517104",
          "md5": "f26895e03540929d7503ea9814cee662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.55-sources.jar",
          "url": "shared_preferences_android_release-0.0.55-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.55-javadoc.jar",
          "url": "shared_preferences_android_release-0.0.55-javadoc.jar",
          "size": 358450,
          "sha512": "aee7c0a023ba3ed7d7a35cf4b0e4403b2362c87c7bdcf11836f3c1e49cfc45f7f8c1e9cf6048ca764882cc84341f9370fc7b43dc5faee63317e534b74e03ee16",
          "sha256": "3a62586fbbc000203479470cb71cdbf77f01cace0d5c9cd7bc14c8e7cc755cfe",
          "sha1": "9559cabe802c00d75a82aaa25b8d792321b00565",
          "md5": "c2dd91f3a458fe6ecd7fdca6c07d1691"
        }
      ]
    }
  ]
}
