{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-3.2.aar",
          "url": "sbc_release-3.2.aar",
          "size": 73283,
          "sha512": "269ff9d58b4bc9f33a2a73bce13760cd7eb074c3a6a00d94c9d103e771014f5307b556cb5bd55e856e764d0fd85ace317001fd62938cb3b0d60524d18f9626d8",
          "sha256": "e7c0fb49ee426193834c869f1a38759d5edb95edc84a482be461b2a2201bb3d6",
          "sha1": "b7131e13757662c6262dbd34572284eee58c9cf9",
          "md5": "30894ccf72bf0c7485227e8093ec5201"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-3.2.aar",
          "url": "sbc_release-3.2.aar",
          "size": 73283,
          "sha512": "269ff9d58b4bc9f33a2a73bce13760cd7eb074c3a6a00d94c9d103e771014f5307b556cb5bd55e856e764d0fd85ace317001fd62938cb3b0d60524d18f9626d8",
          "sha256": "e7c0fb49ee426193834c869f1a38759d5edb95edc84a482be461b2a2201bb3d6",
          "sha1": "b7131e13757662c6262dbd34572284eee58c9cf9",
          "md5": "30894ccf72bf0c7485227e8093ec5201"
        }
      ]
    }
  ]
}
