{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-0.0.30.aar",
          "url": "sbc_release-0.0.30.aar",
          "size": 72199,
          "sha512": "8a60418f455b16c0aee485e17672f01c92d970698437503b4e1612a5be38db2e131db896c792df2c807d962e1dc8e611ab97ee62c372ee0d1d4d504416c331c0",
          "sha256": "28a6f1fd93a7c01e2cd2631179bc68da12e77a7a9b4065e93e7b09ed63d7546a",
          "sha1": "33ad7f07ba193e290f3719c9b9fc40a7701a0a09",
          "md5": "ef47626821ece7b0b45c35ddd055406c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-0.0.30.aar",
          "url": "sbc_release-0.0.30.aar",
          "size": 72199,
          "sha512": "8a60418f455b16c0aee485e17672f01c92d970698437503b4e1612a5be38db2e131db896c792df2c807d962e1dc8e611ab97ee62c372ee0d1d4d504416c331c0",
          "sha256": "28a6f1fd93a7c01e2cd2631179bc68da12e77a7a9b4065e93e7b09ed63d7546a",
          "sha1": "33ad7f07ba193e290f3719c9b9fc40a7701a0a09",
          "md5": "ef47626821ece7b0b45c35ddd055406c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sbc_release-0.0.30-sources.jar",
          "url": "sbc_release-0.0.30-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sbc_release-0.0.30-javadoc.jar",
          "url": "sbc_release-0.0.30-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
