{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sleep_stage_algorithm",
    "module": "creek_sleep_stage_algorithm_release",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.43.aar",
          "url": "creek_sleep_stage_algorithm_release-0.0.43.aar",
          "size": 20497,
          "sha512": "9deed010b63470dbf7f1a508870d5bb4e842af56abcd5517b6fa322bc45cdd210c8ac0a5bbe4bf7ba03aebfb81fc972f9c8ddf8f62f73e4c7eadd24cdbd37389",
          "sha256": "42235346f8d0f19016276440d928c411aff82b34971fc7ecba379849db14dfe2",
          "sha1": "bacd4a0b3ff3194c23e3bd5190964f779738c15b",
          "md5": "59829f0152d029c676b7995dfa362315"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.43.aar",
          "url": "creek_sleep_stage_algorithm_release-0.0.43.aar",
          "size": 20497,
          "sha512": "9deed010b63470dbf7f1a508870d5bb4e842af56abcd5517b6fa322bc45cdd210c8ac0a5bbe4bf7ba03aebfb81fc972f9c8ddf8f62f73e4c7eadd24cdbd37389",
          "sha256": "42235346f8d0f19016276440d928c411aff82b34971fc7ecba379849db14dfe2",
          "sha1": "bacd4a0b3ff3194c23e3bd5190964f779738c15b",
          "md5": "59829f0152d029c676b7995dfa362315"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.43-sources.jar",
          "url": "creek_sleep_stage_algorithm_release-0.0.43-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.43-javadoc.jar",
          "url": "creek_sleep_stage_algorithm_release-0.0.43-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
