{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni",
    "module": "jni_release",
    "version": "10.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-10.9.aar",
          "url": "jni_release-10.9.aar",
          "size": 114416,
          "sha512": "92fa183f9a06d64994dbc0681a29ca0081e3bb39df210e2c041f727f2281f3e0406653075770c725dd3adc005e6426b7f110e3bd30203137b91121697aa6975e",
          "sha256": "fdb2629d55d682817f4cb00e47e34842f160c1db04a8a6829091f570f473c08d",
          "sha1": "8b32a21df38aff31c1c980e8cb1a8bc5684c514b",
          "md5": "d62c288e8c1b7c653276df525451a791"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-10.9.aar",
          "url": "jni_release-10.9.aar",
          "size": 114416,
          "sha512": "92fa183f9a06d64994dbc0681a29ca0081e3bb39df210e2c041f727f2281f3e0406653075770c725dd3adc005e6426b7f110e3bd30203137b91121697aa6975e",
          "sha256": "fdb2629d55d682817f4cb00e47e34842f160c1db04a8a6829091f570f473c08d",
          "sha1": "8b32a21df38aff31c1c980e8cb1a8bc5684c514b",
          "md5": "d62c288e8c1b7c653276df525451a791"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-10.9-sources.jar",
          "url": "jni_release-10.9-sources.jar",
          "size": 5459,
          "sha512": "61c8d0b11708383673e2d967abe5948df4f9f1c20f77852bfc8e4da61a83bb5c2e7561a02692dc183a64b4f842555d66ebd142d02b6295313fcda91f9e8e0c15",
          "sha256": "0762cdfe1e25701b53f0e55fde69135e74f25328f4b1c60e4778701833bfab6e",
          "sha1": "09a60f323f1b590e7921cd33327514fe4d916cb1",
          "md5": "3cf8aa129d418b4388b02cea9ff9819b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-10.9-javadoc.jar",
          "url": "jni_release-10.9-javadoc.jar",
          "size": 282732,
          "sha512": "1dbf962fd455b5910c9010cc43331818c4a6385e93027b109689690c207dbc692673abb7971330b7f827388b5a7daa219bf4b7bd5d6211c7f9a49f6e40954ea3",
          "sha256": "6394c7bbb56df271bfeb39af2eb14a04e4ee003a044a1a20588d07a67b01687e",
          "sha1": "bef38604f201f64c7c026b0433e405ac0d737a57",
          "md5": "2565ed16a28cb94c9d313d9c901bda2a"
        }
      ]
    }
  ]
}
