{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "10.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-10.8.aar",
          "url": "package_info_plus_release-10.8.aar",
          "size": 5765,
          "sha512": "1ad40f4fa78f0073aea6f63bf62bfc97866a536c62b87789dc4d3fa7545d82072408d3beb4c394d9f47efd6a91e51513d0a932ab45140a13014791ea1329d212",
          "sha256": "cb9d41e58f8ba2b465a5a46d19b0a7e51e598ddb74d678d66cc541e469278dee",
          "sha1": "b7665802eeb8890976bb5e97da8654368c1df5de",
          "md5": "503dabe3b2f7a843a99a636647080eb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-10.8.aar",
          "url": "package_info_plus_release-10.8.aar",
          "size": 5765,
          "sha512": "1ad40f4fa78f0073aea6f63bf62bfc97866a536c62b87789dc4d3fa7545d82072408d3beb4c394d9f47efd6a91e51513d0a932ab45140a13014791ea1329d212",
          "sha256": "cb9d41e58f8ba2b465a5a46d19b0a7e51e598ddb74d678d66cc541e469278dee",
          "sha1": "b7665802eeb8890976bb5e97da8654368c1df5de",
          "md5": "503dabe3b2f7a843a99a636647080eb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-10.8-sources.jar",
          "url": "package_info_plus_release-10.8-sources.jar",
          "size": 2626,
          "sha512": "d29752460899631baee24b502608ec59283d4227d7ad35b4fef67f668381b5e5a6d3beefdb30ecf7015fc9e274b202a0efee3ef8c488a9f7d914c89ce368fde7",
          "sha256": "60a4f6359d1000d36e515b035f0b9f07f2861ed2477ef28d1fed8b9e37466437",
          "sha1": "e02c3b77b67d0f8364bd68f442715888cff6e59c",
          "md5": "9664599475a97471a062a35def69698f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-10.8-javadoc.jar",
          "url": "package_info_plus_release-10.8-javadoc.jar",
          "size": 264968,
          "sha512": "71fd322ab7cff9d6d0b0500d0ca6c4a53a22cfc6ac463d7fcb92ec9b9dd5ebb3518fa7e24a74b110de5feef1e7f24970afbc69fa46e2a33a963d9188a738003b",
          "sha256": "dd25d086329a2a7abe970f8a9fa72883a1c49a68ec24c7ed3f231728063f4e34",
          "sha1": "502a269c6c9df62846b92c501bc9b91e8ea706e3",
          "md5": "658e7e9b0173c0a544a25320b69925fd"
        }
      ]
    }
  ]
}
