{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sdk",
    "module": "flutter_release",
    "version": "3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.actions.actres",
          "module": "actres_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-3.1.aar",
          "url": "flutter_release-3.1.aar",
          "size": 8656023,
          "sha512": "fd39c860f0f57c8d4af5890d57d8fd838b0c59d1b7aab05d962d74831cf075f20facd74b9464d53b6fdb1871dc9bf159e25158c34be2172e824977deca9702ee",
          "sha256": "7c14c1a2b767184c16c1618845cfbae473fc9e6390e0c61ad28a6eda13e460f4",
          "sha1": "cd269c3a27e51381526a81254ae68e16d03d697a",
          "md5": "212504a8fad23f8203fa112b787d17ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.actions.actres",
          "module": "actres_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-3.1.aar",
          "url": "flutter_release-3.1.aar",
          "size": 8656023,
          "sha512": "fd39c860f0f57c8d4af5890d57d8fd838b0c59d1b7aab05d962d74831cf075f20facd74b9464d53b6fdb1871dc9bf159e25158c34be2172e824977deca9702ee",
          "sha256": "7c14c1a2b767184c16c1618845cfbae473fc9e6390e0c61ad28a6eda13e460f4",
          "sha1": "cd269c3a27e51381526a81254ae68e16d03d697a",
          "md5": "212504a8fad23f8203fa112b787d17ae"
        }
      ]
    }
  ]
}
