{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.13.aar",
          "url": "path_provider_android_release-0.0.13.aar",
          "size": 10143,
          "sha512": "619cb779acaf2ec8ef04f8067d51166a5e65e8d975a1afed7a1cbb0a3cd62c8b21083f8628e4d1ef9a3281be8dabcb328b873e617b4638038f9d11a72ee37918",
          "sha256": "7d2b64535a70e132f40eb9eb2e75ff72435ea5d23c539a197e03fd5f3265ba4c",
          "sha1": "a387555930fd6a8431eee41e8882b7ca226f8983",
          "md5": "184e390219e8e13e507506d2eb070f89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.13.aar",
          "url": "path_provider_android_release-0.0.13.aar",
          "size": 10143,
          "sha512": "619cb779acaf2ec8ef04f8067d51166a5e65e8d975a1afed7a1cbb0a3cd62c8b21083f8628e4d1ef9a3281be8dabcb328b873e617b4638038f9d11a72ee37918",
          "sha256": "7d2b64535a70e132f40eb9eb2e75ff72435ea5d23c539a197e03fd5f3265ba4c",
          "sha1": "a387555930fd6a8431eee41e8882b7ca226f8983",
          "md5": "184e390219e8e13e507506d2eb070f89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.13-sources.jar",
          "url": "path_provider_android_release-0.0.13-sources.jar",
          "size": 4689,
          "sha512": "393ff86455165de18b7a102452a6f1434cafbdaa5bb2e9191230d753addd814c5ba33a3662dac95f8c8e2851a155014a2cebf9978bd075c569002b8852fe0b67",
          "sha256": "47c585346554942b1a793181486d70b5ff14b69ff1aa332ba1fc8e01af0a6464",
          "sha1": "7eb6c06469537e38fe2699f24f9d3ec0a20080f4",
          "md5": "dfb79a1435833d291d93d6d7c818c936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.13-javadoc.jar",
          "url": "path_provider_android_release-0.0.13-javadoc.jar",
          "size": 294102,
          "sha512": "6d4ed9c1f382ba2df0789cd9c5e86c46424221347806f8b81dad149ac442e44cd3d5a7d9498a03f6b82fe20d15d0f22430862419f791560ebd6ab9aa16e90684",
          "sha256": "e583c06c06ff1f963b06baecd7d66656c336fa7a8059caeae976ee7f67cb84a9",
          "sha1": "fcf0edf3b2e92882855621c511fb54afac679e73",
          "md5": "0773c1620b3911213fa8ab79d4152249"
        }
      ]
    }
  ]
}
