{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sleep_stage_algorithm",
    "module": "creek_sleep_stage_algorithm_release",
    "version": "0.0.58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.58.aar",
          "url": "creek_sleep_stage_algorithm_release-0.0.58.aar",
          "size": 20583,
          "sha512": "4b7802b2da8c31e7916dd651dfa3c75fe6c6d141604466ec4febe1b4ce9d7094693b9eff043c09607ddd2d18c71202e3f5655f480ccaab4fb7c1340be8c72913",
          "sha256": "36cf50e3005734cda35ebc9842455b7bc6cca133aa5ef9e95d293bb5855dd210",
          "sha1": "cb32dfcb61f4253624834c932d5b143247409159",
          "md5": "d1a38bda42cc637bf97f775c311a4b84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.58.aar",
          "url": "creek_sleep_stage_algorithm_release-0.0.58.aar",
          "size": 20583,
          "sha512": "4b7802b2da8c31e7916dd651dfa3c75fe6c6d141604466ec4febe1b4ce9d7094693b9eff043c09607ddd2d18c71202e3f5655f480ccaab4fb7c1340be8c72913",
          "sha256": "36cf50e3005734cda35ebc9842455b7bc6cca133aa5ef9e95d293bb5855dd210",
          "sha1": "cb32dfcb61f4253624834c932d5b143247409159",
          "md5": "d1a38bda42cc637bf97f775c311a4b84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.58-sources.jar",
          "url": "creek_sleep_stage_algorithm_release-0.0.58-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.58-javadoc.jar",
          "url": "creek_sleep_stage_algorithm_release-0.0.58-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
