{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sdk",
    "module": "flutter_release",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_index_convert",
          "module": "creek_index_convert_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_voice_assistant",
          "module": "creek_voice_assistant_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.whelksoft.flutter_native_timezone",
          "module": "flutter_native_timezone_updated_gradle_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.flutter_silero_vad",
          "module": "flutter_silero_vad_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.opusBridge.opus_bridge",
          "module": "opus_bridge_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.xfyun_speech",
          "module": "xfyun_speech_release",
          "version": {
            "requires": "0.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.2.aar",
          "url": "flutter_release-0.0.2.aar",
          "size": 15268037,
          "sha512": "0812abeaede30d6dc34fd7066c43e8d393f2a83ff0309d97d1dc20752d6a625954532b9477f8cfef5ca539552bff7370f55066ddfe331db4d407e5326cceb03f",
          "sha256": "ddb60a3404340fbfdc1b7d729bc907ea882f1589497f0355748f4dfaf54ad8e8",
          "sha1": "fb7906564c965e316cb82b28fefb19556211c468",
          "md5": "21ceb5ea9de5088086d78b933ca7cc86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_index_convert",
          "module": "creek_index_convert_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.creek_voice_assistant",
          "module": "creek_voice_assistant_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.whelksoft.flutter_native_timezone",
          "module": "flutter_native_timezone_updated_gradle_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.flutter_silero_vad",
          "module": "flutter_silero_vad_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.opusBridge.opus_bridge",
          "module": "opus_bridge_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.example.xfyun_speech",
          "module": "xfyun_speech_release",
          "version": {
            "requires": "0.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.2.aar",
          "url": "flutter_release-0.0.2.aar",
          "size": 15268037,
          "sha512": "0812abeaede30d6dc34fd7066c43e8d393f2a83ff0309d97d1dc20752d6a625954532b9477f8cfef5ca539552bff7370f55066ddfe331db4d407e5326cceb03f",
          "sha256": "ddb60a3404340fbfdc1b7d729bc907ea882f1589497f0355748f4dfaf54ad8e8",
          "sha1": "fb7906564c965e316cb82b28fefb19556211c468",
          "md5": "21ceb5ea9de5088086d78b933ca7cc86"
        }
      ]
    }
  ]
}
