{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-3.2.aar",
          "url": "creek_blue_manage_release-3.2.aar",
          "size": 4743,
          "sha512": "80531b3ba8be89d3c82cd3c5d8a363f90416c255691cd4f6627bdff3fe7aa22ef0e67ecd36af74c715bcfcda9e21ffa356ee5425a4bfb4a39abfbbc29f0fe4f6",
          "sha256": "b95b2c72bf5f427c735e6c0d8dc1ad831e18ad997d55cdc03b5c878b3c2a0444",
          "sha1": "d4b6e48e317829bba3ccd9f06d53e15f434c7fa4",
          "md5": "6cc9dad8c36785c15ba26edd504159f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "3.2"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "3.2"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "3.2"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "3.2"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-3.2.aar",
          "url": "creek_blue_manage_release-3.2.aar",
          "size": 4743,
          "sha512": "80531b3ba8be89d3c82cd3c5d8a363f90416c255691cd4f6627bdff3fe7aa22ef0e67ecd36af74c715bcfcda9e21ffa356ee5425a4bfb4a39abfbbc29f0fe4f6",
          "sha256": "b95b2c72bf5f427c735e6c0d8dc1ad831e18ad997d55cdc03b5c878b3c2a0444",
          "sha1": "d4b6e48e317829bba3ccd9f06d53e15f434c7fa4",
          "md5": "6cc9dad8c36785c15ba26edd504159f8"
        }
      ]
    }
  ]
}
