{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-6.5.aar",
          "url": "azure_speech_release-6.5.aar",
          "size": 10893,
          "sha512": "49c394dcda794d717949f859cb0231adefe351328c79a2bef44f8bb4044731b1f13d844fc6607b0e5f3b30759e20beb6c553b05f2d07e17dc98ad6a089775c84",
          "sha256": "1c599faa2a23441661734c7894c8bfa1fd61499dbb571aa0e4360c7a0bb1ff28",
          "sha1": "3ccef1f13a3ab9fe04b925a4e43aa5c52e83c102",
          "md5": "2781c7d215fd4f7dae181f5658cab4a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-6.5.aar",
          "url": "azure_speech_release-6.5.aar",
          "size": 10893,
          "sha512": "49c394dcda794d717949f859cb0231adefe351328c79a2bef44f8bb4044731b1f13d844fc6607b0e5f3b30759e20beb6c553b05f2d07e17dc98ad6a089775c84",
          "sha256": "1c599faa2a23441661734c7894c8bfa1fd61499dbb571aa0e4360c7a0bb1ff28",
          "sha1": "3ccef1f13a3ab9fe04b925a4e43aa5c52e83c102",
          "md5": "2781c7d215fd4f7dae181f5658cab4a0"
        }
      ]
    }
  ]
}
