{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.lz4",
    "module": "lz4_release",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-0.0.2.aar",
          "url": "lz4_release-0.0.2.aar",
          "size": 142692,
          "sha512": "dd49991cd0413e1fbda43f011e70242e0118e53c10f0b8f4e28df58ab598fdbad1d1e9e5d8af56bbb430c64219838b4aa0db76927f00de1e6198e84f20178918",
          "sha256": "0b5c5f4acbda04ea0fa9c879cbf7e865e62b7132c6c370134dfd503496f7e36d",
          "sha1": "d811c7f62b4991cd49eb628c80d661103b1604aa",
          "md5": "6df0ccd5626f8319d661af93d0102d7c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-0.0.2.aar",
          "url": "lz4_release-0.0.2.aar",
          "size": 142692,
          "sha512": "dd49991cd0413e1fbda43f011e70242e0118e53c10f0b8f4e28df58ab598fdbad1d1e9e5d8af56bbb430c64219838b4aa0db76927f00de1e6198e84f20178918",
          "sha256": "0b5c5f4acbda04ea0fa9c879cbf7e865e62b7132c6c370134dfd503496f7e36d",
          "sha1": "d811c7f62b4991cd49eb628c80d661103b1604aa",
          "md5": "6df0ccd5626f8319d661af93d0102d7c"
        }
      ]
    }
  ]
}
