{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_debug-1.0.aar",
          "url": "creek_blue_manage_debug-1.0.aar",
          "size": 4828,
          "sha512": "021ceaedacb5d1795529033220db747287d699874bdf6989f19f22dc68e048d0ceb68fc5340e2eb90d6e3ebed964f63b1bad872e2ea14ce4faacd08167867435",
          "sha256": "4b7db856c54d492612a58647c43ce5d428cc5d7f995f02f319fba37494f65283",
          "sha1": "0ab1bb97bec6e01e8bfdb1a79e431b5cd589a7ae",
          "md5": "c6fb0bdf5b77fe96d0065a4163ad3333"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_debug-1.0.aar",
          "url": "creek_blue_manage_debug-1.0.aar",
          "size": 4828,
          "sha512": "021ceaedacb5d1795529033220db747287d699874bdf6989f19f22dc68e048d0ceb68fc5340e2eb90d6e3ebed964f63b1bad872e2ea14ce4faacd08167867435",
          "sha256": "4b7db856c54d492612a58647c43ce5d428cc5d7f995f02f319fba37494f65283",
          "sha1": "0ab1bb97bec6e01e8bfdb1a79e431b5cd589a7ae",
          "md5": "c6fb0bdf5b77fe96d0065a4163ad3333"
        }
      ]
    }
  ]
}
