{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "10.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-10.6.aar",
          "url": "device_calendar_release-10.6.aar",
          "size": 70884,
          "sha512": "30ebf229e7ad5c17ece2500796326c6b34966d315b060b8c9272b468fb2991ce07bf260abb4a33355ed9739d2f402337702e45a92fafed3b3aca8ed8321eb2e6",
          "sha256": "65268f26271e985a6881120c03dfdf45eed3bb764e6a7e97151d61312bd44c85",
          "sha1": "bb201f4393a5db2a0ac2afe63b54e9b60687262a",
          "md5": "18d2309f74a8e6e2286c48333b6199e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-10.6.aar",
          "url": "device_calendar_release-10.6.aar",
          "size": 70884,
          "sha512": "30ebf229e7ad5c17ece2500796326c6b34966d315b060b8c9272b468fb2991ce07bf260abb4a33355ed9739d2f402337702e45a92fafed3b3aca8ed8321eb2e6",
          "sha256": "65268f26271e985a6881120c03dfdf45eed3bb764e6a7e97151d61312bd44c85",
          "sha1": "bb201f4393a5db2a0ac2afe63b54e9b60687262a",
          "md5": "18d2309f74a8e6e2286c48333b6199e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-10.6-sources.jar",
          "url": "device_calendar_release-10.6-sources.jar",
          "size": 19259,
          "sha512": "596df879875dbeecd1171483bba32882cbf94115c8c1448185b993e296994006c7652e4315a994630107b6812bdd5cd1a1562c866d3c0dce284107f4409c2ab6",
          "sha256": "b873a00db27dcf44fb83ed111ce903da44f6dbdf95b5c0ba1c98f0ec56eca9e3",
          "sha1": "6f9e51b7f1534e2d360107cf836efc201ff41c23",
          "md5": "9c871bf2f63334dba398899b5e5ab6e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-10.6-javadoc.jar",
          "url": "device_calendar_release-10.6-javadoc.jar",
          "size": 369718,
          "sha512": "8b8500e73c568648ec2560154672d6026241865fd5b06ed1a3672ad7563fb4b43f2fef4ac9180a627217ecef2167f4bd8de4643c05ee35b0a3d46c5f1e4d25c1",
          "sha256": "f2682f0d799ab514fecfaaa7606cdc3bb2989f8241467363bd0ad3c3b660ca75",
          "sha1": "81f40bdf082384e6fda81609a4a7994e5e120778",
          "md5": "62626c82d2260fa65c0e7217b7c9dc16"
        }
      ]
    }
  ]
}
