{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-10.2.aar",
          "url": "sqflite_release-10.2.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-10.2.aar",
          "url": "sqflite_release-10.2.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-10.2-sources.jar",
          "url": "sqflite_release-10.2-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-10.2-javadoc.jar",
          "url": "sqflite_release-10.2-javadoc.jar",
          "size": 341639,
          "sha512": "0d892c4210f5f562c8414b9b6003ef06d6a8789efcaba3340d91774dbf3108122aa2040c9cb3cc39676b81c040881ec93f09ca03de91a815b3c91d6acf82ad4b",
          "sha256": "72503ab74b68bb89e0a9bb46922aa22865c4685c1ca1e8749f305731e58a7106",
          "sha1": "4172af78bc9e4738ebc14f554aceff6e3d5a95ee",
          "md5": "145524783b9c13c304598e4363a8e911"
        }
      ]
    }
  ]
}
