{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.45.aar",
          "url": "sqflite_android_release-0.0.45.aar",
          "size": 43114,
          "sha512": "d503f9bfda65979de31a2fae5f8f09ba4c0dffc2e4b103bafed743ad856f6fe846942769cfdfd1a6b7b002a547ad66254c23079af4e8761a3644c8c1db9ae130",
          "sha256": "9853dd219a077ace534dd5baca1a95ba8c4472db8a138054784c5625cd97dfe0",
          "sha1": "dc898fa37aef3652ebae2d18055ae54079786cdc",
          "md5": "abc510276235f235e95d5194735e8ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.45.aar",
          "url": "sqflite_android_release-0.0.45.aar",
          "size": 43114,
          "sha512": "d503f9bfda65979de31a2fae5f8f09ba4c0dffc2e4b103bafed743ad856f6fe846942769cfdfd1a6b7b002a547ad66254c23079af4e8761a3644c8c1db9ae130",
          "sha256": "9853dd219a077ace534dd5baca1a95ba8c4472db8a138054784c5625cd97dfe0",
          "sha1": "dc898fa37aef3652ebae2d18055ae54079786cdc",
          "md5": "abc510276235f235e95d5194735e8ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.45-sources.jar",
          "url": "sqflite_android_release-0.0.45-sources.jar",
          "size": 23748,
          "sha512": "79a18e8544303c175a5518d48dc0d23a617f6da7f5ddf699a7e94e154c1a221a1182d6b22363d34103e63d7e17decb835bdc2e3e92bfe0d08b1be7349ecc3847",
          "sha256": "7c4ef41dcd75693d0abddc88b3ba5c2fd30c31ee71155462d81055d982095868",
          "sha1": "8b554a039e5de13b3998bf9f2a1ef11cda40c2f1",
          "md5": "54e2ffa57d01fe69ac670dda7fb4b5f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.45-javadoc.jar",
          "url": "sqflite_android_release-0.0.45-javadoc.jar",
          "size": 339908,
          "sha512": "e0edaf86b6f425414c87f0d35d3030abccde3c511ca093b7a30d82a8a360e368f24e5acd5e23ae4aa55ae0380cee3c97f19dcf26a139b6c3b0397b23c28e6e9a",
          "sha256": "a592f0c21637407011b025279a04d93b085eaf21f46e94d0721b39bd0a03b2e2",
          "sha1": "aa2345f5c045f9985e05c947b0a54fcbfbb36b5b",
          "md5": "30c558f428de2d1acff8f33a37d8f86b"
        }
      ]
    }
  ]
}
