{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.21.aar",
          "url": "device_calendar_release-0.0.21.aar",
          "size": 70890,
          "sha512": "6cb10d4fa7e2824ec9359990703b30673678f2c3b83f28fa586bfe559c7befd8d149f8cf57bb24591eaada6af1a4f111a23198d1a398101efd617e0bc983193c",
          "sha256": "bd6a23db6433cb0f530e8787d24256f1ed0555e6003adf3d419ffa3486402185",
          "sha1": "d162b1634f3d564b7ba6916a2b3cbed26760a933",
          "md5": "f246815d7eff0fd9d2d88424f525c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.21.aar",
          "url": "device_calendar_release-0.0.21.aar",
          "size": 70890,
          "sha512": "6cb10d4fa7e2824ec9359990703b30673678f2c3b83f28fa586bfe559c7befd8d149f8cf57bb24591eaada6af1a4f111a23198d1a398101efd617e0bc983193c",
          "sha256": "bd6a23db6433cb0f530e8787d24256f1ed0555e6003adf3d419ffa3486402185",
          "sha1": "d162b1634f3d564b7ba6916a2b3cbed26760a933",
          "md5": "f246815d7eff0fd9d2d88424f525c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-0.0.21-sources.jar",
          "url": "device_calendar_release-0.0.21-sources.jar",
          "size": 19259,
          "sha512": "596df879875dbeecd1171483bba32882cbf94115c8c1448185b993e296994006c7652e4315a994630107b6812bdd5cd1a1562c866d3c0dce284107f4409c2ab6",
          "sha256": "b873a00db27dcf44fb83ed111ce903da44f6dbdf95b5c0ba1c98f0ec56eca9e3",
          "sha1": "6f9e51b7f1534e2d360107cf836efc201ff41c23",
          "md5": "9c871bf2f63334dba398899b5e5ab6e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-0.0.21-javadoc.jar",
          "url": "device_calendar_release-0.0.21-javadoc.jar",
          "size": 369749,
          "sha512": "6eef3a32dbf7cbc9e08172da4dfb21745f10854bd2a84575a9ee6f839212aa8e544fac5017c11924e78e33d3793d2d235e59f4e1c113752383189a0aabc42f94",
          "sha256": "5ad118d59fa02f6934b377b5404fd9311de1b811a9be3b0119006b193c1202ff",
          "sha1": "3685d38c6d3abbb617661719f09198974eb7d6de",
          "md5": "ee4fa2260ad3ae207274ee305daa6e53"
        }
      ]
    }
  ]
}
