{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni",
    "module": "jni_release",
    "version": "10.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-10.7.aar",
          "url": "jni_release-10.7.aar",
          "size": 104430,
          "sha512": "6ea6e2327050466a79befb711bc10b4f365bcfaa0ccea8c0831de6534f7be1a23368f0b00b48f0d729218c7053039f37e2bc832dae7adcdfa04422f319c88191",
          "sha256": "f72b119a2a17b64786359b0a7708003f919743e3fc16a876beb4463a18326e8c",
          "sha1": "e69a1fd6d84a36be48c99a6edba58f251ae1c4aa",
          "md5": "c5b1691b2c53affc76cdce812961751f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-10.7.aar",
          "url": "jni_release-10.7.aar",
          "size": 104430,
          "sha512": "6ea6e2327050466a79befb711bc10b4f365bcfaa0ccea8c0831de6534f7be1a23368f0b00b48f0d729218c7053039f37e2bc832dae7adcdfa04422f319c88191",
          "sha256": "f72b119a2a17b64786359b0a7708003f919743e3fc16a876beb4463a18326e8c",
          "sha1": "e69a1fd6d84a36be48c99a6edba58f251ae1c4aa",
          "md5": "c5b1691b2c53affc76cdce812961751f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-10.7-sources.jar",
          "url": "jni_release-10.7-sources.jar",
          "size": 5459,
          "sha512": "61c8d0b11708383673e2d967abe5948df4f9f1c20f77852bfc8e4da61a83bb5c2e7561a02692dc183a64b4f842555d66ebd142d02b6295313fcda91f9e8e0c15",
          "sha256": "0762cdfe1e25701b53f0e55fde69135e74f25328f4b1c60e4778701833bfab6e",
          "sha1": "09a60f323f1b590e7921cd33327514fe4d916cb1",
          "md5": "3cf8aa129d418b4388b02cea9ff9819b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-10.7-javadoc.jar",
          "url": "jni_release-10.7-javadoc.jar",
          "size": 283168,
          "sha512": "0bf10152c859540fdf8e44069450a3c0544f1f5388a98d90c8d2be02395d245367d16dabc3a796a855e6c0fc945152b6e1886748d687f51484a8093f9441673f",
          "sha256": "a0f208834649cfea3352c3e32e60f712a64bfcaa868742168d02212f29c4cbc0",
          "sha1": "dd5fc327fcc8e3aeabdb409674a2fe0b354637e7",
          "md5": "01ae8d855c1ff9ab66051177bf1e8a14"
        }
      ]
    }
  ]
}
