{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "10.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.4.aar",
          "url": "azure_speech_release-10.4.aar",
          "size": 12704,
          "sha512": "f9ff524e5efefea3665b3f6b3e7cb8a9387661db3383d1fb659b57b09b97c0c2dabdee3d82dc2be72a4f005bef2de9c5c7031944ae4a9ddfcc8b1b4ae2f1c9b0",
          "sha256": "936e6ef87aed7ca54729b52aeb066a514578aff115345d809c22402fbddb10c8",
          "sha1": "97aa2e8d4ee08184b3b591e354e8741f59d92ecd",
          "md5": "eae9321999c5b58d72eab38a8004a94c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.4.aar",
          "url": "azure_speech_release-10.4.aar",
          "size": 12704,
          "sha512": "f9ff524e5efefea3665b3f6b3e7cb8a9387661db3383d1fb659b57b09b97c0c2dabdee3d82dc2be72a4f005bef2de9c5c7031944ae4a9ddfcc8b1b4ae2f1c9b0",
          "sha256": "936e6ef87aed7ca54729b52aeb066a514578aff115345d809c22402fbddb10c8",
          "sha1": "97aa2e8d4ee08184b3b591e354e8741f59d92ecd",
          "md5": "eae9321999c5b58d72eab38a8004a94c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.4-sources.jar",
          "url": "azure_speech_release-10.4-sources.jar",
          "size": 4716,
          "sha512": "d6737e296ebf8b9f610cdec4dae5a749683f680dec0589a9cdf14e595c5f4481b5592e14054e1a5ba40cae2aec4cb588125945944616cd63376d5739713025fe",
          "sha256": "a4ebcba754bea5ab4c8548460e1ee3b5148d978654bb4b8591c92e8e0abd9dbe",
          "sha1": "2cfafee64360f6b41ec994f0c8e247a674e6efad",
          "md5": "e0d7339802f8667f06b36eca5e27a2f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.4-javadoc.jar",
          "url": "azure_speech_release-10.4-javadoc.jar",
          "size": 262203,
          "sha512": "48d6563d460a9732b2396625f5d04a958b8dff3a5af91d3cb0dfa2d3e5596c3d37b9fb1362fa4465935550be10bb80c71e206cf5fd212f041536a41bda08cc25",
          "sha256": "ddca33c805fcda7cdb2fdfcc949472e3e83c6b69f88d0e9715408b2c2f76d9b6",
          "sha1": "292d7d3a4b147b916ac4a6c0ebcca474372b6951",
          "md5": "8039d9bcbc1b89b9d4771169ea3fd843"
        }
      ]
    }
  ]
}
