{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boskokg.flutter_blue_plus",
    "module": "flutter_blue_plus_release",
    "version": "0.0.62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.0.0-rc-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.62.aar",
          "url": "flutter_blue_plus_release-0.0.62.aar",
          "size": 215659,
          "sha512": "189409eef98d7c8df038a75859a126aac20f5928d00d2f9d58c2704eb74165c2610d6183cbe91982a00ac61d9aa0993d006b556dcf591549ebf785f79dd5feab",
          "sha256": "214a9effa3465e71dee601627e2bc2699ee39e7d641916bfe846e3e05185bf90",
          "sha1": "6a9568f1eecf8798c0ab925435b64afa2fd5b1f2",
          "md5": "1a6ccb93743215d694a693fca2fd6501"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.0.0-rc-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.62.aar",
          "url": "flutter_blue_plus_release-0.0.62.aar",
          "size": 215659,
          "sha512": "189409eef98d7c8df038a75859a126aac20f5928d00d2f9d58c2704eb74165c2610d6183cbe91982a00ac61d9aa0993d006b556dcf591549ebf785f79dd5feab",
          "sha256": "214a9effa3465e71dee601627e2bc2699ee39e7d641916bfe846e3e05185bf90",
          "sha1": "6a9568f1eecf8798c0ab925435b64afa2fd5b1f2",
          "md5": "1a6ccb93743215d694a693fca2fd6501"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.62-sources.jar",
          "url": "flutter_blue_plus_release-0.0.62-sources.jar",
          "size": 54113,
          "sha512": "046ec6894b606af1b69c323f047da2c3b0dd6617f34b3883cd7533553c7bcc38ac4ed912ffa199d0e2f7e6a69ded09d792e9b8176fb1bed260bf11896746ed44",
          "sha256": "b8d711d308639ddc7cf308d4d65242584d4a62752229c3b639421aec6b674f94",
          "sha1": "167c6f35b02319d95337182369c42f608e78b8fd",
          "md5": "65294066a43965565632b62ffad4a883"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.62-javadoc.jar",
          "url": "flutter_blue_plus_release-0.0.62-javadoc.jar",
          "size": 726124,
          "sha512": "215c172ee89cc931cff2240a104fbd3ad180a3002387a6cc63b6401713bf153c4654a315ff095fc44535a15fefa7fe81097174fe45120c573ee0370fea5e11e2",
          "sha256": "5eb70bc3f68c794a5c7791b233e48f5bfff3dc61b791ace3fcf7f9908e8c5983",
          "sha1": "2fc89d2800fdeef9c15e906cc866ba4dd4ca5bb0",
          "md5": "7b9601a7277751accd526fec8e827699"
        }
      ]
    }
  ]
}
