{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "10.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.6.aar",
          "url": "shared_preferences_android_release-10.6.aar",
          "size": 89515,
          "sha512": "e11ce0dfd08bbde09d99683a7ae78b350cf367bc59f7eb288e5567bae59479656fb10599bf030c720693e2562b9f460b02d00e883b2aa05d3990b810eb8a72c6",
          "sha256": "78dd26c83afc0cac4fb98fe39cff259a592ea7ffb5dda0bfc7cabdf7688fd7d9",
          "sha1": "226fa4d44fa8b10d7a6dcb60da0815349e4bdcb1",
          "md5": "303c4f4df62d65e4deeff6c30efb91d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.6.aar",
          "url": "shared_preferences_android_release-10.6.aar",
          "size": 89515,
          "sha512": "e11ce0dfd08bbde09d99683a7ae78b350cf367bc59f7eb288e5567bae59479656fb10599bf030c720693e2562b9f460b02d00e883b2aa05d3990b810eb8a72c6",
          "sha256": "78dd26c83afc0cac4fb98fe39cff259a592ea7ffb5dda0bfc7cabdf7688fd7d9",
          "sha1": "226fa4d44fa8b10d7a6dcb60da0815349e4bdcb1",
          "md5": "303c4f4df62d65e4deeff6c30efb91d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.6-sources.jar",
          "url": "shared_preferences_android_release-10.6-sources.jar",
          "size": 10391,
          "sha512": "c868c1a7019fbb013fc8f7393122f858679c552ee0b0521b78fd01d85a7e22b805f61c1c78db0c81d3d68ca28cb891a1450cbc3be4566fb39ffbc055a7bc22a1",
          "sha256": "4b7a533aea864be65713bbe35408e2eeaaf886febc2e0ff80f6d86c800f0eae9",
          "sha1": "e8a73be85d3672522581e4d702ba7289cd7a69ef",
          "md5": "e196aac4401e72d313a388902984ab00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.6-javadoc.jar",
          "url": "shared_preferences_android_release-10.6-javadoc.jar",
          "size": 326420,
          "sha512": "b9d8be50cb59069fc5220145c4e7b49f8132135c708a47647cc2d7b776f5aab5aa5e2806a744118e2e31af55c87f30de3fc376f8f47fee0983ffd4498564eaec",
          "sha256": "c0efa429a73c85a0ce99aaede6ded2d6c1fc8eb750684166235a74a7f5921f52",
          "sha1": "489794f76f59737c4c3eb18a6bea2c6125ef632f",
          "md5": "649809239cca284e6e01ebace1d6be41"
        }
      ]
    }
  ]
}
