{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_release",
    "version": "10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-10.2.aar",
          "url": "connectivity_plus_release-10.2.aar",
          "size": 7788,
          "sha512": "5a160d7ab2df1847c4c821446710972b08987d01cb6caa29fe51c9181b0f94f28e487e6a33e9a70300e8fdab2fa8c329c59133482e2935f9a33bbd4c09741fca",
          "sha256": "32ffce9236ccc0e46f30e736e569e776bc1366c392c96a4047fe87825aa0bb4f",
          "sha1": "87c7f3122bfdc25b7e95e0a058891ae17b835596",
          "md5": "25e87348885eb87f1ae0fe8c0df2dea0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-10.2.aar",
          "url": "connectivity_plus_release-10.2.aar",
          "size": 7788,
          "sha512": "5a160d7ab2df1847c4c821446710972b08987d01cb6caa29fe51c9181b0f94f28e487e6a33e9a70300e8fdab2fa8c329c59133482e2935f9a33bbd4c09741fca",
          "sha256": "32ffce9236ccc0e46f30e736e569e776bc1366c392c96a4047fe87825aa0bb4f",
          "sha1": "87c7f3122bfdc25b7e95e0a058891ae17b835596",
          "md5": "25e87348885eb87f1ae0fe8c0df2dea0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connectivity_plus_release-10.2-sources.jar",
          "url": "connectivity_plus_release-10.2-sources.jar",
          "size": 5518,
          "sha512": "0c41bf323fcef58553dc1fd1dbf68460941f37d163544470982a5c9a25586a0677af1f9977c2017b4b0b11918912fd73eb499909c3d9ca3ab881ad7f3552c62d",
          "sha256": "a82777fa9f9906c001a146aacca44b44a7f5c7bb1388bb186a3ae6fbae462854",
          "sha1": "eebf9a42929aba7211c003f59863ed40d6d0aa85",
          "md5": "7a487ef9385c43cac7bf7ad669fe8b11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connectivity_plus_release-10.2-javadoc.jar",
          "url": "connectivity_plus_release-10.2-javadoc.jar",
          "size": 278354,
          "sha512": "dca74ed56d3adb16c5019d26bceb4f108d764c54ac90aba9f0d7e4e63dfc997993ad8adb697b303f535f821e160c08f34855e6623d6956624c91be72276ddc22",
          "sha256": "f1623a60006c0a5d7a1097b81aa9f2bfb66a92e10b8ce16b84f6ed6e32b0d66c",
          "sha1": "f1a681df6973be5e71947f11934a417c330152f2",
          "md5": "cd72f09a2fb8dc1b59b4a51f29ac42c9"
        }
      ]
    }
  ]
}
