{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_release",
    "version": "10.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-10.4.aar",
          "url": "connectivity_plus_release-10.4.aar",
          "size": 7788,
          "sha512": "5a160d7ab2df1847c4c821446710972b08987d01cb6caa29fe51c9181b0f94f28e487e6a33e9a70300e8fdab2fa8c329c59133482e2935f9a33bbd4c09741fca",
          "sha256": "32ffce9236ccc0e46f30e736e569e776bc1366c392c96a4047fe87825aa0bb4f",
          "sha1": "87c7f3122bfdc25b7e95e0a058891ae17b835596",
          "md5": "25e87348885eb87f1ae0fe8c0df2dea0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-10.4.aar",
          "url": "connectivity_plus_release-10.4.aar",
          "size": 7788,
          "sha512": "5a160d7ab2df1847c4c821446710972b08987d01cb6caa29fe51c9181b0f94f28e487e6a33e9a70300e8fdab2fa8c329c59133482e2935f9a33bbd4c09741fca",
          "sha256": "32ffce9236ccc0e46f30e736e569e776bc1366c392c96a4047fe87825aa0bb4f",
          "sha1": "87c7f3122bfdc25b7e95e0a058891ae17b835596",
          "md5": "25e87348885eb87f1ae0fe8c0df2dea0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connectivity_plus_release-10.4-sources.jar",
          "url": "connectivity_plus_release-10.4-sources.jar",
          "size": 5518,
          "sha512": "0c41bf323fcef58553dc1fd1dbf68460941f37d163544470982a5c9a25586a0677af1f9977c2017b4b0b11918912fd73eb499909c3d9ca3ab881ad7f3552c62d",
          "sha256": "a82777fa9f9906c001a146aacca44b44a7f5c7bb1388bb186a3ae6fbae462854",
          "sha1": "eebf9a42929aba7211c003f59863ed40d6d0aa85",
          "md5": "7a487ef9385c43cac7bf7ad669fe8b11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connectivity_plus_release-10.4-javadoc.jar",
          "url": "connectivity_plus_release-10.4-javadoc.jar",
          "size": 278356,
          "sha512": "2c0d582826588a8f5759d391e1ff5767fbe6e217d318c1fcc4317467f8c6d1b69fa9199785e32579569897b1e4c6fbe3f2d42bab0a447a3a85dbeb1c90b63882",
          "sha256": "2f4b63fc5a81f6fc88a6910752c46bd5072f2b2f5cf36d31a673685e4c220eb8",
          "sha1": "1cff0460632f0949f8d41bf8f8feb0139254152c",
          "md5": "6bb9129a832a66d3d65ba5c40c670ad1"
        }
      ]
    }
  ]
}
