{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.xfyun_speech",
    "module": "xfyun_speech_release",
    "version": "6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "xfyun_speech_release-6.9.aar",
          "url": "xfyun_speech_release-6.9.aar",
          "size": 492474,
          "sha512": "3390056be771fc66914dca0139a2b309dd2f3d322447502a1743ce29d1023798c3feca7db745677f8d860368d1a552e334b06937a11377f5cf8c9f393cbd5353",
          "sha256": "2c71ddbfad8ab5fbef78781bd81c379c52cb45eef9982dbbc12b177db074bc2c",
          "sha1": "a250560dc3ae06a615263a137b071f7d15076509",
          "md5": "76ed9d466beb7671755da75764e46c97"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "xfyun_speech_release-6.9.aar",
          "url": "xfyun_speech_release-6.9.aar",
          "size": 492474,
          "sha512": "3390056be771fc66914dca0139a2b309dd2f3d322447502a1743ce29d1023798c3feca7db745677f8d860368d1a552e334b06937a11377f5cf8c9f393cbd5353",
          "sha256": "2c71ddbfad8ab5fbef78781bd81c379c52cb45eef9982dbbc12b177db074bc2c",
          "sha1": "a250560dc3ae06a615263a137b071f7d15076509",
          "md5": "76ed9d466beb7671755da75764e46c97"
        }
      ]
    }
  ]
}
