{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "10.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-10.6.aar",
          "url": "sqflite_release-10.6.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-10.6.aar",
          "url": "sqflite_release-10.6.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-10.6-sources.jar",
          "url": "sqflite_release-10.6-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-10.6-javadoc.jar",
          "url": "sqflite_release-10.6-javadoc.jar",
          "size": 341649,
          "sha512": "fcd9bef7b1d978b8460e767aef5df4c5c4bf749749af05bc075cce9e5915f9871df933252d13523e0687d38b923f94695c0cf5a2977b39e776b9801583836bea",
          "sha256": "73b6832c83fe0dbf6e706af6c8fe04868c402fa69d759e3c362b87db8525d300",
          "sha1": "7faf7287760be48ca24702db3533046a33d558d1",
          "md5": "83fac6e5ef454fea61f8cad0c662e080"
        }
      ]
    }
  ]
}
