{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "10.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.9.aar",
          "url": "shared_preferences_android_release-10.9.aar",
          "size": 116504,
          "sha512": "2714c2ba11035397bdd5b0b55e29071bf2e646415abc1928da3f37f0f41c539c69edd5ae9a2ffa254282c055c3aa08a2210562bc537a55cf251543c6f245c977",
          "sha256": "e02c421039cdc1493a82fd55c9c12c5a776308310135d8ceae9ae59785a00106",
          "sha1": "56c7aa23bd608467e7eb80c05ca57e4e957fed84",
          "md5": "8eda1dff559e6ef33b60989623602aa5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.9.aar",
          "url": "shared_preferences_android_release-10.9.aar",
          "size": 116504,
          "sha512": "2714c2ba11035397bdd5b0b55e29071bf2e646415abc1928da3f37f0f41c539c69edd5ae9a2ffa254282c055c3aa08a2210562bc537a55cf251543c6f245c977",
          "sha256": "e02c421039cdc1493a82fd55c9c12c5a776308310135d8ceae9ae59785a00106",
          "sha1": "56c7aa23bd608467e7eb80c05ca57e4e957fed84",
          "md5": "8eda1dff559e6ef33b60989623602aa5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.9-sources.jar",
          "url": "shared_preferences_android_release-10.9-sources.jar",
          "size": 13890,
          "sha512": "dbe72bd5718d4d0b71dc4801c6e52be1b3159dc2d58ee3830698f3a933c794c4ee275db1a93824724ae9e8f0c90e304042feb09e35e8ca520fcf12a0a90427c6",
          "sha256": "678d6f3c56fac616e12cc2dcc77bdec69eebe4be21f2687de96ef3acdd710a84",
          "sha1": "8c4139cb7a538c606058ff2f988fb86e0745b25c",
          "md5": "6ca34416bf0d14e339f9e9cb9bd3251a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.9-javadoc.jar",
          "url": "shared_preferences_android_release-10.9-javadoc.jar",
          "size": 357930,
          "sha512": "c9d146e09f3f255945aa20f576e8b47cc4099a43ee74d39acfc450f374e58b92ba104c27e80618683f78422746bb1a0aefc1ce639682fb91106792ee9a96dc70",
          "sha256": "befd00cea4f87cbcbfaa919c57ce6bb084a27f1c33901cc4d6a8fd5b5becade1",
          "sha1": "aeaa15264b8efa9d8e6643c2e122391ddacf6925",
          "md5": "caab1fc45b5ff3e4701582a4f15d8bab"
        }
      ]
    }
  ]
}
