{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-5.0.aar",
          "url": "creek_blue_manage_release-5.0.aar",
          "size": 18992,
          "sha512": "c485784e24ffa5f0cf79912a8c6cc7750d6bcb528c889c5b2fa5ed5ba3a022fc0e9a40a57b3e05b6d74d229d8114e046f7e8d24bbea29d749b1c9c595a7ee31c",
          "sha256": "7687b1b511a2a364ee17388089b4cb5db1a343e503ab6cf43f9dc1b4d7a5e9a0",
          "sha1": "af30dbef1338daedc965f9eabd2930a877a22a9b",
          "md5": "221d0640277f96dcc19145afea35a48e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "5.0"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "5.0"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "5.0"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "5.0"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "5.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-5.0.aar",
          "url": "creek_blue_manage_release-5.0.aar",
          "size": 18992,
          "sha512": "c485784e24ffa5f0cf79912a8c6cc7750d6bcb528c889c5b2fa5ed5ba3a022fc0e9a40a57b3e05b6d74d229d8114e046f7e8d24bbea29d749b1c9c595a7ee31c",
          "sha256": "7687b1b511a2a364ee17388089b4cb5db1a343e503ab6cf43f9dc1b4d7a5e9a0",
          "sha1": "af30dbef1338daedc965f9eabd2930a877a22a9b",
          "md5": "221d0640277f96dcc19145afea35a48e"
        }
      ]
    }
  ]
}
