{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sdk",
    "module": "flutter_release",
    "version": "9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.actions.actres",
          "module": "actres_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_index_convert",
          "module": "creek_index_convert_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_voice_assistant",
          "module": "creek_voice_assistant_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.whelksoft.flutter_native_timezone",
          "module": "flutter_native_timezone_updated_gradle_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.opusBridge.opus_bridge",
          "module": "opus_bridge_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-9.1.aar",
          "url": "flutter_release-9.1.aar",
          "size": 17228799,
          "sha512": "a460ceffb83b7ef29c61951ef2efb95e60978b2e1a4e3e7e170d0b8f7a5955f8a639b6d4845e207c3f4f00e5599af8b71ef3a79527a46e5582a07e8cae3af061",
          "sha256": "cf997d3a34885fe68e94234906a5e82709069c4fba9ba494c797555ac4a61b95",
          "sha1": "6cbb14aa0f1c8165ada4ea52d5c7574931e9e4c0",
          "md5": "e39b7b15085b54dafbce0a47555423ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.actions.actres",
          "module": "actres_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_index_convert",
          "module": "creek_index_convert_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.creek_voice_assistant",
          "module": "creek_voice_assistant_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.whelksoft.flutter_native_timezone",
          "module": "flutter_native_timezone_updated_gradle_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.opusBridge.opus_bridge",
          "module": "opus_bridge_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-9.1.aar",
          "url": "flutter_release-9.1.aar",
          "size": 17228799,
          "sha512": "a460ceffb83b7ef29c61951ef2efb95e60978b2e1a4e3e7e170d0b8f7a5955f8a639b6d4845e207c3f4f00e5599af8b71ef3a79527a46e5582a07e8cae3af061",
          "sha256": "cf997d3a34885fe68e94234906a5e82709069c4fba9ba494c797555ac4a61b95",
          "sha1": "6cbb14aa0f1c8165ada4ea52d5c7574931e9e4c0",
          "md5": "e39b7b15085b54dafbce0a47555423ea"
        }
      ]
    }
  ]
}
