{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.1.aar",
          "url": "azure_speech_release-0.0.1.aar",
          "size": 305957,
          "sha512": "dc750f312ac0cd404b3a69ba43cd7e1188d10ecf22662c1ea4da59c8ceafaeac84ec95b7d5829d7669ea915d5bc80c247d7ef9d96d0c9571b08c3848c7d5a27a",
          "sha256": "cd538c4c69b7bbc38bb6281cfda055954bb891ba101183ad12d5a6f567fa7248",
          "sha1": "0a488011c11ba003036104ee8fc932b4a09c3f1e",
          "md5": "ca399d4ac5aa309eff5dc9f308011768"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.44.0"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            },
            {
              "group": "com.azure",
              "module": "azure-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.1.aar",
          "url": "azure_speech_release-0.0.1.aar",
          "size": 305957,
          "sha512": "dc750f312ac0cd404b3a69ba43cd7e1188d10ecf22662c1ea4da59c8ceafaeac84ec95b7d5829d7669ea915d5bc80c247d7ef9d96d0c9571b08c3848c7d5a27a",
          "sha256": "cd538c4c69b7bbc38bb6281cfda055954bb891ba101183ad12d5a6f567fa7248",
          "sha1": "0a488011c11ba003036104ee8fc932b4a09c3f1e",
          "md5": "ca399d4ac5aa309eff5dc9f308011768"
        }
      ]
    }
  ]
}
