{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.57.aar",
          "url": "sqflite_android_release-0.0.57.aar",
          "size": 43116,
          "sha512": "42f26c98eed954ceaa8a2bf53d82471694ad905c3be7f1b5edd2c354a8645ad26eb33b71f3d38a010887d72c2a992f1f11921b34d0c14223bc8c9ceb6811d24e",
          "sha256": "9d1876f99d1ebba5bc32e817c3133438457e2e10036559e95028f159deb50f29",
          "sha1": "aecfa2d6a2f80c996e0cb2cc77d0a7ccabd935fa",
          "md5": "4903f16cc805ab3695c74ca727c10b7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.57.aar",
          "url": "sqflite_android_release-0.0.57.aar",
          "size": 43116,
          "sha512": "42f26c98eed954ceaa8a2bf53d82471694ad905c3be7f1b5edd2c354a8645ad26eb33b71f3d38a010887d72c2a992f1f11921b34d0c14223bc8c9ceb6811d24e",
          "sha256": "9d1876f99d1ebba5bc32e817c3133438457e2e10036559e95028f159deb50f29",
          "sha1": "aecfa2d6a2f80c996e0cb2cc77d0a7ccabd935fa",
          "md5": "4903f16cc805ab3695c74ca727c10b7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.57-sources.jar",
          "url": "sqflite_android_release-0.0.57-sources.jar",
          "size": 23748,
          "sha512": "79a18e8544303c175a5518d48dc0d23a617f6da7f5ddf699a7e94e154c1a221a1182d6b22363d34103e63d7e17decb835bdc2e3e92bfe0d08b1be7349ecc3847",
          "sha256": "7c4ef41dcd75693d0abddc88b3ba5c2fd30c31ee71155462d81055d982095868",
          "sha1": "8b554a039e5de13b3998bf9f2a1ef11cda40c2f1",
          "md5": "54e2ffa57d01fe69ac670dda7fb4b5f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.57-javadoc.jar",
          "url": "sqflite_android_release-0.0.57-javadoc.jar",
          "size": 339916,
          "sha512": "29aedf0fd04602ef8d909d81dbf0e71ab0b6e6bc18d4a6eef61fbeb63b34601ac8cb58564aefc3cc8a675de47a517e8d19f9e322154c0fec3a69a8f772c2e186",
          "sha256": "efa7e5bd020beae04fc8f0884b3f69b9e8207c2237c8c1ea2164558ef824be4e",
          "sha1": "39c23ffd25ff200dc7b4d51e6838a6b30c00d788",
          "md5": "54d78ec16eaa0ae7956e73026f3b8ff1"
        }
      ]
    }
  ]
}
