{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.9.aar",
          "url": "sqflite_release-0.0.9.aar",
          "size": 43424,
          "sha512": "b7bbbec288b263ec89222f04e55ae94349786d1e59fb7269d2e6110891aaa190b0aaa711bfa818cc695f03addbe2891f1034bc8e193bd627cb724906e74a58ad",
          "sha256": "8d62e61570339fc95cd2626a8a808a56a884ab2ac616940a0e48230c63d5b21b",
          "sha1": "9e3386c7c55b7c362179c9693e383523bf2540ac",
          "md5": "19d667639dd97e142806f555bf5f0b37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.9.aar",
          "url": "sqflite_release-0.0.9.aar",
          "size": 43424,
          "sha512": "b7bbbec288b263ec89222f04e55ae94349786d1e59fb7269d2e6110891aaa190b0aaa711bfa818cc695f03addbe2891f1034bc8e193bd627cb724906e74a58ad",
          "sha256": "8d62e61570339fc95cd2626a8a808a56a884ab2ac616940a0e48230c63d5b21b",
          "sha1": "9e3386c7c55b7c362179c9693e383523bf2540ac",
          "md5": "19d667639dd97e142806f555bf5f0b37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.9-sources.jar",
          "url": "sqflite_release-0.0.9-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.9-javadoc.jar",
          "url": "sqflite_release-0.0.9-javadoc.jar",
          "size": 341662,
          "sha512": "0acbcc5a72c12e5c052a280ba5c7aa4c9689747ac9cb7a5745a531c3de2606cfe1dd528cb495b95738bdcfcb29435556b3c6fd2f10ba609821ed39f66440c551",
          "sha256": "16b9e29d806168c8ed72da644fde10f7e53a66d8f67b423bcf16fb4f1fa6ebf1",
          "sha1": "bf06eb954ea88096d73e91a3c6cc1699602ea438",
          "md5": "07f1905ca9b4045e2a4688ad6985a6fb"
        }
      ]
    }
  ]
}
