{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sleep_stage_algorithm",
    "module": "creek_sleep_stage_algorithm_release",
    "version": "9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-9.6.aar",
          "url": "creek_sleep_stage_algorithm_release-9.6.aar",
          "size": 20501,
          "sha512": "5bb1d1fbafcbd866a8e0b3700180bf6d7441b28b4e1b377cac5f9584712b8dab94a9210dc5e44df4a0d13f0c691014dbb88d53057914462896ef0164123e7237",
          "sha256": "0c4ca3fb2dbd8cd1cae5eea9a75028efc536555d33a3259ff2b2d4d14c4718b2",
          "sha1": "263ae87f986c6622cad641c5db61196401998eb5",
          "md5": "01eef123ce49359c0fe0fe7a6241938a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-9.6.aar",
          "url": "creek_sleep_stage_algorithm_release-9.6.aar",
          "size": 20501,
          "sha512": "5bb1d1fbafcbd866a8e0b3700180bf6d7441b28b4e1b377cac5f9584712b8dab94a9210dc5e44df4a0d13f0c691014dbb88d53057914462896ef0164123e7237",
          "sha256": "0c4ca3fb2dbd8cd1cae5eea9a75028efc536555d33a3259ff2b2d4d14c4718b2",
          "sha1": "263ae87f986c6622cad641c5db61196401998eb5",
          "md5": "01eef123ce49359c0fe0fe7a6241938a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-9.6-sources.jar",
          "url": "creek_sleep_stage_algorithm_release-9.6-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-9.6-javadoc.jar",
          "url": "creek_sleep_stage_algorithm_release-9.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
