{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-6.3.aar",
          "url": "azure_speech_release-6.3.aar",
          "size": 9440,
          "sha512": "42a4c5c3fb8ec6260139d4dac66bce48d0caed1df59e9139853a6ee17d029127e870696fb435928fa8807dc7fdd4f0f1d47ad0b39dae8d18d7cbf631b5070b39",
          "sha256": "2162e6a7260d4d317bd80e0ec8a0b98ffa1873c8b7e4c3948627b9c933db0a60",
          "sha1": "31f2ea8dfb23137779a1038650077d9a6f489ec3",
          "md5": "b6b966e2eb6f50eac687033ea3f54019"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-6.3.aar",
          "url": "azure_speech_release-6.3.aar",
          "size": 9440,
          "sha512": "42a4c5c3fb8ec6260139d4dac66bce48d0caed1df59e9139853a6ee17d029127e870696fb435928fa8807dc7fdd4f0f1d47ad0b39dae8d18d7cbf631b5070b39",
          "sha256": "2162e6a7260d4d317bd80e0ec8a0b98ffa1873c8b7e4c3948627b9c933db0a60",
          "sha1": "31f2ea8dfb23137779a1038650077d9a6f489ec3",
          "md5": "b6b966e2eb6f50eac687033ea3f54019"
        }
      ]
    }
  ]
}
