{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boskokg.flutter_blue_plus",
    "module": "flutter_blue_plus_release",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.0.0-rc-2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.3.aar",
          "url": "flutter_blue_plus_release-0.0.3.aar",
          "size": 214015,
          "sha512": "f3deaada3e9f4a9a8f1e39a44b89eacf2b940afb81fd5eea237d8a1fc67ae233cd03d0d2a7224a6daa5bb5fa36553d6c590341abd847cf12653b25635026ff24",
          "sha256": "cb9b2a42d52d5091ca9755704c51b7594a2e9d19481b21f5af74da4a2f6c121f",
          "sha1": "c3a230190844c44705388729429f15b58931269e",
          "md5": "07eb1ac88ca7a3ae42333d13a531e415"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.0.0-rc-2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.3.aar",
          "url": "flutter_blue_plus_release-0.0.3.aar",
          "size": 214015,
          "sha512": "f3deaada3e9f4a9a8f1e39a44b89eacf2b940afb81fd5eea237d8a1fc67ae233cd03d0d2a7224a6daa5bb5fa36553d6c590341abd847cf12653b25635026ff24",
          "sha256": "cb9b2a42d52d5091ca9755704c51b7594a2e9d19481b21f5af74da4a2f6c121f",
          "sha1": "c3a230190844c44705388729429f15b58931269e",
          "md5": "07eb1ac88ca7a3ae42333d13a531e415"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.3-sources.jar",
          "url": "flutter_blue_plus_release-0.0.3-sources.jar",
          "size": 53046,
          "sha512": "b5eb33789fcbcd16a553f09696f2024c80b3fdfb6be3717585a4c4166b9aed8fc9439bbe74dafc8fae0f3cfcc190c41d64ea4f4fb5a7d48f49fb486d2dd94b6c",
          "sha256": "0d746d387f84cefb08133a8b6386d76a4e2093a61daff60cce2478314c261d04",
          "sha1": "ed081e5c46778799ae1d1b1aa99246367b54a2a7",
          "md5": "ea49a0a97b6c1f0414cff11984273bc5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.3-javadoc.jar",
          "url": "flutter_blue_plus_release-0.0.3-javadoc.jar",
          "size": 725997,
          "sha512": "21a6c31a88d09e874c2fc2e94dcf723355a0bd448bc1a096bf32cd28919c3b82cc3493c31d036ff8b1a941fea634ac4f64e3af752f30244607a1a214765c41c0",
          "sha256": "3cdc1007fddeb71a79ed94f08273e3a6f1d2306270eebfe5328a46025e91fd7f",
          "sha1": "9badf1656173652b53afeaf4fa20abe2ab8f1456",
          "md5": "81f77e7a0e464714344cde2ad8975676"
        }
      ]
    }
  ]
}
