{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "creek_ffmpeg_kit_flutter_release",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-0.0.13.aar",
          "url": "creek_ffmpeg_kit_flutter_release-0.0.13.aar",
          "size": 26719,
          "sha512": "79dc36a48e91db7515cd692962f42dad52ab61a533495fbf8530b8abe277a52a43d454c5bbfd434c2cb2547042cba5e5178d203b9434c2b6974618e16ebec4f7",
          "sha256": "57aca8603defab78f33d70a8d5e4e5c57c78bc3637507a3207e714c2aece2a79",
          "sha1": "ce60474122155a0582231173b6e4544a4e1a586f",
          "md5": "ca500a0d8b6cf1ec288f7778dd9e9bf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "arthenica",
          "module": "creek-ffmpeg-kit-https",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-0.0.13.aar",
          "url": "creek_ffmpeg_kit_flutter_release-0.0.13.aar",
          "size": 26719,
          "sha512": "79dc36a48e91db7515cd692962f42dad52ab61a533495fbf8530b8abe277a52a43d454c5bbfd434c2cb2547042cba5e5178d203b9434c2b6974618e16ebec4f7",
          "sha256": "57aca8603defab78f33d70a8d5e4e5c57c78bc3637507a3207e714c2aece2a79",
          "sha1": "ce60474122155a0582231173b6e4544a4e1a586f",
          "md5": "ca500a0d8b6cf1ec288f7778dd9e9bf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-0.0.13-sources.jar",
          "url": "creek_ffmpeg_kit_flutter_release-0.0.13-sources.jar",
          "size": 14776,
          "sha512": "40c98156259926efc4c41bef55667936c2a132d961444653c60f565ece2e58aebc34e2aef5086b83fd17632ad589febff57f2e35df7ec2b8021d180bab809d0e",
          "sha256": "b422ae0e9f2db04414511b88e1c5bc4f431edf05110fdf641ac9a67958d0f7ad",
          "sha1": "19af9e7fc11f98350e731b4aa3baa286a5796815",
          "md5": "39fcc732a4d22bd1834ee499ef54f45d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-0.0.13-javadoc.jar",
          "url": "creek_ffmpeg_kit_flutter_release-0.0.13-javadoc.jar",
          "size": 284559,
          "sha512": "d1244f2be9f8478f2633f551f1be7ce0e25e175b88a0f8e2bdd190292e837538423b828c9bac6dd43f47ada50c770db269c964e55fe3c6c99a3d9920527114a2",
          "sha256": "5b22e194679f6526b7a371f4919c6862b4296e6965ede45f068b383744f43fb6",
          "sha1": "d8542dfef31a1b8dc29c8ae4cc19a87c9181e515",
          "md5": "78fc6318a5d19ffa9fec7b4433f5329f"
        }
      ]
    }
  ]
}
