{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.lz4",
    "module": "lz4_release",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-0.0.43.aar",
          "url": "lz4_release-0.0.43.aar",
          "size": 140326,
          "sha512": "798ba1301ed280ee2d3ead88c4f468d424c1b33b34f1abf4b9f679dad0b159f2bca108631c28ba916e612ddd7a51a151a6b0608794d9cf927e3205e23e3c1108",
          "sha256": "fe3ec8369f12b04a404b0388fb031f54bce1583965d46722d461cda9dd30194d",
          "sha1": "ab9fe8c7445c973bffd8ecc3bd22f42a08619a5b",
          "md5": "ed4050f27bdf0b96c15fa074a1c5b5f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-0.0.43.aar",
          "url": "lz4_release-0.0.43.aar",
          "size": 140326,
          "sha512": "798ba1301ed280ee2d3ead88c4f468d424c1b33b34f1abf4b9f679dad0b159f2bca108631c28ba916e612ddd7a51a151a6b0608794d9cf927e3205e23e3c1108",
          "sha256": "fe3ec8369f12b04a404b0388fb031f54bce1583965d46722d461cda9dd30194d",
          "sha1": "ab9fe8c7445c973bffd8ecc3bd22f42a08619a5b",
          "md5": "ed4050f27bdf0b96c15fa074a1c5b5f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lz4_release-0.0.43-sources.jar",
          "url": "lz4_release-0.0.43-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lz4_release-0.0.43-javadoc.jar",
          "url": "lz4_release-0.0.43-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
