{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boskokg.flutter_blue_plus",
    "module": "flutter_blue_plus_release",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-2.8.aar",
          "url": "flutter_blue_plus_release-2.8.aar",
          "size": 204864,
          "sha512": "94f0814d50dd7fe9c6ebf87f81da805a73f6ec56a6bacaa17c82b4ad1f4e8c68d1dece17f42845fe6ad0ef5a6e745994bffbb5e9832280853ef77071ce94a824",
          "sha256": "9e17df34682bf6b63526b794680f0c96f659492e88260d622458e579049d30d7",
          "sha1": "969529075179607dfdc5d369da8bd50c7ed7b496",
          "md5": "fbcd06fc20f783d2981a4c4fb394dba3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-2.8.aar",
          "url": "flutter_blue_plus_release-2.8.aar",
          "size": 204864,
          "sha512": "94f0814d50dd7fe9c6ebf87f81da805a73f6ec56a6bacaa17c82b4ad1f4e8c68d1dece17f42845fe6ad0ef5a6e745994bffbb5e9832280853ef77071ce94a824",
          "sha256": "9e17df34682bf6b63526b794680f0c96f659492e88260d622458e579049d30d7",
          "sha1": "969529075179607dfdc5d369da8bd50c7ed7b496",
          "md5": "fbcd06fc20f783d2981a4c4fb394dba3"
        }
      ]
    }
  ]
}
