{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "0.0.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.54.aar",
          "url": "shared_preferences_android_release-0.0.54.aar",
          "size": 112329,
          "sha512": "f73774b1ac92421b8df7fb4d99b1188f4dc86ca8d17794d5ba731f7009bf7336ddb589f5a02cba7f500eb1db1ffdb1c3083e0185cb20a381ea697e61d5764eb8",
          "sha256": "47ff00186aa60d5eb8b5b384f4846c4c444417a4c7749af7d1d8d6a56364945d",
          "sha1": "e469923958f02def716d95323a2033bcb0517104",
          "md5": "f26895e03540929d7503ea9814cee662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.54.aar",
          "url": "shared_preferences_android_release-0.0.54.aar",
          "size": 112329,
          "sha512": "f73774b1ac92421b8df7fb4d99b1188f4dc86ca8d17794d5ba731f7009bf7336ddb589f5a02cba7f500eb1db1ffdb1c3083e0185cb20a381ea697e61d5764eb8",
          "sha256": "47ff00186aa60d5eb8b5b384f4846c4c444417a4c7749af7d1d8d6a56364945d",
          "sha1": "e469923958f02def716d95323a2033bcb0517104",
          "md5": "f26895e03540929d7503ea9814cee662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.54-sources.jar",
          "url": "shared_preferences_android_release-0.0.54-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.54-javadoc.jar",
          "url": "shared_preferences_android_release-0.0.54-javadoc.jar",
          "size": 358456,
          "sha512": "a516a03d4dfdbb492f534653cb14c2407c54289532ed3658351ebf90b60cd51d38ea970c2b56d2f71490f4ba7bc1acbb2694e8698136e08e1c6bb508be614aaf",
          "sha256": "8bca623b2907f81b9c111aa5a5b85e4b0860eea74ffe4ba03be1c3249d8c3b87",
          "sha1": "063575aa9a8b381cd199321564ca077aab8e0366",
          "md5": "91c8a585ff6081f3b7a5e493fca1b6db"
        }
      ]
    }
  ]
}
