{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_voice_assistant",
    "module": "creek_voice_assistant_release",
    "version": "9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_voice_assistant_release-9.0.aar",
          "url": "creek_voice_assistant_release-9.0.aar",
          "size": 15071,
          "sha512": "7d9bd4a85499417eb959a594c63482e68c2b7f07e34cc29d617bc9b0cfaefb5db5447de08aa2a7209abc2097b23795365b3d922e1514f9f3fba7417b78021528",
          "sha256": "8de0c27022ab2b48c2cb4c9e9b97dfea82fd8d259df504740ae1e296db0e2d16",
          "sha1": "2b0491fd7eacc964cc474de75140b9c6eed68706",
          "md5": "d7365b6162f34d6c5d219b114c8242d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.whelksoft.flutter_native_timezone",
          "module": "flutter_native_timezone_updated_gradle_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.opusBridge.opus_bridge",
          "module": "opus_bridge_release",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "9.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_voice_assistant_release-9.0.aar",
          "url": "creek_voice_assistant_release-9.0.aar",
          "size": 15071,
          "sha512": "7d9bd4a85499417eb959a594c63482e68c2b7f07e34cc29d617bc9b0cfaefb5db5447de08aa2a7209abc2097b23795365b3d922e1514f9f3fba7417b78021528",
          "sha256": "8de0c27022ab2b48c2cb4c9e9b97dfea82fd8d259df504740ae1e296db0e2d16",
          "sha1": "2b0491fd7eacc964cc474de75140b9c6eed68706",
          "md5": "d7365b6162f34d6c5d219b114c8242d9"
        }
      ]
    }
  ]
}
