{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.17.aar",
          "url": "path_provider_android_release-0.0.17.aar",
          "size": 10306,
          "sha512": "1117b79e8443bc563887e53bfe19b67aa998591a5454cedd40d058a9607aa382a65e41d889c55ab2a8cb422f6d54e3d117b3eb9af3177e69d64e84559d2903df",
          "sha256": "2aa0a3f5ea12e92cda39322beccb0ded3010927ce0479940be67a15de816618a",
          "sha1": "879efea521c97e242d400480be524c1e127360e5",
          "md5": "ef13108e065e048e3c8acc93c8727086"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.17.aar",
          "url": "path_provider_android_release-0.0.17.aar",
          "size": 10306,
          "sha512": "1117b79e8443bc563887e53bfe19b67aa998591a5454cedd40d058a9607aa382a65e41d889c55ab2a8cb422f6d54e3d117b3eb9af3177e69d64e84559d2903df",
          "sha256": "2aa0a3f5ea12e92cda39322beccb0ded3010927ce0479940be67a15de816618a",
          "sha1": "879efea521c97e242d400480be524c1e127360e5",
          "md5": "ef13108e065e048e3c8acc93c8727086"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.17-sources.jar",
          "url": "path_provider_android_release-0.0.17-sources.jar",
          "size": 4121,
          "sha512": "98abfe49b0c49012cf74c573e26b0af84ff0b734f9b13ef74b5ee09b3731a8f699a41cbad0060a6f53788a35b595f6cea8b6d24a9b28fc28c55faf578ea78335",
          "sha256": "95e5edc3e2309e7fe549d0d67b05848a141eb5ea996c7e68ce2990e32191cb46",
          "sha1": "e0c3107497e5fa098fb6a873e214796778aee5d7",
          "md5": "6fb2208a851ccf1b24b54473fb99bc03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.17-javadoc.jar",
          "url": "path_provider_android_release-0.0.17-javadoc.jar",
          "size": 294231,
          "sha512": "fa78f7b38343d6f2a8e4a8558870b5ce75754cb62179223101c4d4d0d3736f378ce3670ca18f880f7d009dcf88a4bc6e42973e83b6353e03ecaeb3ebdd578cc0",
          "sha256": "c680459482bfc0e508f4b5b41a287020ae5073d5d58221c46840ed20f65eb1a5",
          "sha1": "8c0faedb5c66e5c392c500ca897b16bdced97e93",
          "md5": "f6f4d09120eb7cff084139aae705b12e"
        }
      ]
    }
  ]
}
