{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_voice_assistant",
    "module": "creek_voice_assistant_release",
    "version": "10.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_voice_assistant_release-10.9.aar",
          "url": "creek_voice_assistant_release-10.9.aar",
          "size": 2691,
          "sha512": "c57701ee29f9334c1096919fa24cc14789408a7c5605ae322cfcb16d5e39beef90a7a4b7eb541daa6f7f1799e054e75ac6f963320d894e0549f717b0ef8b4544",
          "sha256": "0611cc2f8993d54febe2b1b60222c2991c013e558914832db58aaad9d6ef604f",
          "sha1": "abdd0b425f26ba7e06fa64df8f5de32fd54b4e22",
          "md5": "d876210b8f6c0c2d7e99b307863fd39b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_voice_assistant_release-10.9.aar",
          "url": "creek_voice_assistant_release-10.9.aar",
          "size": 2691,
          "sha512": "c57701ee29f9334c1096919fa24cc14789408a7c5605ae322cfcb16d5e39beef90a7a4b7eb541daa6f7f1799e054e75ac6f963320d894e0549f717b0ef8b4544",
          "sha256": "0611cc2f8993d54febe2b1b60222c2991c013e558914832db58aaad9d6ef604f",
          "sha1": "abdd0b425f26ba7e06fa64df8f5de32fd54b4e22",
          "md5": "d876210b8f6c0c2d7e99b307863fd39b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_voice_assistant_release-10.9-sources.jar",
          "url": "creek_voice_assistant_release-10.9-sources.jar",
          "size": 1329,
          "sha512": "99d53ab04432acaae64a40f642cb881834c122817a36774847287e10b4085b723302c3a87abd6801aa0c6c0e62017480ec50747d2c69c4a615b1b619800cb392",
          "sha256": "da51bd286e89d16d6c6d16a52a6920ccbeca4fa8c83a7cd74d8ed7be8334bb00",
          "sha1": "ac87bc9cf27b136205309ece64ca603e694be15d",
          "md5": "ab9a2beeb4fcf956d1c74ef5e4bb2dce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_voice_assistant_release-10.9-javadoc.jar",
          "url": "creek_voice_assistant_release-10.9-javadoc.jar",
          "size": 260787,
          "sha512": "61792506654360941a47f2075e1e5e26ca1fec695dadead0ff84387fabae33986cbc46515476592344d77a9ee8a34f0a4aa2c82933d3814b0d4e7f3cec42182f",
          "sha256": "47f971bd725fecd34be10d4cdd15ffc6cb757f375e596ac64d9f501d4341454b",
          "sha1": "671ae74be8675496ee64b913266c6c866c655f0a",
          "md5": "fdcef60106bb8885f66bcfdb6555d01a"
        }
      ]
    }
  ]
}
