{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.13.aar",
          "url": "azure_speech_release-0.0.13.aar",
          "size": 8044,
          "sha512": "d6a1802c496101747cf4d54dedfb4c61741cb39ebd07d19ba3c5c3c1f6f8f6d2305ff1ec9dd437ddcf163ebe12810d69e6b78e4bfe59a28f9a8d2f548b29d070",
          "sha256": "59872e4f84c87f9e8d49e4574628bc43414c80f0d5b9d931c00e67af30b320db",
          "sha1": "05705c838a71813eeccb58aeed5adc5e2dd0f2ca",
          "md5": "07a077c72506e240dc6289cbcaa8f780"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.13.aar",
          "url": "azure_speech_release-0.0.13.aar",
          "size": 8044,
          "sha512": "d6a1802c496101747cf4d54dedfb4c61741cb39ebd07d19ba3c5c3c1f6f8f6d2305ff1ec9dd437ddcf163ebe12810d69e6b78e4bfe59a28f9a8d2f548b29d070",
          "sha256": "59872e4f84c87f9e8d49e4574628bc43414c80f0d5b9d931c00e67af30b320db",
          "sha1": "05705c838a71813eeccb58aeed5adc5e2dd0f2ca",
          "md5": "07a077c72506e240dc6289cbcaa8f780"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-0.0.13-sources.jar",
          "url": "azure_speech_release-0.0.13-sources.jar",
          "size": 2992,
          "sha512": "221a0f14e84696c1164cd0fd41bbdaf33b562ba5adf8d6405bd43d1f11c4a66c17b20cb360167e9a1fbd545780f22b008a2dea893e52756fdf50d99ee255dc24",
          "sha256": "29897b54dadf3cb618852ceefda91f02aa80bc1eb65db5803be7a447faf0e822",
          "sha1": "f746badb3c983cf933aed73eb9538624e47f239d",
          "md5": "dae7e6434aa902d55e4f784153e8af8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-0.0.13-javadoc.jar",
          "url": "azure_speech_release-0.0.13-javadoc.jar",
          "size": 262206,
          "sha512": "5b785cbdd80281101195466d7ecd58f696054216994f438e09099e8dfb305cf6cab950e216dfdacdd3cf94df26604ec4963cee41d70c0a0c98f588bef026d535",
          "sha256": "12c30705f0a7fbaf5248f5400d1d69cff5af774064fe1e5dd9b8f6953f532f1e",
          "sha1": "3a1dd8be799707f2e1c2ddbda35e021dd5410da1",
          "md5": "a865f9e31845cffc6e2371957098f29b"
        }
      ]
    }
  ]
}
