{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.6.aar",
          "url": "creek_blue_manage_release-0.0.6.aar",
          "size": 30356,
          "sha512": "0df40cfbc8ff15ed9c4889a0112ff18cc3d41a483d077b672b8d3294f4fc707f2a743a7a010ae5e91df930545586665baad331e22f9cdd7a55cb0ac1a1879bd2",
          "sha256": "62fa5940b7648067dc36d8f217d41900f4fb70c37d8c6dc33e8d00bede0cd9d7",
          "sha1": "3406b9ae91d534a941dae82c4948336c7fb6245a",
          "md5": "a5233a8ad732920e47a169b636d6474e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.example.creek_index_convert",
          "module": "creek_index_convert_release",
          "version": {
            "requires": "0.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.6.aar",
          "url": "creek_blue_manage_release-0.0.6.aar",
          "size": 30356,
          "sha512": "0df40cfbc8ff15ed9c4889a0112ff18cc3d41a483d077b672b8d3294f4fc707f2a743a7a010ae5e91df930545586665baad331e22f9cdd7a55cb0ac1a1879bd2",
          "sha256": "62fa5940b7648067dc36d8f217d41900f4fb70c37d8c6dc33e8d00bede0cd9d7",
          "sha1": "3406b9ae91d534a941dae82c4948336c7fb6245a",
          "md5": "a5233a8ad732920e47a169b636d6474e"
        }
      ]
    }
  ]
}
