{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.36.aar",
          "url": "permission_handler_android_release-0.0.36.aar",
          "size": 26441,
          "sha512": "75b2f117fdc712618b5a084e01dfc9785de24b10c862b218c3b0f214f7e20c11d9434a8a114330276996effe73820b566c32823eb00e2eaf457b8974b60e0979",
          "sha256": "0f98bb87e91586eb8bb736ae821af20166bce26baee25bd316f6786ee7eb7c53",
          "sha1": "d2e7122f9b6bfa25d2ebc2b317679746a670da10",
          "md5": "65600598f715f09db0ab2ea0f9dff0dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.36.aar",
          "url": "permission_handler_android_release-0.0.36.aar",
          "size": 26441,
          "sha512": "75b2f117fdc712618b5a084e01dfc9785de24b10c862b218c3b0f214f7e20c11d9434a8a114330276996effe73820b566c32823eb00e2eaf457b8974b60e0979",
          "sha256": "0f98bb87e91586eb8bb736ae821af20166bce26baee25bd316f6786ee7eb7c53",
          "sha1": "d2e7122f9b6bfa25d2ebc2b317679746a670da10",
          "md5": "65600598f715f09db0ab2ea0f9dff0dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.36-sources.jar",
          "url": "permission_handler_android_release-0.0.36-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.36-javadoc.jar",
          "url": "permission_handler_android_release-0.0.36-javadoc.jar",
          "size": 264580,
          "sha512": "27efc490dfff2d81ae70ab77f259e45ae10c82f12a31227de0599e62fbe1263384dddc6d7660c1fb822cb86aeb7e0ff4196e13a229328aba8ba583a2d4fe144c",
          "sha256": "8cf315d2ac79af8d68eb7b1e33ef978709ca34493bbd2d84c6271e5e0be12215",
          "sha1": "1b6fba5347389fc6c8184f33fe0926ec74d2f12a",
          "md5": "fcfc82f2b15e4a589794a31b606100e3"
        }
      ]
    }
  ]
}
