{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boskokg.flutter_blue_plus",
    "module": "flutter_blue_plus_release",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.0.0-rc-2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.17.aar",
          "url": "flutter_blue_plus_release-0.0.17.aar",
          "size": 217302,
          "sha512": "c3fb51cb7b3ff73b30737aaaaeb3dfd9e6abe8dab90cfb2390e841ba9431b1d9f76199e99cd8ad116a405a49489a9407c6611b30eb987753d06aaf4be57e8ff9",
          "sha256": "4544a8c75ee8929ae4bdaecce211735c4a36ea6c7195faa5f3018b60c2da8b09",
          "sha1": "da255841d73d1c4ea48a422af5422099fda8b06c",
          "md5": "a090ac53dca128cd84a81abdad601312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.0.0-rc-2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_release-0.0.17.aar",
          "url": "flutter_blue_plus_release-0.0.17.aar",
          "size": 217302,
          "sha512": "c3fb51cb7b3ff73b30737aaaaeb3dfd9e6abe8dab90cfb2390e841ba9431b1d9f76199e99cd8ad116a405a49489a9407c6611b30eb987753d06aaf4be57e8ff9",
          "sha256": "4544a8c75ee8929ae4bdaecce211735c4a36ea6c7195faa5f3018b60c2da8b09",
          "sha1": "da255841d73d1c4ea48a422af5422099fda8b06c",
          "md5": "a090ac53dca128cd84a81abdad601312"
        }
      ]
    }
  ]
}
