{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sdk",
    "module": "flutter_release",
    "version": "0.0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.0.64"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.64.aar",
          "url": "flutter_release-0.0.64.aar",
          "size": 9251208,
          "sha512": "68804aeded13917a9d9181e49db6124cf76a8d707ad155007fbb23b26c474ea6f4f001c669e157e1c227fa00d2b2b5fe30f65329811fdeb2327fd147f42d3100",
          "sha256": "d98dafa4db21097f1991ca3725edf52bf14edd0b64d13defbbdd69abfc49b653",
          "sha1": "37573ee73ddb00f1db34a0f15a426cf2e8451d64",
          "md5": "cc6b642e7f697899ea5958edd44d9865"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "0.0.64"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.0.64"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.64.aar",
          "url": "flutter_release-0.0.64.aar",
          "size": 9251208,
          "sha512": "68804aeded13917a9d9181e49db6124cf76a8d707ad155007fbb23b26c474ea6f4f001c669e157e1c227fa00d2b2b5fe30f65329811fdeb2327fd147f42d3100",
          "sha256": "d98dafa4db21097f1991ca3725edf52bf14edd0b64d13defbbdd69abfc49b653",
          "sha1": "37573ee73ddb00f1db34a0f15a426cf2e8451d64",
          "md5": "cc6b642e7f697899ea5958edd44d9865"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.0.64-sources.jar",
          "url": "flutter_release-0.0.64-sources.jar",
          "size": 1297,
          "sha512": "b9f5bed6a98e66b92cb69f12e9b5de6c477b6e25f04068553649673ee9e81eee79cdb21d8806fa0941992697f8e5a8f4936ec729abbb93ac9c2a3bec0d70ae33",
          "sha256": "bdf48a61c6f27cde3209dada74caab2873358c7c8e8e16be37f86992d5c6b643",
          "sha1": "fab5838d36969b09439c7de35889509b9c589aaf",
          "md5": "19f9436cd3c94e3f41df359d730c0768"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.0.64-javadoc.jar",
          "url": "flutter_release-0.0.64-javadoc.jar",
          "size": 261623,
          "sha512": "f205dc5e6e70b8e916bf0a84b7c263a9bd5f420a47df7bb6ff0b4a1dfbd4eb1093a391ddfd24a035d72ed26c14fa8954262ca966fe42ae7e408c731c74b8f56b",
          "sha256": "be0bd7a4a60f879d3dbffd3275ef6f2b71431ea349d9e9c84a3aea868f34f827",
          "sha1": "e5e8c7067f8ec32233070064b7e71940b43fd7f7",
          "md5": "ef172133f0e950a950ba3c57ee0fe158"
        }
      ]
    }
  ]
}
