{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.3.aar",
          "url": "path_provider_android_release-0.0.3.aar",
          "size": 10143,
          "sha512": "619cb779acaf2ec8ef04f8067d51166a5e65e8d975a1afed7a1cbb0a3cd62c8b21083f8628e4d1ef9a3281be8dabcb328b873e617b4638038f9d11a72ee37918",
          "sha256": "7d2b64535a70e132f40eb9eb2e75ff72435ea5d23c539a197e03fd5f3265ba4c",
          "sha1": "a387555930fd6a8431eee41e8882b7ca226f8983",
          "md5": "184e390219e8e13e507506d2eb070f89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.3.aar",
          "url": "path_provider_android_release-0.0.3.aar",
          "size": 10143,
          "sha512": "619cb779acaf2ec8ef04f8067d51166a5e65e8d975a1afed7a1cbb0a3cd62c8b21083f8628e4d1ef9a3281be8dabcb328b873e617b4638038f9d11a72ee37918",
          "sha256": "7d2b64535a70e132f40eb9eb2e75ff72435ea5d23c539a197e03fd5f3265ba4c",
          "sha1": "a387555930fd6a8431eee41e8882b7ca226f8983",
          "md5": "184e390219e8e13e507506d2eb070f89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.3-sources.jar",
          "url": "path_provider_android_release-0.0.3-sources.jar",
          "size": 4689,
          "sha512": "393ff86455165de18b7a102452a6f1434cafbdaa5bb2e9191230d753addd814c5ba33a3662dac95f8c8e2851a155014a2cebf9978bd075c569002b8852fe0b67",
          "sha256": "47c585346554942b1a793181486d70b5ff14b69ff1aa332ba1fc8e01af0a6464",
          "sha1": "7eb6c06469537e38fe2699f24f9d3ec0a20080f4",
          "md5": "dfb79a1435833d291d93d6d7c818c936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.3-javadoc.jar",
          "url": "path_provider_android_release-0.0.3-javadoc.jar",
          "size": 294096,
          "sha512": "362a82fcc87ccaa07f03a5dad80550e427a2bc1c5e384be7b4b375380e3c909cf21868ec15eac3d0f3ae47bc495562a273bdb9acc97c9bb47633fe3a9df2fdf4",
          "sha256": "18e4553e3f313f436ba063d7818092f4360b30a00e28f9620bf01332d02962e7",
          "sha1": "cc82fc9dd37787537b71987fff5aabd18dbd9a82",
          "md5": "bb2ac2c4af17206b4f2ef3060efc1bf1"
        }
      ]
    }
  ]
}
