{
  "formatVersion": "1.1",
  "component": {
    "group": "com.whelksoft.flutter_native_timezone",
    "module": "flutter_native_timezone_updated_gradle_release",
    "version": "7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_native_timezone_updated_gradle_release-7.0.aar",
          "url": "flutter_native_timezone_updated_gradle_release-7.0.aar",
          "size": 6648,
          "sha512": "e4e17a3e848f3bf68ece8e068cdbd52d578b1375497960ab3d317cac6366d00d45d30fce6034677d4c5953347650aeafa194c082ffa0352240dbb28355972176",
          "sha256": "f006799255f77c6a7e53b7f04803ce46a4db968eea3a31ffcd64f5b86e285391",
          "sha1": "03e8d970230ca604d81ccde9fe02ca65b7781118",
          "md5": "e1c6e58b8e117676574108a038e70968"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_native_timezone_updated_gradle_release-7.0.aar",
          "url": "flutter_native_timezone_updated_gradle_release-7.0.aar",
          "size": 6648,
          "sha512": "e4e17a3e848f3bf68ece8e068cdbd52d578b1375497960ab3d317cac6366d00d45d30fce6034677d4c5953347650aeafa194c082ffa0352240dbb28355972176",
          "sha256": "f006799255f77c6a7e53b7f04803ce46a4db968eea3a31ffcd64f5b86e285391",
          "sha1": "03e8d970230ca604d81ccde9fe02ca65b7781118",
          "md5": "e1c6e58b8e117676574108a038e70968"
        }
      ]
    }
  ]
}
