{
  "formatVersion": "1.1",
  "component": {
    "group": "com.actions.actres",
    "module": "actres_release",
    "version": "8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "actres_release-8.5.aar",
          "url": "actres_release-8.5.aar",
          "size": 1399251,
          "sha512": "345af7ae0696bf776c01dc9f27f9f72ca119446b05f708f897f2b70502b41d09b7d98e25ce07016167a438b895eb6a8d3f113c0e6c8973cef4ff9f3de2d0be87",
          "sha256": "b644e86a39ee50aefc419734dfae780f6f5d4d7c556f3ab49eee14c6150a3a38",
          "sha1": "ef8c742b5e3a549d34005964affbd34d7ffba0bb",
          "md5": "5cb5d322ee31119506b0e44e0e46c453"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "actres_release-8.5.aar",
          "url": "actres_release-8.5.aar",
          "size": 1399251,
          "sha512": "345af7ae0696bf776c01dc9f27f9f72ca119446b05f708f897f2b70502b41d09b7d98e25ce07016167a438b895eb6a8d3f113c0e6c8973cef4ff9f3de2d0be87",
          "sha256": "b644e86a39ee50aefc419734dfae780f6f5d4d7c556f3ab49eee14c6150a3a38",
          "sha1": "ef8c742b5e3a549d34005964affbd34d7ffba0bb",
          "md5": "5cb5d322ee31119506b0e44e0e46c453"
        }
      ]
    }
  ]
}
