{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-2.0.aar",
          "url": "sbc_release-2.0.aar",
          "size": 73284,
          "sha512": "e4f73beb165724519634b36e9674556a0e3d8dabe07ec45f519b16cfd13b947f3b21345020779a082165b7037807fa3261bbcf0e8746a52743fc440ca9ee35b0",
          "sha256": "358946ee5a16f8d923736a977f1d22d0a37be82c906d485dd2296c10372e8bfe",
          "sha1": "dc480b4b94b29571ee29266cc85b4e7890995119",
          "md5": "2046a4633a60393b58eba8b877c75e3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-bd986c5ed20a62dc34b7718c50abc782beae4c33"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-2.0.aar",
          "url": "sbc_release-2.0.aar",
          "size": 73284,
          "sha512": "e4f73beb165724519634b36e9674556a0e3d8dabe07ec45f519b16cfd13b947f3b21345020779a082165b7037807fa3261bbcf0e8746a52743fc440ca9ee35b0",
          "sha256": "358946ee5a16f8d923736a977f1d22d0a37be82c906d485dd2296c10372e8bfe",
          "sha1": "dc480b4b94b29571ee29266cc85b4e7890995119",
          "md5": "2046a4633a60393b58eba8b877c75e3a"
        }
      ]
    }
  ]
}
