{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-2.0.aar",
          "url": "sbc_release-2.0.aar",
          "size": 73282,
          "sha512": "7e504e6abe8f8c6c8cbbba8637359641d1b3c651519744f9f4d6e6a7f871e5376a34c89cbd1c0a1d351a8aaaddb1fbc45d7ada98b3b8f43db749db4798e67a8e",
          "sha256": "ac37f5d52b15df8d95f1bc3cf8d85bb1b494db391160d56ee05071cf441bb8fc",
          "sha1": "aca3de86e6eb550dd51ffbefe62cd4394978476e",
          "md5": "64d7c6ecaa3d19122eb9be96e7226f6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-2.0.aar",
          "url": "sbc_release-2.0.aar",
          "size": 73282,
          "sha512": "7e504e6abe8f8c6c8cbbba8637359641d1b3c651519744f9f4d6e6a7f871e5376a34c89cbd1c0a1d351a8aaaddb1fbc45d7ada98b3b8f43db749db4798e67a8e",
          "sha256": "ac37f5d52b15df8d95f1bc3cf8d85bb1b494db391160d56ee05071cf441bb8fc",
          "sha1": "aca3de86e6eb550dd51ffbefe62cd4394978476e",
          "md5": "64d7c6ecaa3d19122eb9be96e7226f6a"
        }
      ]
    }
  ]
}
