{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_voice_assistant",
    "module": "creek_voice_assistant_release",
    "version": "10.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_voice_assistant_release-10.7.aar",
          "url": "creek_voice_assistant_release-10.7.aar",
          "size": 2691,
          "sha512": "c57701ee29f9334c1096919fa24cc14789408a7c5605ae322cfcb16d5e39beef90a7a4b7eb541daa6f7f1799e054e75ac6f963320d894e0549f717b0ef8b4544",
          "sha256": "0611cc2f8993d54febe2b1b60222c2991c013e558914832db58aaad9d6ef604f",
          "sha1": "abdd0b425f26ba7e06fa64df8f5de32fd54b4e22",
          "md5": "d876210b8f6c0c2d7e99b307863fd39b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "com.example.azure_speech",
          "module": "azure_speech_release",
          "version": {
            "requires": "10.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_voice_assistant_release-10.7.aar",
          "url": "creek_voice_assistant_release-10.7.aar",
          "size": 2691,
          "sha512": "c57701ee29f9334c1096919fa24cc14789408a7c5605ae322cfcb16d5e39beef90a7a4b7eb541daa6f7f1799e054e75ac6f963320d894e0549f717b0ef8b4544",
          "sha256": "0611cc2f8993d54febe2b1b60222c2991c013e558914832db58aaad9d6ef604f",
          "sha1": "abdd0b425f26ba7e06fa64df8f5de32fd54b4e22",
          "md5": "d876210b8f6c0c2d7e99b307863fd39b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_voice_assistant_release-10.7-sources.jar",
          "url": "creek_voice_assistant_release-10.7-sources.jar",
          "size": 1329,
          "sha512": "99d53ab04432acaae64a40f642cb881834c122817a36774847287e10b4085b723302c3a87abd6801aa0c6c0e62017480ec50747d2c69c4a615b1b619800cb392",
          "sha256": "da51bd286e89d16d6c6d16a52a6920ccbeca4fa8c83a7cd74d8ed7be8334bb00",
          "sha1": "ac87bc9cf27b136205309ece64ca603e694be15d",
          "md5": "ab9a2beeb4fcf956d1c74ef5e4bb2dce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_voice_assistant_release-10.7-javadoc.jar",
          "url": "creek_voice_assistant_release-10.7-javadoc.jar",
          "size": 260840,
          "sha512": "04b2298749b04c4964612e2ea1cdab9023a1be69e72ef6069aabb760ca7db15c80faf44c39302f45368bda688d7bbe40202fcb76bdca172a552ddf4b4b7ee4ef",
          "sha256": "254d78aa64f88659ee1d8d523ee48bc64b028b27351bb6ba76f7ad62e05a79b2",
          "sha1": "31bcc1b6dc15eb57264b9e493fe5f6347aeb9f6a",
          "md5": "dab3c07df1dfd4ef702be2deda5c110d"
        }
      ]
    }
  ]
}
