{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.1.aar",
          "url": "device_calendar_release-0.0.1.aar",
          "size": 70890,
          "sha512": "6cb10d4fa7e2824ec9359990703b30673678f2c3b83f28fa586bfe559c7befd8d149f8cf57bb24591eaada6af1a4f111a23198d1a398101efd617e0bc983193c",
          "sha256": "bd6a23db6433cb0f530e8787d24256f1ed0555e6003adf3d419ffa3486402185",
          "sha1": "d162b1634f3d564b7ba6916a2b3cbed26760a933",
          "md5": "f246815d7eff0fd9d2d88424f525c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.1.aar",
          "url": "device_calendar_release-0.0.1.aar",
          "size": 70890,
          "sha512": "6cb10d4fa7e2824ec9359990703b30673678f2c3b83f28fa586bfe559c7befd8d149f8cf57bb24591eaada6af1a4f111a23198d1a398101efd617e0bc983193c",
          "sha256": "bd6a23db6433cb0f530e8787d24256f1ed0555e6003adf3d419ffa3486402185",
          "sha1": "d162b1634f3d564b7ba6916a2b3cbed26760a933",
          "md5": "f246815d7eff0fd9d2d88424f525c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-0.0.1-sources.jar",
          "url": "device_calendar_release-0.0.1-sources.jar",
          "size": 19259,
          "sha512": "596df879875dbeecd1171483bba32882cbf94115c8c1448185b993e296994006c7652e4315a994630107b6812bdd5cd1a1562c866d3c0dce284107f4409c2ab6",
          "sha256": "b873a00db27dcf44fb83ed111ce903da44f6dbdf95b5c0ba1c98f0ec56eca9e3",
          "sha1": "6f9e51b7f1534e2d360107cf836efc201ff41c23",
          "md5": "9c871bf2f63334dba398899b5e5ab6e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-0.0.1-javadoc.jar",
          "url": "device_calendar_release-0.0.1-javadoc.jar",
          "size": 369723,
          "sha512": "a6dfc6ba3520c977cefbb452375c0f1411f813ce0a4696cf3e38536dd35716794d9785920b879fa73787078cee1565815223443465a23e912d6d46ec5f7f62d8",
          "sha256": "5747470b705151751b55afc1d36451d70998d120d33459822f923895b1aaa045",
          "sha1": "bd82495ab9d40a0f987541c5d8a1e3e448179938",
          "md5": "29dd2a426ad55f1433fe6bcb123adf83"
        }
      ]
    }
  ]
}
