{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.20.aar",
          "url": "creek_blue_manage_release-0.0.20.aar",
          "size": 20421,
          "sha512": "1b48c397a5d6ffcb3fc58b9ae29f4da38027fbe1594c22512359268ecef738d5576d332d64a2c68a65c524f905cce095b63037da594e51df120a7b1ef73f00a0",
          "sha256": "58183922a1956cb84f07723b1269314807bd14d4216dc1b00d28f3d179a0aea0",
          "sha1": "a1d91fdb33a32ed872bb3379cf3a456b66b09d4c",
          "md5": "c95697d109d30d9d8efded5c4e4ad4bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.example.creek_index_convert",
          "module": "creek_index_convert_release",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.20.aar",
          "url": "creek_blue_manage_release-0.0.20.aar",
          "size": 20421,
          "sha512": "1b48c397a5d6ffcb3fc58b9ae29f4da38027fbe1594c22512359268ecef738d5576d332d64a2c68a65c524f905cce095b63037da594e51df120a7b1ef73f00a0",
          "sha256": "58183922a1956cb84f07723b1269314807bd14d4216dc1b00d28f3d179a0aea0",
          "sha1": "a1d91fdb33a32ed872bb3379cf3a456b66b09d4c",
          "md5": "c95697d109d30d9d8efded5c4e4ad4bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.20-sources.jar",
          "url": "creek_blue_manage_release-0.0.20-sources.jar",
          "size": 7298,
          "sha512": "17bf4ebd7f52bfa8c33b3853716b3bee853ed00ad89abb1b9190f665f53d2540e2a6e77a0f9266023aab52b291e2316e8c8d308842bd347e2568f66052f0ba91",
          "sha256": "c21faef1bd5cb0589139114b3421bc27761a8068af516197d7bb220b6e71c4ce",
          "sha1": "016952c434480c189283fae18b2563f69ec4a1e3",
          "md5": "92877b45c507ccea3982bddadab46cfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.20-javadoc.jar",
          "url": "creek_blue_manage_release-0.0.20-javadoc.jar",
          "size": 298399,
          "sha512": "0427fc193dc015ff2f9298e76018d0d487fcdbd68381fe1eba94456b53c20cd7f99fe76c39073c83e9977c29589392f6de5714d3c6ee7d7561437b3b4fe212da",
          "sha256": "1cfa0a7c1c1e61e9e0c70fdd3ee7b2312bdca56629e9326d1cea700e3b409c77",
          "sha1": "9281043df9aa39512e6a233c1f6197b41eed299b",
          "md5": "ff877bfbd93b87cf690b17d34d460ecf"
        }
      ]
    }
  ]
}
