{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.21.aar",
          "url": "device_calendar_release-0.0.21.aar",
          "size": 84657,
          "sha512": "b5fcbead52051be52bc775c3677cff409a07b9b93654ed7a77a6bbdaad4e12c80ce2882b36c8ae04f669381342791a0c45d4257aebeefccabcd30bd51e3a2177",
          "sha256": "6cee5f35c6212a28f374749a1aed8a35d799d605b009d06d93fe5a553b81db0a",
          "sha1": "183d8828af17f017910b04381333eff68896642f",
          "md5": "3eb036ac28f7ea29e07938fed2357b00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.21.aar",
          "url": "device_calendar_release-0.0.21.aar",
          "size": 84657,
          "sha512": "b5fcbead52051be52bc775c3677cff409a07b9b93654ed7a77a6bbdaad4e12c80ce2882b36c8ae04f669381342791a0c45d4257aebeefccabcd30bd51e3a2177",
          "sha256": "6cee5f35c6212a28f374749a1aed8a35d799d605b009d06d93fe5a553b81db0a",
          "sha1": "183d8828af17f017910b04381333eff68896642f",
          "md5": "3eb036ac28f7ea29e07938fed2357b00"
        }
      ]
    }
  ]
}
