{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "10.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.3.aar",
          "url": "azure_speech_release-10.3.aar",
          "size": 12704,
          "sha512": "f9ff524e5efefea3665b3f6b3e7cb8a9387661db3383d1fb659b57b09b97c0c2dabdee3d82dc2be72a4f005bef2de9c5c7031944ae4a9ddfcc8b1b4ae2f1c9b0",
          "sha256": "936e6ef87aed7ca54729b52aeb066a514578aff115345d809c22402fbddb10c8",
          "sha1": "97aa2e8d4ee08184b3b591e354e8741f59d92ecd",
          "md5": "eae9321999c5b58d72eab38a8004a94c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.3.aar",
          "url": "azure_speech_release-10.3.aar",
          "size": 12704,
          "sha512": "f9ff524e5efefea3665b3f6b3e7cb8a9387661db3383d1fb659b57b09b97c0c2dabdee3d82dc2be72a4f005bef2de9c5c7031944ae4a9ddfcc8b1b4ae2f1c9b0",
          "sha256": "936e6ef87aed7ca54729b52aeb066a514578aff115345d809c22402fbddb10c8",
          "sha1": "97aa2e8d4ee08184b3b591e354e8741f59d92ecd",
          "md5": "eae9321999c5b58d72eab38a8004a94c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.3-sources.jar",
          "url": "azure_speech_release-10.3-sources.jar",
          "size": 4716,
          "sha512": "d6737e296ebf8b9f610cdec4dae5a749683f680dec0589a9cdf14e595c5f4481b5592e14054e1a5ba40cae2aec4cb588125945944616cd63376d5739713025fe",
          "sha256": "a4ebcba754bea5ab4c8548460e1ee3b5148d978654bb4b8591c92e8e0abd9dbe",
          "sha1": "2cfafee64360f6b41ec994f0c8e247a674e6efad",
          "md5": "e0d7339802f8667f06b36eca5e27a2f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.3-javadoc.jar",
          "url": "azure_speech_release-10.3-javadoc.jar",
          "size": 262203,
          "sha512": "6f510d4803be6e855f2025caaa3c9a422b04fd15752018a2930da5459c753e09e89b5906c22fa660e2120d5beaf191dd02a2244428c1cbf2722f552a8dc89288",
          "sha256": "e03384b22e8451f8863224f3058f8bcbbe1e31eb89bd06b81a85bd13d1e05972",
          "sha1": "4fc4bc7b0b2412248065cb00964dbff0c231d03e",
          "md5": "4ca912eb1d4bd9f6afb6388c52712813"
        }
      ]
    }
  ]
}
