{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.15.aar",
          "url": "azure_speech_release-0.0.15.aar",
          "size": 8356,
          "sha512": "c9dc1c4a606655d1145a257752ed21f919eb352bfb222c1c7dd1f038792eb84c447134e1ccb382059edac001b280260ba6fdb8fc13fce27546edbec0814033a6",
          "sha256": "1579bc12925a8fb0e3b2aebd793767bd975628ac3916a7b95d6ab1d4df67282a",
          "sha1": "b8c9d94f6f8b7974043ee731ba6c6dbfb4ac3ebf",
          "md5": "7b2e096f36ea8b53d8041ec27bcb0ddf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.15.aar",
          "url": "azure_speech_release-0.0.15.aar",
          "size": 8356,
          "sha512": "c9dc1c4a606655d1145a257752ed21f919eb352bfb222c1c7dd1f038792eb84c447134e1ccb382059edac001b280260ba6fdb8fc13fce27546edbec0814033a6",
          "sha256": "1579bc12925a8fb0e3b2aebd793767bd975628ac3916a7b95d6ab1d4df67282a",
          "sha1": "b8c9d94f6f8b7974043ee731ba6c6dbfb4ac3ebf",
          "md5": "7b2e096f36ea8b53d8041ec27bcb0ddf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-0.0.15-sources.jar",
          "url": "azure_speech_release-0.0.15-sources.jar",
          "size": 3126,
          "sha512": "c5fa482378fdd5f590f01c09bad0bf0a1e1027b3b1099efbb4c7c0383bf25e94efc4661b47f42f56bffa83fa69035684e8540237d8f321807ea8c82b7ef8e7bf",
          "sha256": "dbc48cfeddc8a77360a235294ce5a1e5b33ea0e8f58d014a36f47a444801bc4c",
          "sha1": "472e764be030c1f6f0ed99b7d9a68b18c1963915",
          "md5": "184592d26c85753e0c119f324542f14b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-0.0.15-javadoc.jar",
          "url": "azure_speech_release-0.0.15-javadoc.jar",
          "size": 262206,
          "sha512": "7cb2533fd43e14c27827f75a509f7bdcac180358430108526622320d18f2b617499ccfbaa1cc998ccec264ea0482eb3622aca27081be431575e68fb65b23f62c",
          "sha256": "68c35e598f36c0807fb841df2afdbc0878f9903ee9abd93b3f358c42f053effa",
          "sha1": "aa1a6c9d4cbc04cc851e9cd3a379d10b6bdda7ab",
          "md5": "26147700623229544848545180724ea9"
        }
      ]
    }
  ]
}
