{
  "formatVersion": "1.1",
  "component": {
    "group": "com.actions.actres",
    "module": "actres_release",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "actres_release-2.0.aar",
          "url": "actres_release-2.0.aar",
          "size": 1260661,
          "sha512": "a776a02c85b29260490636e4478ccec68f678e9d492fa8b7bf3f74983ed4fe0c13269fd9b19d429b858531ad30f84d90460bcb03248d603ca432b983829d1367",
          "sha256": "353b88b72fd4f25b2c7371c23647678be8f6be00f7844977f73688cbc1c441b9",
          "sha1": "49e1b5b978b17a02c4eff4ba9817624dc75c5855",
          "md5": "06775bb712c4045a9a9f906fed10fcf9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "actres_release-2.0.aar",
          "url": "actres_release-2.0.aar",
          "size": 1260661,
          "sha512": "a776a02c85b29260490636e4478ccec68f678e9d492fa8b7bf3f74983ed4fe0c13269fd9b19d429b858531ad30f84d90460bcb03248d603ca432b983829d1367",
          "sha256": "353b88b72fd4f25b2c7371c23647678be8f6be00f7844977f73688cbc1c441b9",
          "sha1": "49e1b5b978b17a02c4eff4ba9817624dc75c5855",
          "md5": "06775bb712c4045a9a9f906fed10fcf9"
        }
      ]
    }
  ]
}
