{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-5.0.aar",
          "url": "path_provider_android_release-5.0.aar",
          "size": 12286,
          "sha512": "8732adb1ff74a73c167b137f5f296cde7f7f05b8b49b69599b2e20cf8954188d37202a47d2340fe3af0cb8f4801ac712de2fbb8446b33dc9d9dbb22c4c0eebc0",
          "sha256": "0fb6a737495b82b749689740cdc3faf7172dcbdc04cc122250063c5e16ccaf03",
          "sha1": "24801e9908b187c254381a1186e9f396df6b4ee6",
          "md5": "1315151190dbd428a6df5757c65df600"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-5.0.aar",
          "url": "path_provider_android_release-5.0.aar",
          "size": 12286,
          "sha512": "8732adb1ff74a73c167b137f5f296cde7f7f05b8b49b69599b2e20cf8954188d37202a47d2340fe3af0cb8f4801ac712de2fbb8446b33dc9d9dbb22c4c0eebc0",
          "sha256": "0fb6a737495b82b749689740cdc3faf7172dcbdc04cc122250063c5e16ccaf03",
          "sha1": "24801e9908b187c254381a1186e9f396df6b4ee6",
          "md5": "1315151190dbd428a6df5757c65df600"
        }
      ]
    }
  ]
}
