{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.33.aar",
          "url": "path_provider_android_release-0.0.33.aar",
          "size": 10347,
          "sha512": "5bbeeb17d2629753c93208965e80aa883ceea5d10c038c637fba208f037da74e32da0503e698aadda74aafe58ff2c91bcd459def512b13fa410ff9ff50619349",
          "sha256": "1c4a04ceebfc108e36907f514101fc21bcf14641b139ab09fa542947d339e49f",
          "sha1": "00f50fe45dabc06fa1705eff3cda976b445d2a48",
          "md5": "229bf13ebbd79af8ebc110a2d4daafbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.0.33.aar",
          "url": "path_provider_android_release-0.0.33.aar",
          "size": 10347,
          "sha512": "5bbeeb17d2629753c93208965e80aa883ceea5d10c038c637fba208f037da74e32da0503e698aadda74aafe58ff2c91bcd459def512b13fa410ff9ff50619349",
          "sha256": "1c4a04ceebfc108e36907f514101fc21bcf14641b139ab09fa542947d339e49f",
          "sha1": "00f50fe45dabc06fa1705eff3cda976b445d2a48",
          "md5": "229bf13ebbd79af8ebc110a2d4daafbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.33-sources.jar",
          "url": "path_provider_android_release-0.0.33-sources.jar",
          "size": 4121,
          "sha512": "98abfe49b0c49012cf74c573e26b0af84ff0b734f9b13ef74b5ee09b3731a8f699a41cbad0060a6f53788a35b595f6cea8b6d24a9b28fc28c55faf578ea78335",
          "sha256": "95e5edc3e2309e7fe549d0d67b05848a141eb5ea996c7e68ce2990e32191cb46",
          "sha1": "e0c3107497e5fa098fb6a873e214796778aee5d7",
          "md5": "6fb2208a851ccf1b24b54473fb99bc03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.0.33-javadoc.jar",
          "url": "path_provider_android_release-0.0.33-javadoc.jar",
          "size": 294230,
          "sha512": "6a2b9041795ad6b13dd3d71f822ffefa6cfbace321cfd7b7f905d6a85c41cf170f56f64230532e28b38a3295334a87b104a6a5a898ba20cc0d65efe8c5ecaf54",
          "sha256": "f7891c7eea3c4b447a40c143f04e850984507d74384c6725c3a35e8cd85378d3",
          "sha1": "f4abd30e1bb7df1d59357a2db23164c62c21f59d",
          "md5": "b19994f7e3a6d13c4f68f507542692fe"
        }
      ]
    }
  ]
}
