{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boskokg.flutter_blue_plus",
    "module": "flutter_blue_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_debug-1.0.aar",
          "url": "flutter_blue_plus_debug-1.0.aar",
          "size": 214438,
          "sha512": "84f7dff70eff135cdb27789681d3a4e37e2c944c8236424dd9d1dd03131ff7fbf0fab477e76d60353adc18014de7a005285849625285d055823c064772099257",
          "sha256": "0fff50fe825db7e62bf26d5a6c7b0312280427d50fbe7a22e718e8dbf845e32b",
          "sha1": "a8d39feeff2206e3e3560975ce0271c296738213",
          "md5": "084db08c46095164d8121d5e576c6751"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_debug-1.0.aar",
          "url": "flutter_blue_plus_debug-1.0.aar",
          "size": 214438,
          "sha512": "84f7dff70eff135cdb27789681d3a4e37e2c944c8236424dd9d1dd03131ff7fbf0fab477e76d60353adc18014de7a005285849625285d055823c064772099257",
          "sha256": "0fff50fe825db7e62bf26d5a6c7b0312280427d50fbe7a22e718e8dbf845e32b",
          "sha1": "a8d39feeff2206e3e3560975ce0271c296738213",
          "md5": "084db08c46095164d8121d5e576c6751"
        }
      ]
    }
  ]
}
