{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.1.aar",
          "url": "azure_speech_release-10.1.aar",
          "size": 9242,
          "sha512": "3ebcf0b5143ed8c1d2753f340578014c59b955e8ead97c487bc609f4c899d899324a0130ba91b257925e1a83d474f4d6c7eacb0d0ca0f8f538f323e63a8ccf38",
          "sha256": "e895d517a3accceae43741cec376d3d6e05108e7044541035e00c430b04ff04b",
          "sha1": "fe1e17267f1afdadc334e41dc9e299c6acadcd9e",
          "md5": "8c352e838280c3200d69f06d6337ee8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.1.aar",
          "url": "azure_speech_release-10.1.aar",
          "size": 9242,
          "sha512": "3ebcf0b5143ed8c1d2753f340578014c59b955e8ead97c487bc609f4c899d899324a0130ba91b257925e1a83d474f4d6c7eacb0d0ca0f8f538f323e63a8ccf38",
          "sha256": "e895d517a3accceae43741cec376d3d6e05108e7044541035e00c430b04ff04b",
          "sha1": "fe1e17267f1afdadc334e41dc9e299c6acadcd9e",
          "md5": "8c352e838280c3200d69f06d6337ee8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.1-sources.jar",
          "url": "azure_speech_release-10.1-sources.jar",
          "size": 3548,
          "sha512": "4e8caa7b8334ed04a5cc9bb08edff17f887e65f08d5297074ece1239a40ab237b7ccaf0fb9938764cc459fd77946331d595d3fd434baadd5c4d3209a7881cf7f",
          "sha256": "d5a003e71641c56cf59a78a0c9472fcbc0bcd7cd1ee9b20529220113d844135e",
          "sha1": "c026a9dcdf5d1e6073a71383730e7755402adf1a",
          "md5": "2505c3c50da646cb727dd156cdf121fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.1-javadoc.jar",
          "url": "azure_speech_release-10.1-javadoc.jar",
          "size": 262202,
          "sha512": "af4fdd773b2c3231399faa4ed991bc0c03dfb16bbbf3b4b8d15351aafce80277d7c3b2c20d37509640ceeeee512572c0483e86de6cb5393f126d09395052c62c",
          "sha256": "d2fb579ae89f7293220f404d9c0b83d341cb38b976369ff9a67c02bae02018cd",
          "sha1": "12b60682c2c8812b8356dbc499a02921a7312539",
          "md5": "1a7879ccbf90faeda405ff4204fe5a8a"
        }
      ]
    }
  ]
}
