{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-8.0.aar",
          "url": "device_calendar_release-8.0.aar",
          "size": 84595,
          "sha512": "88a5d92d004fbd3cd0cec0171149663d5a7c730b2af0fbf4a2298b5b3813ca98d922ea85750eeda2ee272a1db032f2a7d9789179592c8ddcc6bf37670e205035",
          "sha256": "6f5da391f8125ac91adc872ae0e805e5cc0197bb3538f56701d4549df458d5e6",
          "sha1": "1539d7e9848917e2cd4aa387a06196cf3fc2a472",
          "md5": "db261635b70bad12e3de51967c67ad9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-8.0.aar",
          "url": "device_calendar_release-8.0.aar",
          "size": 84595,
          "sha512": "88a5d92d004fbd3cd0cec0171149663d5a7c730b2af0fbf4a2298b5b3813ca98d922ea85750eeda2ee272a1db032f2a7d9789179592c8ddcc6bf37670e205035",
          "sha256": "6f5da391f8125ac91adc872ae0e805e5cc0197bb3538f56701d4549df458d5e6",
          "sha1": "1539d7e9848917e2cd4aa387a06196cf3fc2a472",
          "md5": "db261635b70bad12e3de51967c67ad9e"
        }
      ]
    }
  ]
}
