{
  "formatVersion": "1.1",
  "component": {
    "group": "com.creek.creek_gnss_algorithm",
    "module": "creek_gnss_algorithm_release",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_gnss_algorithm_release-0.0.21.aar",
          "url": "creek_gnss_algorithm_release-0.0.21.aar",
          "size": 32306,
          "sha512": "a0751c75339b438f2c8c0e66fc0d9fbd59650d00a982f53e52fcf2240d5f3e6999eba8fb39c46751b1c8434b14db0d88560305e4a2c80c373fdbb8b9f6e15043",
          "sha256": "ed163718623bc9317bb2b474c6e42d36541c458a38cd1c122a38e28b3d25226e",
          "sha1": "daff46fac0313fbb3b9d63d5dc2576a10526f984",
          "md5": "93af288cb263415e5ccb1ed6fa36efe3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_gnss_algorithm_release-0.0.21.aar",
          "url": "creek_gnss_algorithm_release-0.0.21.aar",
          "size": 32306,
          "sha512": "a0751c75339b438f2c8c0e66fc0d9fbd59650d00a982f53e52fcf2240d5f3e6999eba8fb39c46751b1c8434b14db0d88560305e4a2c80c373fdbb8b9f6e15043",
          "sha256": "ed163718623bc9317bb2b474c6e42d36541c458a38cd1c122a38e28b3d25226e",
          "sha1": "daff46fac0313fbb3b9d63d5dc2576a10526f984",
          "md5": "93af288cb263415e5ccb1ed6fa36efe3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_gnss_algorithm_release-0.0.21-sources.jar",
          "url": "creek_gnss_algorithm_release-0.0.21-sources.jar",
          "size": 1930,
          "sha512": "b4f1b4b26a30e0ce823820a76c3a15c6bc63209fdc9b2158cc813432faac13b4706b40bf960941682913da453dcad7bd528a7355334942aa20db137dc557cbeb",
          "sha256": "c058a6d79ccb1c04307ea00ad96614cff098555bcb4dabda264d10eecad821a7",
          "sha1": "63ca2e291998310cbcbf8c02f99b20348524b86e",
          "md5": "bfa59871906a5bb65fbb6b67a4953303"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_gnss_algorithm_release-0.0.21-javadoc.jar",
          "url": "creek_gnss_algorithm_release-0.0.21-javadoc.jar",
          "size": 260684,
          "sha512": "eb05cd554b24c6bcdac0b5c90ae756f9a652df032460b5a313d1d87c5454e8b40f6d9bb51e087df838f2d6203a2ccadebeda5ad75830398782b36da34ad3da94",
          "sha256": "d57a4f1b4f97a9bd456ed9c4c392432a1494ad9b72f5451f579c97f3c8133d0d",
          "sha1": "7b58cf7f1e92739dd860f3ab6edf6e093a39a9e4",
          "md5": "0d3890ec145a1f262a8d385a8b770131"
        }
      ]
    }
  ]
}
