{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 26233,
          "sha512": "0818cc7d9f0ae35f6c33ed63c2da9b237129eb8fd873e8b4bea40a36888dc696e73bbab05bc26b7829b17abc23e98d7aa3cc0e5b4aef82e1160cbbd11c58fbc5",
          "sha256": "f1365ba4feb345fcb5c0cdcf8d3ca006c2009e0c44db8a94bd416c7ae6995621",
          "sha1": "7869f04017694ce4319cd0642c65dd514366f5be",
          "md5": "1e6a9886ffe72fb60e41753016305489"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 26233,
          "sha512": "0818cc7d9f0ae35f6c33ed63c2da9b237129eb8fd873e8b4bea40a36888dc696e73bbab05bc26b7829b17abc23e98d7aa3cc0e5b4aef82e1160cbbd11c58fbc5",
          "sha256": "f1365ba4feb345fcb5c0cdcf8d3ca006c2009e0c44db8a94bd416c7ae6995621",
          "sha1": "7869f04017694ce4319cd0642c65dd514366f5be",
          "md5": "1e6a9886ffe72fb60e41753016305489"
        }
      ]
    }
  ]
}
