{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-4.9.aar",
          "url": "creek_blue_manage_release-4.9.aar",
          "size": 18787,
          "sha512": "98eb36583f41b237ea8c60273cae574f2f20512262b7cedb3490bc7c0914238b8bd912cd01bdfcc58a839bda464b09dfc8873fdd1fe1e048bac16d20773535a8",
          "sha256": "a81bf6ff081fbc098fca8b37d584d0e8c85b76bd4dde70ffbb7082309132414f",
          "sha1": "5b6f682ef8684eab9b78cb8c82982eec86a0f389",
          "md5": "ef62866774abca4680fe975410d7ada5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-4.9.aar",
          "url": "creek_blue_manage_release-4.9.aar",
          "size": 18787,
          "sha512": "98eb36583f41b237ea8c60273cae574f2f20512262b7cedb3490bc7c0914238b8bd912cd01bdfcc58a839bda464b09dfc8873fdd1fe1e048bac16d20773535a8",
          "sha256": "a81bf6ff081fbc098fca8b37d584d0e8c85b76bd4dde70ffbb7082309132414f",
          "sha1": "5b6f682ef8684eab9b78cb8c82982eec86a0f389",
          "md5": "ef62866774abca4680fe975410d7ada5"
        }
      ]
    }
  ]
}
