{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.3.aar",
          "url": "creek_blue_manage_release-0.0.3.aar",
          "size": 30348,
          "sha512": "86cfd91a86e5d453d56d8cbf311e95123ce2afe90d23dd6e3b3dedef229a3467b578f81c7c47ff92aecd0b1cdfe173e63178f011cc4d7d8948af6ac5303f32cc",
          "sha256": "ac4eadba30966a6d753b4a9dc426b9b856e07d867a17c04cc55d1f98f0769200",
          "sha1": "b88e2fc94937bb5d92d09000638ac2c5dafd743e",
          "md5": "6bd651e3cc27589daae21e4c61a37318"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-0.0.3.aar",
          "url": "creek_blue_manage_release-0.0.3.aar",
          "size": 30348,
          "sha512": "86cfd91a86e5d453d56d8cbf311e95123ce2afe90d23dd6e3b3dedef229a3467b578f81c7c47ff92aecd0b1cdfe173e63178f011cc4d7d8948af6ac5303f32cc",
          "sha256": "ac4eadba30966a6d753b4a9dc426b9b856e07d867a17c04cc55d1f98f0769200",
          "sha1": "b88e2fc94937bb5d92d09000638ac2c5dafd743e",
          "md5": "6bd651e3cc27589daae21e4c61a37318"
        }
      ]
    }
  ]
}
