{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.4.aar",
          "url": "sqflite_release-0.0.4.aar",
          "size": 43424,
          "sha512": "b7bbbec288b263ec89222f04e55ae94349786d1e59fb7269d2e6110891aaa190b0aaa711bfa818cc695f03addbe2891f1034bc8e193bd627cb724906e74a58ad",
          "sha256": "8d62e61570339fc95cd2626a8a808a56a884ab2ac616940a0e48230c63d5b21b",
          "sha1": "9e3386c7c55b7c362179c9693e383523bf2540ac",
          "md5": "19d667639dd97e142806f555bf5f0b37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.4.aar",
          "url": "sqflite_release-0.0.4.aar",
          "size": 43424,
          "sha512": "b7bbbec288b263ec89222f04e55ae94349786d1e59fb7269d2e6110891aaa190b0aaa711bfa818cc695f03addbe2891f1034bc8e193bd627cb724906e74a58ad",
          "sha256": "8d62e61570339fc95cd2626a8a808a56a884ab2ac616940a0e48230c63d5b21b",
          "sha1": "9e3386c7c55b7c362179c9693e383523bf2540ac",
          "md5": "19d667639dd97e142806f555bf5f0b37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.4-sources.jar",
          "url": "sqflite_release-0.0.4-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.4-javadoc.jar",
          "url": "sqflite_release-0.0.4-javadoc.jar",
          "size": 341658,
          "sha512": "4c3a1fbb4c02295c72e1c8ea7e69816349760e00ecea9b31aab9ffb3ef599b28bac1f69c963f3a2d405faa5af6cb67c3d4c90675ea8c117f60c82a0dfeaca4fa",
          "sha256": "a68a8c7af4b893764ef586258b16ab6a8227826cfbfd1dbe09bc5fd8eaf790e8",
          "sha1": "cd065abb9ad548797907f117591dd0c74012170c",
          "md5": "6b154d32c20015ca450e102d6cbb1d8e"
        }
      ]
    }
  ]
}
