{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "creek_ffmpeg_kit_flutter_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-0.0.1.aar",
          "url": "creek_ffmpeg_kit_flutter_release-0.0.1.aar",
          "size": 28915,
          "sha512": "90f922b4eb80512736a0ce2950772f20d00ee31d39ec897e1bf170b24bf34152b7c065ba25195c0198806a348ab0eb4b06f3e8e06e9926cbd188f5a8bd828c1b",
          "sha256": "b942b82c5a585aa865bee62318af186b6e0d840fa6b930d0311c4f1031f76f4b",
          "sha1": "6d6798bf553562d2db3df634e285e40863df4b6b",
          "md5": "47d60b3b536d57927dc794be50c854f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "arthenica",
          "module": "creek-ffmpeg-kit-https",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-0.0.1.aar",
          "url": "creek_ffmpeg_kit_flutter_release-0.0.1.aar",
          "size": 28915,
          "sha512": "90f922b4eb80512736a0ce2950772f20d00ee31d39ec897e1bf170b24bf34152b7c065ba25195c0198806a348ab0eb4b06f3e8e06e9926cbd188f5a8bd828c1b",
          "sha256": "b942b82c5a585aa865bee62318af186b6e0d840fa6b930d0311c4f1031f76f4b",
          "sha1": "6d6798bf553562d2db3df634e285e40863df4b6b",
          "md5": "47d60b3b536d57927dc794be50c854f2"
        }
      ]
    }
  ]
}
