{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-2.6.aar",
          "url": "sbc_release-2.6.aar",
          "size": 73285,
          "sha512": "14bb709e757217a7715b89e2a7d434b3d059a011dfed9fa3f06f04beca67f74cfd2d77f3f623f8cdf5b45b7e041a7570a673bd3c854a15e403dc1414a75326df",
          "sha256": "6ce5019d41d7e3b425001c9944d2249f49bf841329ad6a7a4017c831219caa89",
          "sha1": "3762f05f5e83c601c6e6126d29c0bbf6e4184846",
          "md5": "289024095fa10b48ad663ba3cc10364d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-2.6.aar",
          "url": "sbc_release-2.6.aar",
          "size": 73285,
          "sha512": "14bb709e757217a7715b89e2a7d434b3d059a011dfed9fa3f06f04beca67f74cfd2d77f3f623f8cdf5b45b7e041a7570a673bd3c854a15e403dc1414a75326df",
          "sha256": "6ce5019d41d7e3b425001c9944d2249f49bf841329ad6a7a4017c831219caa89",
          "sha1": "3762f05f5e83c601c6e6126d29c0bbf6e4184846",
          "md5": "289024095fa10b48ad663ba3cc10364d"
        }
      ]
    }
  ]
}
