{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.lz4",
    "module": "lz4_release",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-0.0.22.aar",
          "url": "lz4_release-0.0.22.aar",
          "size": 140318,
          "sha512": "8db2bfc7d23c65501032ed7fa0270951bd7572ac00f17bef055e41e400fa1bb42f7a9fd4cbae575ca284178703d9ed12c541c4246ca943a923c552e8047ed427",
          "sha256": "78d23517a3c7f96390eb000be002ec0845d18069fa5f8f03722b4f16613b732e",
          "sha1": "4b7631c0aea6dbc593e463c8ed806e26d882d10d",
          "md5": "b83d2bec854ec32771f58d55ade0968e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-0.0.22.aar",
          "url": "lz4_release-0.0.22.aar",
          "size": 140318,
          "sha512": "8db2bfc7d23c65501032ed7fa0270951bd7572ac00f17bef055e41e400fa1bb42f7a9fd4cbae575ca284178703d9ed12c541c4246ca943a923c552e8047ed427",
          "sha256": "78d23517a3c7f96390eb000be002ec0845d18069fa5f8f03722b4f16613b732e",
          "sha1": "4b7631c0aea6dbc593e463c8ed806e26d882d10d",
          "md5": "b83d2bec854ec32771f58d55ade0968e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lz4_release-0.0.22-sources.jar",
          "url": "lz4_release-0.0.22-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lz4_release-0.0.22-javadoc.jar",
          "url": "lz4_release-0.0.22-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
