{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "creek_ffmpeg_kit_flutter_release",
    "version": "10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-10.2.aar",
          "url": "creek_ffmpeg_kit_flutter_release-10.2.aar",
          "size": 26717,
          "sha512": "89aa4af268df77720607dab2a94c39cb346a48381ba60bd9220e28935c091554cb71d86e4de9e70fe04dc37604594813c209e4866add9db4d2e2c946fddd47ff",
          "sha256": "c2def6d3b73f1a215e37c8b207091445368bd4c702c8f8538078ddc1f5ce8c22",
          "sha1": "538c9a84864e6deebfeea510b1b1d226b46c80d4",
          "md5": "8440887f5164cf1091396641243bd301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "arthenica",
          "module": "creek-ffmpeg-kit-https",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-10.2.aar",
          "url": "creek_ffmpeg_kit_flutter_release-10.2.aar",
          "size": 26717,
          "sha512": "89aa4af268df77720607dab2a94c39cb346a48381ba60bd9220e28935c091554cb71d86e4de9e70fe04dc37604594813c209e4866add9db4d2e2c946fddd47ff",
          "sha256": "c2def6d3b73f1a215e37c8b207091445368bd4c702c8f8538078ddc1f5ce8c22",
          "sha1": "538c9a84864e6deebfeea510b1b1d226b46c80d4",
          "md5": "8440887f5164cf1091396641243bd301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-10.2-sources.jar",
          "url": "creek_ffmpeg_kit_flutter_release-10.2-sources.jar",
          "size": 14776,
          "sha512": "40c98156259926efc4c41bef55667936c2a132d961444653c60f565ece2e58aebc34e2aef5086b83fd17632ad589febff57f2e35df7ec2b8021d180bab809d0e",
          "sha256": "b422ae0e9f2db04414511b88e1c5bc4f431edf05110fdf641ac9a67958d0f7ad",
          "sha1": "19af9e7fc11f98350e731b4aa3baa286a5796815",
          "md5": "39fcc732a4d22bd1834ee499ef54f45d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_ffmpeg_kit_flutter_release-10.2-javadoc.jar",
          "url": "creek_ffmpeg_kit_flutter_release-10.2-javadoc.jar",
          "size": 284548,
          "sha512": "4297ab5180dad31888e463d598291e862ac64f5c1df531f41d524f03b725f247b9dede845ced3c1fbcb89a5be3a93e3abc9d3e56c6510be12a92e6ac48b96bc7",
          "sha256": "4404fdf825caefdadca89a3b15468a33a0b2ef603bbf25be2dba94094b87cad1",
          "sha1": "067b7ee1744d6c7d48c469f6e07160553410f8a0",
          "md5": "0383d5865212b86326d58ef374c71200"
        }
      ]
    }
  ]
}
