{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.image_clipper",
    "module": "image_clipper_release",
    "version": "9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_clipper_release-9.4.aar",
          "url": "image_clipper_release-9.4.aar",
          "size": 4682,
          "sha512": "2589309a1a4e219c4f1150ec98978b8cc41270ca64ec89dfb9a388a31a7657cdf8dee0de6c786af421da044e0d972b99a9e98a34725bf76a907d6523feba22b5",
          "sha256": "08eec7057a71acbe91d6aed4160112a04a0b8546e74b68bbf7e54cfff42497c2",
          "sha1": "dd1dd9e3b16f69bff4db7ff1e12a7db81b9a7389",
          "md5": "07325f41afc1c41dd071e14e3393b613"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_clipper_release-9.4.aar",
          "url": "image_clipper_release-9.4.aar",
          "size": 4682,
          "sha512": "2589309a1a4e219c4f1150ec98978b8cc41270ca64ec89dfb9a388a31a7657cdf8dee0de6c786af421da044e0d972b99a9e98a34725bf76a907d6523feba22b5",
          "sha256": "08eec7057a71acbe91d6aed4160112a04a0b8546e74b68bbf7e54cfff42497c2",
          "sha1": "dd1dd9e3b16f69bff4db7ff1e12a7db81b9a7389",
          "md5": "07325f41afc1c41dd071e14e3393b613"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_clipper_release-9.4-sources.jar",
          "url": "image_clipper_release-9.4-sources.jar",
          "size": 2090,
          "sha512": "49a3d855e5adb04581fc58ac9edb4eefae04d9d5087c1f7acf55558069ef19aeb173055f11ed46c983fa88e900ad0f2e41bb5c7fde7ffc07f23c7c4d04c442ff",
          "sha256": "d90937921945ff45bd0e060ab98b28237b0305883d241a92e34e6959c12b279a",
          "sha1": "cae6d4ec31fbbb4a9b5b53ef98c1178dfa2ea085",
          "md5": "b2ab330d3f15077d302f465949bacac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_clipper_release-9.4-javadoc.jar",
          "url": "image_clipper_release-9.4-javadoc.jar",
          "size": 262195,
          "sha512": "88b0e1bd4446161c9e041f12262d2478f6e7420d98eff2667063d30f09f6185c0fac2521308c5277edd03da69dbd256f60f85ff092aec7bacaa6fe10aa9c7806",
          "sha256": "f99d1dc9fac35c91cbde336d3265f32f65377e34ddd7bb30fa22184430270e4b",
          "sha1": "98550ec93eaf307fa876bb5f4e54ab1aad5db128",
          "md5": "4241752c9a47dff79246a08c000f2326"
        }
      ]
    }
  ]
}
