{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-4.4.aar",
          "url": "sbc_release-4.4.aar",
          "size": 73285,
          "sha512": "4aa44443e98724e4f6f83935e705eb9654940414c62a6488058394073d0ca3c5fbb4ffe05c1173e2d0d3c581c86a81319069b196f84a77a4aa13e75852375f5a",
          "sha256": "31058410bc56f3b1524d7e29c98b4bd6db24cb3b0b56148b1de11de96ad1eaa7",
          "sha1": "9f2e1599d464e738b196360eb465434012d9a0d7",
          "md5": "d782e975a4bba04be73c60010d77e569"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-4.4.aar",
          "url": "sbc_release-4.4.aar",
          "size": 73285,
          "sha512": "4aa44443e98724e4f6f83935e705eb9654940414c62a6488058394073d0ca3c5fbb4ffe05c1173e2d0d3c581c86a81319069b196f84a77a4aa13e75852375f5a",
          "sha256": "31058410bc56f3b1524d7e29c98b4bd6db24cb3b0b56148b1de11de96ad1eaa7",
          "sha1": "9f2e1599d464e738b196360eb465434012d9a0d7",
          "md5": "d782e975a4bba04be73c60010d77e569"
        }
      ]
    }
  ]
}
