{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-4.4.aar",
          "url": "sbc_release-4.4.aar",
          "size": 73285,
          "sha512": "fc67b9bde59133fe5cb7b373f26a34792fe7052c99200668e5d52f9cb112a6964f9524d98a057ea5cbbbbe0375a3cec0e4954bfb1d4e237b732d20f6dd8ed6a7",
          "sha256": "69820f742e4f7c1a042c2e5998e8fbc90c5e2fd88b4c95a0808bfb05df3937e0",
          "sha1": "f2504d4e2855414d9795405b1fd5d2339dd10f44",
          "md5": "05a84b70c1f546f39ac4c5d6fa7d087e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-4.4.aar",
          "url": "sbc_release-4.4.aar",
          "size": 73285,
          "sha512": "fc67b9bde59133fe5cb7b373f26a34792fe7052c99200668e5d52f9cb112a6964f9524d98a057ea5cbbbbe0375a3cec0e4954bfb1d4e237b732d20f6dd8ed6a7",
          "sha256": "69820f742e4f7c1a042c2e5998e8fbc90c5e2fd88b4c95a0808bfb05df3937e0",
          "sha1": "f2504d4e2855414d9795405b1fd5d2339dd10f44",
          "md5": "05a84b70c1f546f39ac4c5d6fa7d087e"
        }
      ]
    }
  ]
}
