{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sdk",
    "module": "flutter_release",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "com.actions.actres",
          "module": "actres_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-4.9.aar",
          "url": "flutter_release-4.9.aar",
          "size": 8870881,
          "sha512": "d0ae68e1f31790fe0fe60766d52c216885e467d354cbee7ca925955e51572c4f202f9ba59117f3e83aa5ce62606d81ae565dc4dd6df587189d45c8c72f75d770",
          "sha256": "010ec26b1249f26607f32b03f39fe6ecc8d49b27843cfcfffc56c0e086beb952",
          "sha1": "c25b259c8643deee0a55967d40edb05866a6e959",
          "md5": "a15fcd5cb3758f6f8b4d7f7c4b51f799"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4"
          }
        },
        {
          "group": "com.actions.actres",
          "module": "actres_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.creek_blue_manage",
          "module": "creek_blue_manage_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.image_clipper",
          "module": "image_clipper_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-4.9.aar",
          "url": "flutter_release-4.9.aar",
          "size": 8870881,
          "sha512": "d0ae68e1f31790fe0fe60766d52c216885e467d354cbee7ca925955e51572c4f202f9ba59117f3e83aa5ce62606d81ae565dc4dd6df587189d45c8c72f75d770",
          "sha256": "010ec26b1249f26607f32b03f39fe6ecc8d49b27843cfcfffc56c0e086beb952",
          "sha1": "c25b259c8643deee0a55967d40edb05866a6e959",
          "md5": "a15fcd5cb3758f6f8b4d7f7c4b51f799"
        }
      ]
    }
  ]
}
