{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-9.9.aar",
          "url": "azure_speech_release-9.9.aar",
          "size": 9242,
          "sha512": "3ebcf0b5143ed8c1d2753f340578014c59b955e8ead97c487bc609f4c899d899324a0130ba91b257925e1a83d474f4d6c7eacb0d0ca0f8f538f323e63a8ccf38",
          "sha256": "e895d517a3accceae43741cec376d3d6e05108e7044541035e00c430b04ff04b",
          "sha1": "fe1e17267f1afdadc334e41dc9e299c6acadcd9e",
          "md5": "8c352e838280c3200d69f06d6337ee8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-9.9.aar",
          "url": "azure_speech_release-9.9.aar",
          "size": 9242,
          "sha512": "3ebcf0b5143ed8c1d2753f340578014c59b955e8ead97c487bc609f4c899d899324a0130ba91b257925e1a83d474f4d6c7eacb0d0ca0f8f538f323e63a8ccf38",
          "sha256": "e895d517a3accceae43741cec376d3d6e05108e7044541035e00c430b04ff04b",
          "sha1": "fe1e17267f1afdadc334e41dc9e299c6acadcd9e",
          "md5": "8c352e838280c3200d69f06d6337ee8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-9.9-sources.jar",
          "url": "azure_speech_release-9.9-sources.jar",
          "size": 3548,
          "sha512": "4e8caa7b8334ed04a5cc9bb08edff17f887e65f08d5297074ece1239a40ab237b7ccaf0fb9938764cc459fd77946331d595d3fd434baadd5c4d3209a7881cf7f",
          "sha256": "d5a003e71641c56cf59a78a0c9472fcbc0bcd7cd1ee9b20529220113d844135e",
          "sha1": "c026a9dcdf5d1e6073a71383730e7755402adf1a",
          "md5": "2505c3c50da646cb727dd156cdf121fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-9.9-javadoc.jar",
          "url": "azure_speech_release-9.9-javadoc.jar",
          "size": 262202,
          "sha512": "a26f0381d3bb5716bc87991c8989eac9075187c8ae8ee9873fae8dc3472a1b6bd8a8a48ff1517f15b6aa56aeb9b36de23b3dfd403e4fc6fcb32672aaa309a9fb",
          "sha256": "3e32325c934c9b403715d8833d6d6c0ba4d8758a5e8fcd2ec17ed7ee8d29e765",
          "sha1": "08303712c6142f79b1c6ef2a0ea52006b409dfd2",
          "md5": "f3a1c89441ed59245a108a46545ebed0"
        }
      ]
    }
  ]
}
