{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.5.aar",
          "url": "azure_speech_release-0.0.5.aar",
          "size": 12545,
          "sha512": "9cf2bc4ef531d56783d3bc584e73db1e4564baa3069a96d47e55dc470985eecbd428c9df9ca9414a05240df0e33ce43911eba08e749697c8695bffc789b068a4",
          "sha256": "32e4ce50a975e7705dcb9fc0f8476feb96c5c9bf8958ca007cea2381bb80af51",
          "sha1": "d93329c4c642585484649a647c6a9884169c1592",
          "md5": "917688f664a76d26ede56d4c51a5ce28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        },
        {
          "group": "arthenica",
          "module": "client-sdk",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "jakarta.xml.bind",
              "module": "jakarta.xml.bind-api"
            },
            {
              "group": "jakarta.activation",
              "module": "jakarta.activation-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-0.0.5.aar",
          "url": "azure_speech_release-0.0.5.aar",
          "size": 12545,
          "sha512": "9cf2bc4ef531d56783d3bc584e73db1e4564baa3069a96d47e55dc470985eecbd428c9df9ca9414a05240df0e33ce43911eba08e749697c8695bffc789b068a4",
          "sha256": "32e4ce50a975e7705dcb9fc0f8476feb96c5c9bf8958ca007cea2381bb80af51",
          "sha1": "d93329c4c642585484649a647c6a9884169c1592",
          "md5": "917688f664a76d26ede56d4c51a5ce28"
        }
      ]
    }
  ]
}
