{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_index_convert",
    "module": "creek_index_convert_release",
    "version": "10.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "creek_index_convert_release-10.4.aar",
          "url": "creek_index_convert_release-10.4.aar",
          "size": 2868636,
          "sha512": "c0c89dec2c4f05d2212906dfb28de82574904102e01476072166d5a73c2c36cea9fd976d22bc24cdfe8a4238a982a4694ba39f10726bdf788bfadbe255014a80",
          "sha256": "4c8881e4f132796e4b51a58b47099816468a0dd9e15390b02f2b8911681277ce",
          "sha1": "e65cbe30361d5b664a5c9cde21847ba5ad90ce7f",
          "md5": "b28a08286fb0633928873ca20ffb9426"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "creek_index_convert_release-10.4.aar",
          "url": "creek_index_convert_release-10.4.aar",
          "size": 2868636,
          "sha512": "c0c89dec2c4f05d2212906dfb28de82574904102e01476072166d5a73c2c36cea9fd976d22bc24cdfe8a4238a982a4694ba39f10726bdf788bfadbe255014a80",
          "sha256": "4c8881e4f132796e4b51a58b47099816468a0dd9e15390b02f2b8911681277ce",
          "sha1": "e65cbe30361d5b664a5c9cde21847ba5ad90ce7f",
          "md5": "b28a08286fb0633928873ca20ffb9426"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_index_convert_release-10.4-sources.jar",
          "url": "creek_index_convert_release-10.4-sources.jar",
          "size": 2108,
          "sha512": "f88fe6b5bbd14b8555d88edc585ed63b93d6d0399cddd2762de0005c4b411baa30ac9874503a9306b04b4f979ac71b1b12924f900e3d0556945d70328ca7c8c2",
          "sha256": "edf7a20354be4c8987d645aef5174c7c24cb36b7b427248425929f530b933beb",
          "sha1": "901e948db47ae84f8bc5ac58063b379fdae69f52",
          "md5": "8399bd8939a21ee9082b30a3163a1b5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_index_convert_release-10.4-javadoc.jar",
          "url": "creek_index_convert_release-10.4-javadoc.jar",
          "size": 266846,
          "sha512": "c47ff8734cb6e2a55b6c3947b9005bad59057a4b20f2e97c5adbf4e22b7abe076f03e936ef7934184b3a16767d515619bc2428d3e7cf26891d3bb75366b6a91e",
          "sha256": "2e0dbd9d94be5a0b95b678314365a30022826c29e773a85f3ef8f2aade6aa42e",
          "sha1": "611fcb867ea37de320b1093af8d719894022bf77",
          "md5": "4f0c589d18118975a86b649b641f547b"
        }
      ]
    }
  ]
}
