{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "10.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-10.7.aar",
          "url": "package_info_plus_release-10.7.aar",
          "size": 5765,
          "sha512": "1ad40f4fa78f0073aea6f63bf62bfc97866a536c62b87789dc4d3fa7545d82072408d3beb4c394d9f47efd6a91e51513d0a932ab45140a13014791ea1329d212",
          "sha256": "cb9d41e58f8ba2b465a5a46d19b0a7e51e598ddb74d678d66cc541e469278dee",
          "sha1": "b7665802eeb8890976bb5e97da8654368c1df5de",
          "md5": "503dabe3b2f7a843a99a636647080eb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-10.7.aar",
          "url": "package_info_plus_release-10.7.aar",
          "size": 5765,
          "sha512": "1ad40f4fa78f0073aea6f63bf62bfc97866a536c62b87789dc4d3fa7545d82072408d3beb4c394d9f47efd6a91e51513d0a932ab45140a13014791ea1329d212",
          "sha256": "cb9d41e58f8ba2b465a5a46d19b0a7e51e598ddb74d678d66cc541e469278dee",
          "sha1": "b7665802eeb8890976bb5e97da8654368c1df5de",
          "md5": "503dabe3b2f7a843a99a636647080eb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-10.7-sources.jar",
          "url": "package_info_plus_release-10.7-sources.jar",
          "size": 2626,
          "sha512": "d29752460899631baee24b502608ec59283d4227d7ad35b4fef67f668381b5e5a6d3beefdb30ecf7015fc9e274b202a0efee3ef8c488a9f7d914c89ce368fde7",
          "sha256": "60a4f6359d1000d36e515b035f0b9f07f2861ed2477ef28d1fed8b9e37466437",
          "sha1": "e02c3b77b67d0f8364bd68f442715888cff6e59c",
          "md5": "9664599475a97471a062a35def69698f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-10.7-javadoc.jar",
          "url": "package_info_plus_release-10.7-javadoc.jar",
          "size": 265025,
          "sha512": "062ac71e43be932b077419cbad080bd3674fb89644e4f03ed8e6c91f5eb4f038e4ccda2af8c135ac19d54639bcb08541597b07b8c1df28577a1ef40db09a221b",
          "sha256": "fef58fa60cbb5ddad78053b60b293542e16c57c292035dd221748eae0fb5e719",
          "sha1": "729cd9e5f53d51c0043c9d6c73712168462c88f5",
          "md5": "9cc2ded16cd5efa111674dcb03dc99ac"
        }
      ]
    }
  ]
}
