{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_silero_vad",
    "module": "flutter_silero_vad_release",
    "version": "8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_silero_vad_release-8.6.aar",
          "url": "flutter_silero_vad_release-8.6.aar",
          "size": 8304,
          "sha512": "94b8f9c9e89f7d7e73f9335ea8c76dfe85cedd9f0807b0a979088262e87933515d2595f7064427b92e05e3ce31ff2c37f84975b6b208340c622f444db2ec4fbb",
          "sha256": "ea553b94c5c7e5a8163a3b4f7be3809becc663be6ff8d07e4b1a7b0ff434cf79",
          "sha1": "82df95fb7c493298273fffb12c93c0cb4f09857f",
          "md5": "2146095b0dda4e25d44b7dbcb5379f49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.onnxruntime",
          "module": "onnxruntime-android",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_silero_vad_release-8.6.aar",
          "url": "flutter_silero_vad_release-8.6.aar",
          "size": 8304,
          "sha512": "94b8f9c9e89f7d7e73f9335ea8c76dfe85cedd9f0807b0a979088262e87933515d2595f7064427b92e05e3ce31ff2c37f84975b6b208340c622f444db2ec4fbb",
          "sha256": "ea553b94c5c7e5a8163a3b4f7be3809becc663be6ff8d07e4b1a7b0ff434cf79",
          "sha1": "82df95fb7c493298273fffb12c93c0cb4f09857f",
          "md5": "2146095b0dda4e25d44b7dbcb5379f49"
        }
      ]
    }
  ]
}
