{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.15.aar",
          "url": "sqflite_android_release-0.0.15.aar",
          "size": 43114,
          "sha512": "d503f9bfda65979de31a2fae5f8f09ba4c0dffc2e4b103bafed743ad856f6fe846942769cfdfd1a6b7b002a547ad66254c23079af4e8761a3644c8c1db9ae130",
          "sha256": "9853dd219a077ace534dd5baca1a95ba8c4472db8a138054784c5625cd97dfe0",
          "sha1": "dc898fa37aef3652ebae2d18055ae54079786cdc",
          "md5": "abc510276235f235e95d5194735e8ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.15.aar",
          "url": "sqflite_android_release-0.0.15.aar",
          "size": 43114,
          "sha512": "d503f9bfda65979de31a2fae5f8f09ba4c0dffc2e4b103bafed743ad856f6fe846942769cfdfd1a6b7b002a547ad66254c23079af4e8761a3644c8c1db9ae130",
          "sha256": "9853dd219a077ace534dd5baca1a95ba8c4472db8a138054784c5625cd97dfe0",
          "sha1": "dc898fa37aef3652ebae2d18055ae54079786cdc",
          "md5": "abc510276235f235e95d5194735e8ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.15-sources.jar",
          "url": "sqflite_android_release-0.0.15-sources.jar",
          "size": 23748,
          "sha512": "79a18e8544303c175a5518d48dc0d23a617f6da7f5ddf699a7e94e154c1a221a1182d6b22363d34103e63d7e17decb835bdc2e3e92bfe0d08b1be7349ecc3847",
          "sha256": "7c4ef41dcd75693d0abddc88b3ba5c2fd30c31ee71155462d81055d982095868",
          "sha1": "8b554a039e5de13b3998bf9f2a1ef11cda40c2f1",
          "md5": "54e2ffa57d01fe69ac670dda7fb4b5f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.15-javadoc.jar",
          "url": "sqflite_android_release-0.0.15-javadoc.jar",
          "size": 339899,
          "sha512": "db58e5ab141fa1c393db60e660b56ba32d2a159b47ce18193c1b438a9b953dd15471d4789bb8d0db65a9bb7d9b562d5a8f37fda8e14fab61c66c647c27d022b4",
          "sha256": "23c32b49f3722c17f0870851ea0c33b66fe3a8f2696467c43468caccb84d4a6f",
          "sha1": "408356a60a37a60101891fd8e658b42de21536c8",
          "md5": "6e5ae0c6f307d695bccd060847656ebe"
        }
      ]
    }
  ]
}
