{
  "formatVersion": "1.1",
  "component": {
    "group": "com.actions.actres",
    "module": "actres_release",
    "version": "2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "actres_release-2.6.aar",
          "url": "actres_release-2.6.aar",
          "size": 1260711,
          "sha512": "5abd10a30d6f5115ae86e9a2a62be8d2726f90fabbfead0be1596c135d0d280f860dbfc332b0394f335762041aa329e6886266bc32a45c2f9fe5a3570a1f1597",
          "sha256": "eab4a6a3e89275acadff789de124986797feeef695ce09dbcb6d48792f7c3a3b",
          "sha1": "23556a9c395536ec1bba8e2d9752d7c4b45edf92",
          "md5": "1465d3efaa65a57c58ecbebb690dc071"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "actres_release-2.6.aar",
          "url": "actres_release-2.6.aar",
          "size": 1260711,
          "sha512": "5abd10a30d6f5115ae86e9a2a62be8d2726f90fabbfead0be1596c135d0d280f860dbfc332b0394f335762041aa329e6886266bc32a45c2f9fe5a3570a1f1597",
          "sha256": "eab4a6a3e89275acadff789de124986797feeef695ce09dbcb6d48792f7c3a3b",
          "sha1": "23556a9c395536ec1bba8e2d9752d7c4b45edf92",
          "md5": "1465d3efaa65a57c58ecbebb690dc071"
        }
      ]
    }
  ]
}
