{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_sleep_stage_algorithm",
    "module": "creek_sleep_stage_algorithm_release",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.2.aar",
          "url": "creek_sleep_stage_algorithm_release-0.0.2.aar",
          "size": 23268,
          "sha512": "fadb5717e9c8b8ba19429b1b7e822b9fbaf511faaabac819a2ca0a63f133cf8e1c7160f3847c50af61e4e355dfa4da6e65712587ac9d089dc4d06e2221988afb",
          "sha256": "e02127a10f7558dd0ab9273155a778422f9490e7f7815fa006c7c82ece99e385",
          "sha1": "5a6f293bf175b54da83f8be9e01bb37d4a16d0b0",
          "md5": "ba1d6eb6d1da0470efb8b7a2f4d68bf8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "creek_sleep_stage_algorithm_release-0.0.2.aar",
          "url": "creek_sleep_stage_algorithm_release-0.0.2.aar",
          "size": 23268,
          "sha512": "fadb5717e9c8b8ba19429b1b7e822b9fbaf511faaabac819a2ca0a63f133cf8e1c7160f3847c50af61e4e355dfa4da6e65712587ac9d089dc4d06e2221988afb",
          "sha256": "e02127a10f7558dd0ab9273155a778422f9490e7f7815fa006c7c82ece99e385",
          "sha1": "5a6f293bf175b54da83f8be9e01bb37d4a16d0b0",
          "md5": "ba1d6eb6d1da0470efb8b7a2f4d68bf8"
        }
      ]
    }
  ]
}
