{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-7.1.aar",
          "url": "creek_blue_manage_release-7.1.aar",
          "size": 30366,
          "sha512": "ed94e392171db4cb5e9e00a4bc9277210f7cc85b907afae30ebf651bb7da0dec42e30e40e22b4f35012dc58ed947aa816c75f0eefd34ff59cebf7f743675a133",
          "sha256": "9cf9875810071cac1bdf1c7cc601f1cefeb37bf7ad7a9e476510d27adb93f46b",
          "sha1": "668e98273705f2ec6866149f10f6c36e1ffa5d04",
          "md5": "6a821c667f2386f855c7b46bfd7b047f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.builttoroam.devicecalendar",
          "module": "device_calendar_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "android_generated",
          "module": "creek_ffmpeg_kit_flutter_release",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-7.1.aar",
          "url": "creek_blue_manage_release-7.1.aar",
          "size": 30366,
          "sha512": "ed94e392171db4cb5e9e00a4bc9277210f7cc85b907afae30ebf651bb7da0dec42e30e40e22b4f35012dc58ed947aa816c75f0eefd34ff59cebf7f743675a133",
          "sha256": "9cf9875810071cac1bdf1c7cc601f1cefeb37bf7ad7a9e476510d27adb93f46b",
          "sha1": "668e98273705f2ec6866149f10f6c36e1ffa5d04",
          "md5": "6a821c667f2386f855c7b46bfd7b047f"
        }
      ]
    }
  ]
}
