{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.lz4",
    "module": "lz4_release",
    "version": "3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-3.3.aar",
          "url": "lz4_release-3.3.aar",
          "size": 142689,
          "sha512": "99a851ed170ee6c7e01030da20c71034d8862e72f483894a3e9db35fc2beda9e516d8f25ada842bbcb931413ed3d8798b065e5963d044fb8fd1dcd412c4a1046",
          "sha256": "d1445ba050acf7095003a157c3f2a2432b324925404c19c160a4647a284b9ee0",
          "sha1": "1dabe5fbaa39d0c300deaa134b634e0a977ccb14",
          "md5": "80c20f93bbb841fe2ae8721f734f9c03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "lz4_release-3.3.aar",
          "url": "lz4_release-3.3.aar",
          "size": 142689,
          "sha512": "99a851ed170ee6c7e01030da20c71034d8862e72f483894a3e9db35fc2beda9e516d8f25ada842bbcb931413ed3d8798b065e5963d044fb8fd1dcd412c4a1046",
          "sha256": "d1445ba050acf7095003a157c3f2a2432b324925404c19c160a4647a284b9ee0",
          "sha1": "1dabe5fbaa39d0c300deaa134b634e0a977ccb14",
          "md5": "80c20f93bbb841fe2ae8721f734f9c03"
        }
      ]
    }
  ]
}
