{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.5.aar",
          "url": "sqflite_release-0.0.5.aar",
          "size": 43424,
          "sha512": "b7bbbec288b263ec89222f04e55ae94349786d1e59fb7269d2e6110891aaa190b0aaa711bfa818cc695f03addbe2891f1034bc8e193bd627cb724906e74a58ad",
          "sha256": "8d62e61570339fc95cd2626a8a808a56a884ab2ac616940a0e48230c63d5b21b",
          "sha1": "9e3386c7c55b7c362179c9693e383523bf2540ac",
          "md5": "19d667639dd97e142806f555bf5f0b37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.5.aar",
          "url": "sqflite_release-0.0.5.aar",
          "size": 43424,
          "sha512": "b7bbbec288b263ec89222f04e55ae94349786d1e59fb7269d2e6110891aaa190b0aaa711bfa818cc695f03addbe2891f1034bc8e193bd627cb724906e74a58ad",
          "sha256": "8d62e61570339fc95cd2626a8a808a56a884ab2ac616940a0e48230c63d5b21b",
          "sha1": "9e3386c7c55b7c362179c9693e383523bf2540ac",
          "md5": "19d667639dd97e142806f555bf5f0b37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.5-sources.jar",
          "url": "sqflite_release-0.0.5-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.5-javadoc.jar",
          "url": "sqflite_release-0.0.5-javadoc.jar",
          "size": 341658,
          "sha512": "31f87c919f2cd98feda2d70fe6acd57c06bb33f915878c4dfb239967f641c17eb9a2b2c690c44b580ede63668fc9de61f5f27bc612c3b6c6296268b7bc4732d8",
          "sha256": "157d0b56dc93daad09a328aa8ce2901cba180465edccf40a1054ea24aff870bb",
          "sha1": "d783a646c4bae180c378fb67320bddff3743449c",
          "md5": "2b1650a94324c3c7100f1e03d674b578"
        }
      ]
    }
  ]
}
