{
  "formatVersion": "1.1",
  "component": {
    "group": "com.llfbandit.record",
    "module": "record_android_release",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "record_android_release-0.0.22.aar",
          "url": "record_android_release-0.0.22.aar",
          "size": 118306,
          "sha512": "debfe0f1cc8a118519c31cc4cefab0bfd60b8c9cfb965cbbaac54133036f4d9f1d8343f3591c4099aa174dceb6979aa91f99aaff1ee370866c10266c8839b923",
          "sha256": "f8d1157d5bbb534bdfa4a444b6924e745826e468467d9d06d0439083a8fafb89",
          "sha1": "2023198f723907ee8e48e4eed391146bc9736e01",
          "md5": "4b68faba4c86136c5d5fa1b25cda6aae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "record_android_release-0.0.22.aar",
          "url": "record_android_release-0.0.22.aar",
          "size": 118306,
          "sha512": "debfe0f1cc8a118519c31cc4cefab0bfd60b8c9cfb965cbbaac54133036f4d9f1d8343f3591c4099aa174dceb6979aa91f99aaff1ee370866c10266c8839b923",
          "sha256": "f8d1157d5bbb534bdfa4a444b6924e745826e468467d9d06d0439083a8fafb89",
          "sha1": "2023198f723907ee8e48e4eed391146bc9736e01",
          "md5": "4b68faba4c86136c5d5fa1b25cda6aae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "record_android_release-0.0.22-sources.jar",
          "url": "record_android_release-0.0.22-sources.jar",
          "size": 40616,
          "sha512": "239758d1a403c6cc595ab7629464716b749032e12c1ca3791f7a2e6677a7e69f37049956f5d998c6907a2e4c3acd971f99db44a42e1be042193cf0577b66b29d",
          "sha256": "8bc0914b614021a6bb9845e99196d26641af96cb1d9ab3920a4e0971ff9096d1",
          "sha1": "697d84ee8516e44174d9e5e3162f64f276c78322",
          "md5": "2c9d71d93b952786b47da00546cbcfee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "record_android_release-0.0.22-javadoc.jar",
          "url": "record_android_release-0.0.22-javadoc.jar",
          "size": 509559,
          "sha512": "8a220484b1d92bd72a5d91930a6f1d6ee9bf8d4a67e43aad2ddd5c560945b1ebac8341097ff5eb630995af6db3c4fe363b8fb4cf904fc27fec4c816a6987f4a3",
          "sha256": "c984ce6cf50c7345726c5cb7b4ae5f1df543f9f3b7a9875475ea55c2fe497e79",
          "sha1": "50ac7950a3f365f5dde83b696bc7ff6724b294a2",
          "md5": "fbf3265fc30a4961465fec7ec4af60f4"
        }
      ]
    }
  ]
}
