{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.14.aar",
          "url": "sqflite_android_release-0.0.14.aar",
          "size": 42986,
          "sha512": "a3b861d06f741b2e7802dd916929e16d1b3314f0624f860f66fd1dcfa506b7185919ae73dad0ca9dbfe8ab68554e19c581f7eedc18048ae8c3f06d12528037a2",
          "sha256": "d38c43fdecfd7aa76cf897a683af11041ae8b85f43374caa9fc022f7f634d5e0",
          "sha1": "fe0774cad4b4984c40b1918db7917e828675854d",
          "md5": "053b7ff958728c6431090189fc704d0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.0.14.aar",
          "url": "sqflite_android_release-0.0.14.aar",
          "size": 42986,
          "sha512": "a3b861d06f741b2e7802dd916929e16d1b3314f0624f860f66fd1dcfa506b7185919ae73dad0ca9dbfe8ab68554e19c581f7eedc18048ae8c3f06d12528037a2",
          "sha256": "d38c43fdecfd7aa76cf897a683af11041ae8b85f43374caa9fc022f7f634d5e0",
          "sha1": "fe0774cad4b4984c40b1918db7917e828675854d",
          "md5": "053b7ff958728c6431090189fc704d0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.14-sources.jar",
          "url": "sqflite_android_release-0.0.14-sources.jar",
          "size": 23748,
          "sha512": "79a18e8544303c175a5518d48dc0d23a617f6da7f5ddf699a7e94e154c1a221a1182d6b22363d34103e63d7e17decb835bdc2e3e92bfe0d08b1be7349ecc3847",
          "sha256": "7c4ef41dcd75693d0abddc88b3ba5c2fd30c31ee71155462d81055d982095868",
          "sha1": "8b554a039e5de13b3998bf9f2a1ef11cda40c2f1",
          "md5": "54e2ffa57d01fe69ac670dda7fb4b5f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.0.14-javadoc.jar",
          "url": "sqflite_android_release-0.0.14-javadoc.jar",
          "size": 339899,
          "sha512": "804333ee4e5509669d45079adc24897a5eb2cfff1ea5b72b2a3bfa652f1b22369313175b1710c5a584edffb980af1f494cedfd4913b6d2efabcb53774ce34eba",
          "sha256": "6b726a52b7c94c6806b75bc00e5bc43c6edcd26b708138baff6bc29a727181cf",
          "sha1": "caeafae6a174b9c2a457f3b40c396796f739b757",
          "md5": "4b1f979e962dd9bb2df60fc5072e8cad"
        }
      ]
    }
  ]
}
