{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.64.aar",
          "url": "permission_handler_android_release-0.0.64.aar",
          "size": 26560,
          "sha512": "caedb5215f1cb920be942e6348e2a78d58acb01251c7f4868536cbe435f84b3b92c57f153ead64a8861fe54476427fef584c0fa34fb2c557bf2d0b8311053f76",
          "sha256": "4249a7edcd7489c64a73e8b4553aaeca8864eef47a17bda142eb70b6f8555bfc",
          "sha1": "4c59027349565b5513bf0e1d03efeeefaa724cc8",
          "md5": "db7e217eed52c1aeb08eaa707bf7bce0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.64.aar",
          "url": "permission_handler_android_release-0.0.64.aar",
          "size": 26560,
          "sha512": "caedb5215f1cb920be942e6348e2a78d58acb01251c7f4868536cbe435f84b3b92c57f153ead64a8861fe54476427fef584c0fa34fb2c557bf2d0b8311053f76",
          "sha256": "4249a7edcd7489c64a73e8b4553aaeca8864eef47a17bda142eb70b6f8555bfc",
          "sha1": "4c59027349565b5513bf0e1d03efeeefaa724cc8",
          "md5": "db7e217eed52c1aeb08eaa707bf7bce0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.64-sources.jar",
          "url": "permission_handler_android_release-0.0.64-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.64-javadoc.jar",
          "url": "permission_handler_android_release-0.0.64-javadoc.jar",
          "size": 264581,
          "sha512": "f379852802963e42895a3a2c9fe8d662b3b460fd2aa5bf0cacb49aec9e2a581f940f5a8fe522fe0caeea5283e6a2c585b2111b5bddca87d83b879f14315fe660",
          "sha256": "b44a2afa27d0d37728490e90096b25ecbcc5cb554ee78d26ca122dca191e9935",
          "sha1": "57d8d104b5207c2803e1de775510782eb4cb953e",
          "md5": "c648e9b4028db37ec78b232ee4d07e67"
        }
      ]
    }
  ]
}
