{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.23.aar",
          "url": "device_calendar_release-0.0.23.aar",
          "size": 70890,
          "sha512": "6cb10d4fa7e2824ec9359990703b30673678f2c3b83f28fa586bfe559c7befd8d149f8cf57bb24591eaada6af1a4f111a23198d1a398101efd617e0bc983193c",
          "sha256": "bd6a23db6433cb0f530e8787d24256f1ed0555e6003adf3d419ffa3486402185",
          "sha1": "d162b1634f3d564b7ba6916a2b3cbed26760a933",
          "md5": "f246815d7eff0fd9d2d88424f525c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-0.0.23.aar",
          "url": "device_calendar_release-0.0.23.aar",
          "size": 70890,
          "sha512": "6cb10d4fa7e2824ec9359990703b30673678f2c3b83f28fa586bfe559c7befd8d149f8cf57bb24591eaada6af1a4f111a23198d1a398101efd617e0bc983193c",
          "sha256": "bd6a23db6433cb0f530e8787d24256f1ed0555e6003adf3d419ffa3486402185",
          "sha1": "d162b1634f3d564b7ba6916a2b3cbed26760a933",
          "md5": "f246815d7eff0fd9d2d88424f525c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-0.0.23-sources.jar",
          "url": "device_calendar_release-0.0.23-sources.jar",
          "size": 19259,
          "sha512": "596df879875dbeecd1171483bba32882cbf94115c8c1448185b993e296994006c7652e4315a994630107b6812bdd5cd1a1562c866d3c0dce284107f4409c2ab6",
          "sha256": "b873a00db27dcf44fb83ed111ce903da44f6dbdf95b5c0ba1c98f0ec56eca9e3",
          "sha1": "6f9e51b7f1534e2d360107cf836efc201ff41c23",
          "md5": "9c871bf2f63334dba398899b5e5ab6e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-0.0.23-javadoc.jar",
          "url": "device_calendar_release-0.0.23-javadoc.jar",
          "size": 367544,
          "sha512": "085a32fe0fc9e7fe1c885fea9fa3ab6ed762668d368f51f2de20e5377fe869167479f4850a05250a9314c94f6dfdf8e30b157ec4e3bc45cb59f897eba5bbff22",
          "sha256": "41f424805330b28fd423e1e41d07b905a331c73b0d7e280e08e406f8eccad0fb",
          "sha1": "0127d34bfd84d7dceb01e42364846cd5ccdbce36",
          "md5": "0b65fad79bc7cda02346b93fb4f736a5"
        }
      ]
    }
  ]
}
