{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-10.1.aar",
          "url": "sqflite_release-10.1.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-10.1.aar",
          "url": "sqflite_release-10.1.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-10.1-sources.jar",
          "url": "sqflite_release-10.1-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-10.1-javadoc.jar",
          "url": "sqflite_release-10.1-javadoc.jar",
          "size": 341639,
          "sha512": "b6f056b79f659ecbef0bad02bbea19b44cf568c1f4ff6c1b068407db22ebdf9e105c9c99b25ba0132f5c80a484d0ce9eb26ec50c85a0a68358826969a4b5cd76",
          "sha256": "bf37704841ab84a2337d3dfaf15e9e37001f8b9d20efb65042f22913c485a255",
          "sha1": "76f1711cbae4ea3e681b17020c4022b2aba15b13",
          "md5": "9fbf54c437fcc583eb410571a9d26219"
        }
      ]
    }
  ]
}
