{
  "formatVersion": "1.1",
  "component": {
    "group": "co.quis.flutter_contacts",
    "module": "flutter_contacts_release",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_contacts_release-0.0.22.aar",
          "url": "flutter_contacts_release-0.0.22.aar",
          "size": 131160,
          "sha512": "2f8dced86182c4a71747702c2116141f5e363c509f8d04537873c4ee49da8e244c797c8ad101ba8473b281e9994aab4ff135e342626bb91b7d630f855ce10ec9",
          "sha256": "6488cc11d931dafa9d96091583b8f8703a4a816885ec10b20409eb24f31776a9",
          "sha1": "802fe9e2a2a2305d7d262cd24cf1f3c3003e5418",
          "md5": "e255f3714c9fcf949d23dd61c10f543e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_contacts_release-0.0.22.aar",
          "url": "flutter_contacts_release-0.0.22.aar",
          "size": 131160,
          "sha512": "2f8dced86182c4a71747702c2116141f5e363c509f8d04537873c4ee49da8e244c797c8ad101ba8473b281e9994aab4ff135e342626bb91b7d630f855ce10ec9",
          "sha256": "6488cc11d931dafa9d96091583b8f8703a4a816885ec10b20409eb24f31776a9",
          "sha1": "802fe9e2a2a2305d7d262cd24cf1f3c3003e5418",
          "md5": "e255f3714c9fcf949d23dd61c10f543e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_contacts_release-0.0.22-sources.jar",
          "url": "flutter_contacts_release-0.0.22-sources.jar",
          "size": 20016,
          "sha512": "4120b9c59bfcf46bde5138a7bce63f945a61befe8d46d00a904948a866fc2e7a7d2c0a50d1ae2f6b4922cc8a689d0eb2b3647ec39bfba24ff905e306e9e6f459",
          "sha256": "d996d26da7d1958177f2788c55275619d472f8859efbc4e4d7dae141e97a0db6",
          "sha1": "eecd3daa5e7893e38a170c52092828c74df06b43",
          "md5": "30826daeeb89a1c08aa800fc8b4735d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_contacts_release-0.0.22-javadoc.jar",
          "url": "flutter_contacts_release-0.0.22-javadoc.jar",
          "size": 387004,
          "sha512": "29b6f3e0017d5b5ecd09a4cfc1578c9629af67e05f4075e8ed63067de291c835490167dc83720f00871c30c99eaf331432901765aba4c43a2de2cce4e9080beb",
          "sha256": "6eac120517a4ae9777528a124e5e01d917ef57715633fbbca19a38f40ff02217",
          "sha1": "f3da8ca01de54a35d5ed0ec30f5ce864fdf818ce",
          "md5": "5069557c4cd41b54058640aeb2896f54"
        }
      ]
    }
  ]
}
