{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-3.0.aar",
          "url": "sbc_release-3.0.aar",
          "size": 73286,
          "sha512": "a3f617c857471b960a2edc3db204c8de425da8379cf3a10b859d7e25dea340419624af2d9178e593b78be69ccb03ae9eca55f27a8df999b99e861c54500cb6a8",
          "sha256": "44f2e748d9eb805e67b213cba049a664684aaa87058c2ae055a6872cf065436a",
          "sha1": "2292c7cec7aa4f55b4ea042afabcd541dd05b827",
          "md5": "c3264deeda63ca0020b3c270cd73b987"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-3.0.aar",
          "url": "sbc_release-3.0.aar",
          "size": 73286,
          "sha512": "a3f617c857471b960a2edc3db204c8de425da8379cf3a10b859d7e25dea340419624af2d9178e593b78be69ccb03ae9eca55f27a8df999b99e861c54500cb6a8",
          "sha256": "44f2e748d9eb805e67b213cba049a664684aaa87058c2ae055a6872cf065436a",
          "sha1": "2292c7cec7aa4f55b4ea042afabcd541dd05b827",
          "md5": "c3264deeda63ca0020b3c270cd73b987"
        }
      ]
    }
  ]
}
