{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_profile-1.0.aar",
          "url": "creek_blue_manage_profile-1.0.aar",
          "size": 4673,
          "sha512": "39d70e538d7498fb5d789421f8adbef830f9cecfc30ef92743e38905a13773b55ccb9c56e55dc2db779b57a6b11552d96f4470ec919208bd906441aedac8375c",
          "sha256": "7dd45d18f8e3162bb4e5e1265b7f3044ec011d3f288a23c6211c53122c8ffe7f",
          "sha1": "46983ac4ecdae15171be497f2025fad45f70b296",
          "md5": "d0437d3cdc097d52737d03927ad69029"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_profile-1.0.aar",
          "url": "creek_blue_manage_profile-1.0.aar",
          "size": 4673,
          "sha512": "39d70e538d7498fb5d789421f8adbef830f9cecfc30ef92743e38905a13773b55ccb9c56e55dc2db779b57a6b11552d96f4470ec919208bd906441aedac8375c",
          "sha256": "7dd45d18f8e3162bb4e5e1265b7f3044ec011d3f288a23c6211c53122c8ffe7f",
          "sha1": "46983ac4ecdae15171be497f2025fad45f70b296",
          "md5": "d0437d3cdc097d52737d03927ad69029"
        }
      ]
    }
  ]
}
