{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.20.aar",
          "url": "sqflite_release-0.0.20.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.20.aar",
          "url": "sqflite_release-0.0.20.aar",
          "size": 43557,
          "sha512": "146b17eb92496010fe09ef32ffb9eecaabd45d2963b71f007beae0cf0873decc7b001a8d7c51cded8ac841360a568f3fa52be4cff6e74ace7e5d32cdd718559f",
          "sha256": "d08f00d79da8f8f4ecbaa00eaa53676374c15a0baf2884119d177f3c971e26eb",
          "sha1": "32f8037e7cfc8dd83d524ca3205c53c958df317f",
          "md5": "a3070b844347efc98cc49cf335066052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.20-sources.jar",
          "url": "sqflite_release-0.0.20-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_release-0.0.20-javadoc.jar",
          "url": "sqflite_release-0.0.20-javadoc.jar",
          "size": 341668,
          "sha512": "9ebbccfc4fa96ba9b64970fe5e2354450b337b91a0c62c1385cb44b88aef13e7b848a3bbf58d72093d980008ef7863758232f458cccf817051ca35471d6a4052",
          "sha256": "43ce2fbe92b88fc09dd066d2576b2a2b6d7785ff33cae35362f88b3c44441c9d",
          "sha1": "d535e2006497770a43cc44a0ae2874e8875f19ed",
          "md5": "06a935d58d1a4a25b3fbba742352157f"
        }
      ]
    }
  ]
}
