{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_index_convert",
    "module": "creek_index_convert_release",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_index_convert_release-0.0.22.aar",
          "url": "creek_index_convert_release-0.0.22.aar",
          "size": 2868632,
          "sha512": "ae3bc1bfc4a1fd481c8255c727464760530adc06a11c42a6445d2218b7c251a801466118609b6026975451e5e6f2601fee140aa09c933b84cdd4be7f54e81d9d",
          "sha256": "54e708bab68667639fe53e1e50d0b38059c6f890987145f23e6ed2edb697ab76",
          "sha1": "acfafba7643350e495d8b28effa9ebab5c6cfd26",
          "md5": "8f05a2dc624035ccd52e4fbf22c79576"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "creek_index_convert_release-0.0.22.aar",
          "url": "creek_index_convert_release-0.0.22.aar",
          "size": 2868632,
          "sha512": "ae3bc1bfc4a1fd481c8255c727464760530adc06a11c42a6445d2218b7c251a801466118609b6026975451e5e6f2601fee140aa09c933b84cdd4be7f54e81d9d",
          "sha256": "54e708bab68667639fe53e1e50d0b38059c6f890987145f23e6ed2edb697ab76",
          "sha1": "acfafba7643350e495d8b28effa9ebab5c6cfd26",
          "md5": "8f05a2dc624035ccd52e4fbf22c79576"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_index_convert_release-0.0.22-sources.jar",
          "url": "creek_index_convert_release-0.0.22-sources.jar",
          "size": 2108,
          "sha512": "f88fe6b5bbd14b8555d88edc585ed63b93d6d0399cddd2762de0005c4b411baa30ac9874503a9306b04b4f979ac71b1b12924f900e3d0556945d70328ca7c8c2",
          "sha256": "edf7a20354be4c8987d645aef5174c7c24cb36b7b427248425929f530b933beb",
          "sha1": "901e948db47ae84f8bc5ac58063b379fdae69f52",
          "md5": "8399bd8939a21ee9082b30a3163a1b5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "creek_index_convert_release-0.0.22-javadoc.jar",
          "url": "creek_index_convert_release-0.0.22-javadoc.jar",
          "size": 266850,
          "sha512": "870d20807705e6fabb4c0264b93422c772a625199d1585e3b82c9314f96ac56551075d22752096435dd2282a0d010f927d189e9fc829f40fa53c9b0641a7b04a",
          "sha256": "0b35a7e772f5b37817d89e541e6a6e14f67f4147bad5af653d7950128b146934",
          "sha1": "acb87401f42e8733c300e49027ccd2b1dd17c8cf",
          "md5": "e70c987c0204a21b415b7935d8cc0e57"
        }
      ]
    }
  ]
}
