{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-8.4.aar",
          "url": "azure_speech_release-8.4.aar",
          "size": 11244,
          "sha512": "65ea8e2928d477fd697d6f640ecd86d2c1f8125de59fc2c4a95afa6b2ab0c3d06fa44bb309cbcbfea327de0e4246606f8972ab54f5b22b4bad82f38cad94f0eb",
          "sha256": "38f151ff8ea41da4f99887a34b2d81c7b66a7f8e077fc413fae31ee4519485b9",
          "sha1": "d9cd5b5f5073e4047f26f2c8e882e39ffec089e8",
          "md5": "1ab6af716b5bbc9b5b04b40c3b0a97cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-8.4.aar",
          "url": "azure_speech_release-8.4.aar",
          "size": 11244,
          "sha512": "65ea8e2928d477fd697d6f640ecd86d2c1f8125de59fc2c4a95afa6b2ab0c3d06fa44bb309cbcbfea327de0e4246606f8972ab54f5b22b4bad82f38cad94f0eb",
          "sha256": "38f151ff8ea41da4f99887a34b2d81c7b66a7f8e077fc413fae31ee4519485b9",
          "sha1": "d9cd5b5f5073e4047f26f2c8e882e39ffec089e8",
          "md5": "1ab6af716b5bbc9b5b04b40c3b0a97cb"
        }
      ]
    }
  ]
}
