{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.image_clipper",
    "module": "image_clipper_release",
    "version": "10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_clipper_release-10.1.aar",
          "url": "image_clipper_release-10.1.aar",
          "size": 4682,
          "sha512": "2589309a1a4e219c4f1150ec98978b8cc41270ca64ec89dfb9a388a31a7657cdf8dee0de6c786af421da044e0d972b99a9e98a34725bf76a907d6523feba22b5",
          "sha256": "08eec7057a71acbe91d6aed4160112a04a0b8546e74b68bbf7e54cfff42497c2",
          "sha1": "dd1dd9e3b16f69bff4db7ff1e12a7db81b9a7389",
          "md5": "07325f41afc1c41dd071e14e3393b613"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_clipper_release-10.1.aar",
          "url": "image_clipper_release-10.1.aar",
          "size": 4682,
          "sha512": "2589309a1a4e219c4f1150ec98978b8cc41270ca64ec89dfb9a388a31a7657cdf8dee0de6c786af421da044e0d972b99a9e98a34725bf76a907d6523feba22b5",
          "sha256": "08eec7057a71acbe91d6aed4160112a04a0b8546e74b68bbf7e54cfff42497c2",
          "sha1": "dd1dd9e3b16f69bff4db7ff1e12a7db81b9a7389",
          "md5": "07325f41afc1c41dd071e14e3393b613"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_clipper_release-10.1-sources.jar",
          "url": "image_clipper_release-10.1-sources.jar",
          "size": 2090,
          "sha512": "49a3d855e5adb04581fc58ac9edb4eefae04d9d5087c1f7acf55558069ef19aeb173055f11ed46c983fa88e900ad0f2e41bb5c7fde7ffc07f23c7c4d04c442ff",
          "sha256": "d90937921945ff45bd0e060ab98b28237b0305883d241a92e34e6959c12b279a",
          "sha1": "cae6d4ec31fbbb4a9b5b53ef98c1178dfa2ea085",
          "md5": "b2ab330d3f15077d302f465949bacac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_clipper_release-10.1-javadoc.jar",
          "url": "image_clipper_release-10.1-javadoc.jar",
          "size": 262196,
          "sha512": "a001f4f0dbde587ac169effe639ebecd5e43e702213fbf870dc1d88480f7140243ddbe07a7ecf2df1e43d82613f16655ed7f1d2293e5dcd1916abdc46e288fdf",
          "sha256": "3c8b739575bc84b9a93bdc71f080d3c8bbc9817127cbc84fd04f603078fa1c33",
          "sha1": "b4f78dc7e032f78bdbc8855c61f6d3b884376162",
          "md5": "92f4394c2ca9f8cac255d1291786b2c7"
        }
      ]
    }
  ]
}
