{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.azure_speech",
    "module": "azure_speech_release",
    "version": "10.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.9.aar",
          "url": "azure_speech_release-10.9.aar",
          "size": 12704,
          "sha512": "f9ff524e5efefea3665b3f6b3e7cb8a9387661db3383d1fb659b57b09b97c0c2dabdee3d82dc2be72a4f005bef2de9c5c7031944ae4a9ddfcc8b1b4ae2f1c9b0",
          "sha256": "936e6ef87aed7ca54729b52aeb066a514578aff115345d809c22402fbddb10c8",
          "sha1": "97aa2e8d4ee08184b3b591e354e8741f59d92ecd",
          "md5": "eae9321999c5b58d72eab38a8004a94c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.48.2"
          }
        }
      ],
      "files": [
        {
          "name": "azure_speech_release-10.9.aar",
          "url": "azure_speech_release-10.9.aar",
          "size": 12704,
          "sha512": "f9ff524e5efefea3665b3f6b3e7cb8a9387661db3383d1fb659b57b09b97c0c2dabdee3d82dc2be72a4f005bef2de9c5c7031944ae4a9ddfcc8b1b4ae2f1c9b0",
          "sha256": "936e6ef87aed7ca54729b52aeb066a514578aff115345d809c22402fbddb10c8",
          "sha1": "97aa2e8d4ee08184b3b591e354e8741f59d92ecd",
          "md5": "eae9321999c5b58d72eab38a8004a94c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.9-sources.jar",
          "url": "azure_speech_release-10.9-sources.jar",
          "size": 4716,
          "sha512": "d6737e296ebf8b9f610cdec4dae5a749683f680dec0589a9cdf14e595c5f4481b5592e14054e1a5ba40cae2aec4cb588125945944616cd63376d5739713025fe",
          "sha256": "a4ebcba754bea5ab4c8548460e1ee3b5148d978654bb4b8591c92e8e0abd9dbe",
          "sha1": "2cfafee64360f6b41ec994f0c8e247a674e6efad",
          "md5": "e0d7339802f8667f06b36eca5e27a2f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "azure_speech_release-10.9-javadoc.jar",
          "url": "azure_speech_release-10.9-javadoc.jar",
          "size": 262147,
          "sha512": "fc19ac24f4b87e8f8f56f936df1b5dbe1f109c23c8cd62173490d36214126bad453721aeccef6092126f132bb8b82ef682f9d31d68dff494f9b15bcdeb1866c6",
          "sha256": "bd40074790ef1d2a7c220e29e3aa06ccc84510fd61785b25f697be0ceef7707f",
          "sha1": "801baee101d5cb7b930253014081589a21f39e06",
          "md5": "43adcfe66d11f14ac5b27fd3b700dbe5"
        }
      ]
    }
  ]
}
