{
  "formatVersion": "1.1",
  "component": {
    "group": "com.builttoroam.devicecalendar",
    "module": "device_calendar_release",
    "version": "10.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-10.4.aar",
          "url": "device_calendar_release-10.4.aar",
          "size": 70884,
          "sha512": "30ebf229e7ad5c17ece2500796326c6b34966d315b060b8c9272b468fb2991ce07bf260abb4a33355ed9739d2f402337702e45a92fafed3b3aca8ed8321eb2e6",
          "sha256": "65268f26271e985a6881120c03dfdf45eed3bb764e6a7e97151d61312bd44c85",
          "sha1": "bb201f4393a5db2a0ac2afe63b54e9b60687262a",
          "md5": "18d2309f74a8e6e2286c48333b6199e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.dmfs",
          "module": "lib-recur",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "device_calendar_release-10.4.aar",
          "url": "device_calendar_release-10.4.aar",
          "size": 70884,
          "sha512": "30ebf229e7ad5c17ece2500796326c6b34966d315b060b8c9272b468fb2991ce07bf260abb4a33355ed9739d2f402337702e45a92fafed3b3aca8ed8321eb2e6",
          "sha256": "65268f26271e985a6881120c03dfdf45eed3bb764e6a7e97151d61312bd44c85",
          "sha1": "bb201f4393a5db2a0ac2afe63b54e9b60687262a",
          "md5": "18d2309f74a8e6e2286c48333b6199e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-10.4-sources.jar",
          "url": "device_calendar_release-10.4-sources.jar",
          "size": 19259,
          "sha512": "596df879875dbeecd1171483bba32882cbf94115c8c1448185b993e296994006c7652e4315a994630107b6812bdd5cd1a1562c866d3c0dce284107f4409c2ab6",
          "sha256": "b873a00db27dcf44fb83ed111ce903da44f6dbdf95b5c0ba1c98f0ec56eca9e3",
          "sha1": "6f9e51b7f1534e2d360107cf836efc201ff41c23",
          "md5": "9c871bf2f63334dba398899b5e5ab6e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_calendar_release-10.4-javadoc.jar",
          "url": "device_calendar_release-10.4-javadoc.jar",
          "size": 369714,
          "sha512": "c33ca11ba3144ea52fdbdb274a9019eb87e716bc4339789fb2ee49ec30207b0b7c00afbdb6a57284fe892da80853a207994fba025b8f770b1d4bd62f707b0cd2",
          "sha256": "c8ef7dceeb4211b0551bb6e45b7a989052de325e296e9603736d7dc2ad327012",
          "sha1": "a1c569dd0706e48fae495303862a5e3524b0ba2d",
          "md5": "f2f040f930d89130dc6685d91dde0d61"
        }
      ]
    }
  ]
}
