{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.sbc",
    "module": "sbc_release",
    "version": "9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-9.6.aar",
          "url": "sbc_release-9.6.aar",
          "size": 72196,
          "sha512": "41ae08e022c73ff01e0b7ef23ecc39c81af40adb8885bc0307d8bae61852ea0ac3d7e3f205cd8cd4a2213e53ab1895cd7ec2f5be9ca32302dc2a69b5f68d713b",
          "sha256": "9d833512941e0c1a6ad297deb374215fc2884e33b56199bfc3eee6ddae4a0c0b",
          "sha1": "07b6425c273faa6588ac732034a0e657f817ca52",
          "md5": "47474304c2e1910891eb0fa97473d343"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sbc_release-9.6.aar",
          "url": "sbc_release-9.6.aar",
          "size": 72196,
          "sha512": "41ae08e022c73ff01e0b7ef23ecc39c81af40adb8885bc0307d8bae61852ea0ac3d7e3f205cd8cd4a2213e53ab1895cd7ec2f5be9ca32302dc2a69b5f68d713b",
          "sha256": "9d833512941e0c1a6ad297deb374215fc2884e33b56199bfc3eee6ddae4a0c0b",
          "sha1": "07b6425c273faa6588ac732034a0e657f817ca52",
          "md5": "47474304c2e1910891eb0fa97473d343"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sbc_release-9.6-sources.jar",
          "url": "sbc_release-9.6-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sbc_release-9.6-javadoc.jar",
          "url": "sbc_release-9.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
