{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-2.0.aar",
          "url": "permission_handler_android_release-2.0.aar",
          "size": 28849,
          "sha512": "69dc9644cf895508eeb407777ac9fe16ef9b701553d25a39d868fbc198c5f2c2d279bbf193565fe30ba6f85cb7ffa8840d51fbc254db4b57052737af36fc8788",
          "sha256": "16ca0d3b69a5e50ed6779f6d4610ac1f49dcf99c75393929a7a954933ded6831",
          "sha1": "e93b2211a67abcd2a0cb8f1c7812f63cbb2fe559",
          "md5": "a5aec633398681f0fb4599ae45a87d08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-2.0.aar",
          "url": "permission_handler_android_release-2.0.aar",
          "size": 28849,
          "sha512": "69dc9644cf895508eeb407777ac9fe16ef9b701553d25a39d868fbc198c5f2c2d279bbf193565fe30ba6f85cb7ffa8840d51fbc254db4b57052737af36fc8788",
          "sha256": "16ca0d3b69a5e50ed6779f6d4610ac1f49dcf99c75393929a7a954933ded6831",
          "sha1": "e93b2211a67abcd2a0cb8f1c7812f63cbb2fe559",
          "md5": "a5aec633398681f0fb4599ae45a87d08"
        }
      ]
    }
  ]
}
