{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "0.0.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.61.aar",
          "url": "shared_preferences_android_release-0.0.61.aar",
          "size": 112331,
          "sha512": "675e2674f79668530cab2fb38513a636ceb2bb79a415a6bdc92ad79c7e95ee6e91cdaaa18a22b3d7b2be8bb957b96e082ef04eaae992980fb216c13cb3ad3162",
          "sha256": "e4b21a21ad888f2ee0313f54111ef8fbc87f4b38d68371a94d390b247b0d16c8",
          "sha1": "aba76d96563d8de782c2105d4d5b323c3f546b80",
          "md5": "f8bbe74713a76bb4d1de32664a5b5cf6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-83675ed27633283e7fc296c8bca22e841224c096"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.61.aar",
          "url": "shared_preferences_android_release-0.0.61.aar",
          "size": 112331,
          "sha512": "675e2674f79668530cab2fb38513a636ceb2bb79a415a6bdc92ad79c7e95ee6e91cdaaa18a22b3d7b2be8bb957b96e082ef04eaae992980fb216c13cb3ad3162",
          "sha256": "e4b21a21ad888f2ee0313f54111ef8fbc87f4b38d68371a94d390b247b0d16c8",
          "sha1": "aba76d96563d8de782c2105d4d5b323c3f546b80",
          "md5": "f8bbe74713a76bb4d1de32664a5b5cf6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.61-sources.jar",
          "url": "shared_preferences_android_release-0.0.61-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-0.0.61-javadoc.jar",
          "url": "shared_preferences_android_release-0.0.61-javadoc.jar",
          "size": 358450,
          "sha512": "c13b61d28a79b4519ac8d4719fefd33ff5a1118ff3dc458a8f5ae04165896f61e9de34b8b6c1ff75764437fd1026d007e4c7ee166c0bd9adfc9fb8eabb2157ca",
          "sha256": "5f5d6a23cc6f20c120f4afd8ba40114334dc9ab1a0887fe8859dd69a787f9c97",
          "sha1": "370617f039c89e21b3a33b82c9e5bcc48920f4b3",
          "md5": "33c71258ebd5929cda35f046d9fa9b7f"
        }
      ]
    }
  ]
}
