{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.creek_blue_manage",
    "module": "creek_blue_manage_release",
    "version": "6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-6.3.aar",
          "url": "creek_blue_manage_release-6.3.aar",
          "size": 19366,
          "sha512": "9a885f5b16bb117b6e343f017b7446994c39281964b5581b4d94f7ee80631570b80b3ce287b5064fd219e40b2b83c1b5b18c766c185d577448f9cd7679c8b34f",
          "sha256": "0a3ffca6c34ec4fe939031d2bb1ef762f393bd256592943a782289e0ffd79ec1",
          "sha1": "98fb3014d3d5a695a6c51f2b74f91c9b4700c214",
          "md5": "7ff32195f1118d0ba0d84fd5405308e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "com.example.lz4",
          "module": "lz4_release",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "com.boskokg.flutter_blue_plus",
          "module": "flutter_blue_plus_release",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "com.example.sbc",
          "module": "sbc_release",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "com.example.creek_sleep_stage_algorithm",
          "module": "creek_sleep_stage_algorithm_release",
          "version": {
            "requires": "6.3"
          }
        }
      ],
      "files": [
        {
          "name": "creek_blue_manage_release-6.3.aar",
          "url": "creek_blue_manage_release-6.3.aar",
          "size": 19366,
          "sha512": "9a885f5b16bb117b6e343f017b7446994c39281964b5581b4d94f7ee80631570b80b3ce287b5064fd219e40b2b83c1b5b18c766c185d577448f9cd7679c8b34f",
          "sha256": "0a3ffca6c34ec4fe939031d2bb1ef762f393bd256592943a782289e0ffd79ec1",
          "sha1": "98fb3014d3d5a695a6c51f2b74f91c9b4700c214",
          "md5": "7ff32195f1118d0ba0d84fd5405308e2"
        }
      ]
    }
  ]
}
