{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.image_clipper",
    "module": "image_clipper_release",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "image_clipper_release-0.0.8.aar",
          "url": "image_clipper_release-0.0.8.aar",
          "size": 7955,
          "sha512": "aa88f4664817b84cdcdf73f9e7a7bb7237fadabbb2a9fa3a34f3cd1d9af2a543dd56aeb717620c83b6912ff64e7caa6fd1c52d59abecf98e00dc62e0cf499d47",
          "sha256": "adcfdb62648e2681ecd599875becdd355c352442a91cfa3c86a6e7772f6cad99",
          "sha1": "27d4a091bd82e80655f894d1e78135a397134940",
          "md5": "5596d6b9f186b63ab8267334f8ad2aaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "image_clipper_release-0.0.8.aar",
          "url": "image_clipper_release-0.0.8.aar",
          "size": 7955,
          "sha512": "aa88f4664817b84cdcdf73f9e7a7bb7237fadabbb2a9fa3a34f3cd1d9af2a543dd56aeb717620c83b6912ff64e7caa6fd1c52d59abecf98e00dc62e0cf499d47",
          "sha256": "adcfdb62648e2681ecd599875becdd355c352442a91cfa3c86a6e7772f6cad99",
          "sha1": "27d4a091bd82e80655f894d1e78135a397134940",
          "md5": "5596d6b9f186b63ab8267334f8ad2aaa"
        }
      ]
    }
  ]
}
