{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.2.aar",
          "url": "permission_handler_android_release-0.0.2.aar",
          "size": 26443,
          "sha512": "14a2033269ce0732ddcef99f046fa307daa4e11a13029109a72b3da946d299d7f5ff9c6f6eb7b9f38439f14b6bbd647ea2ebd3e3ce97422641b80ad32c740f38",
          "sha256": "b92a0e7d32db5eddbe5870459824f2532c851a53f94e58f0243e702f3b14a419",
          "sha1": "3b07c1a0560bd1fbc9c8df7fc05cae2b8ffeba42",
          "md5": "bbacca53410c75afb2d86da403a42214"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.2.aar",
          "url": "permission_handler_android_release-0.0.2.aar",
          "size": 26443,
          "sha512": "14a2033269ce0732ddcef99f046fa307daa4e11a13029109a72b3da946d299d7f5ff9c6f6eb7b9f38439f14b6bbd647ea2ebd3e3ce97422641b80ad32c740f38",
          "sha256": "b92a0e7d32db5eddbe5870459824f2532c851a53f94e58f0243e702f3b14a419",
          "sha1": "3b07c1a0560bd1fbc9c8df7fc05cae2b8ffeba42",
          "md5": "bbacca53410c75afb2d86da403a42214"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.2-sources.jar",
          "url": "permission_handler_android_release-0.0.2-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.2-javadoc.jar",
          "url": "permission_handler_android_release-0.0.2-javadoc.jar",
          "size": 264576,
          "sha512": "18d0b0901b26032c7e67abaceee54a201ffff091a61adc385913c0c8c5d8afc1b9b9b33674188e1133852d53eec661737327bb6368cd468e2f851ac53f4bca3f",
          "sha256": "e34e54db8513634cfc1649f6b970013e06fbd9e3b04b5be5da643e6df755a2c4",
          "sha1": "f23a16f884167194e2d8e19ca80b0ca241e473b7",
          "md5": "755f41803075fb42d9d256dcdeae9b2f"
        }
      ]
    }
  ]
}
