{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "10.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.3.aar",
          "url": "shared_preferences_android_release-10.3.aar",
          "size": 89515,
          "sha512": "e11ce0dfd08bbde09d99683a7ae78b350cf367bc59f7eb288e5567bae59479656fb10599bf030c720693e2562b9f460b02d00e883b2aa05d3990b810eb8a72c6",
          "sha256": "78dd26c83afc0cac4fb98fe39cff259a592ea7ffb5dda0bfc7cabdf7688fd7d9",
          "sha1": "226fa4d44fa8b10d7a6dcb60da0815349e4bdcb1",
          "md5": "303c4f4df62d65e4deeff6c30efb91d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-10.3.aar",
          "url": "shared_preferences_android_release-10.3.aar",
          "size": 89515,
          "sha512": "e11ce0dfd08bbde09d99683a7ae78b350cf367bc59f7eb288e5567bae59479656fb10599bf030c720693e2562b9f460b02d00e883b2aa05d3990b810eb8a72c6",
          "sha256": "78dd26c83afc0cac4fb98fe39cff259a592ea7ffb5dda0bfc7cabdf7688fd7d9",
          "sha1": "226fa4d44fa8b10d7a6dcb60da0815349e4bdcb1",
          "md5": "303c4f4df62d65e4deeff6c30efb91d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.3-sources.jar",
          "url": "shared_preferences_android_release-10.3-sources.jar",
          "size": 10391,
          "sha512": "c868c1a7019fbb013fc8f7393122f858679c552ee0b0521b78fd01d85a7e22b805f61c1c78db0c81d3d68ca28cb891a1450cbc3be4566fb39ffbc055a7bc22a1",
          "sha256": "4b7a533aea864be65713bbe35408e2eeaaf886febc2e0ff80f6d86c800f0eae9",
          "sha1": "e8a73be85d3672522581e4d702ba7289cd7a69ef",
          "md5": "e196aac4401e72d313a388902984ab00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-10.3-javadoc.jar",
          "url": "shared_preferences_android_release-10.3-javadoc.jar",
          "size": 326413,
          "sha512": "949c74e685ac1bb71131d44a4a5117eb58753d492f23e18cfb678258771ddd0fe806387fd84250aedf8d9c2f8608d0e9bb390c0c0837cb32ccece97c552ed27b",
          "sha256": "753fa8d113c8a216e35789dcad616197b73ec2807f18b5820b53130a0acf88ca",
          "sha1": "fca8f25fdf80bd09fceb6eb8ec42090c4baafad7",
          "md5": "de439bc9b5b53ec066f93197faeadb09"
        }
      ]
    }
  ]
}
