{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.25.aar",
          "url": "permission_handler_android_release-0.0.25.aar",
          "size": 26441,
          "sha512": "75b2f117fdc712618b5a084e01dfc9785de24b10c862b218c3b0f214f7e20c11d9434a8a114330276996effe73820b566c32823eb00e2eaf457b8974b60e0979",
          "sha256": "0f98bb87e91586eb8bb736ae821af20166bce26baee25bd316f6786ee7eb7c53",
          "sha1": "d2e7122f9b6bfa25d2ebc2b317679746a670da10",
          "md5": "65600598f715f09db0ab2ea0f9dff0dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.0.25.aar",
          "url": "permission_handler_android_release-0.0.25.aar",
          "size": 26441,
          "sha512": "75b2f117fdc712618b5a084e01dfc9785de24b10c862b218c3b0f214f7e20c11d9434a8a114330276996effe73820b566c32823eb00e2eaf457b8974b60e0979",
          "sha256": "0f98bb87e91586eb8bb736ae821af20166bce26baee25bd316f6786ee7eb7c53",
          "sha1": "d2e7122f9b6bfa25d2ebc2b317679746a670da10",
          "md5": "65600598f715f09db0ab2ea0f9dff0dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.25-sources.jar",
          "url": "permission_handler_android_release-0.0.25-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.0.25-javadoc.jar",
          "url": "permission_handler_android_release-0.0.25-javadoc.jar",
          "size": 264580,
          "sha512": "6ff6ec3f5990cac2eb0136a7b419646149007c89ee51982d44efda2b8ee21122ae0b9134423406cc3fbcf4c73d81f915f241d06942a518e7db716d8f6b0c310e",
          "sha256": "014aeb5b7001258394f4c36f0b93e99d6d3fd8d23aa248ff1bea6c4987b719a1",
          "sha1": "24a78278c23bcbd20e3bff1789b42f2bff7413dc",
          "md5": "c4ddb29f2389b00d308b40949955d628"
        }
      ]
    }
  ]
}
